/**
 * Case company roster for the Marketing Academy projects layer.
 *
 * Every entry below has a verified, cited exit event (acquisition, IPO,
 * direct listing, or SPAC merger) — a real company chosen as the backdrop
 * for one or more hands-on projects (PROJECTS_PLAN.md Stage 8). Each
 * `exit.source` is a URL to a press release or reputable news report
 * confirming the deal terms and date.
 *
 * This started as a Phase 0 starter roster per PROJECTS_PLAN.md Stage 8.1
 * targeting ~40 companies; a gap-fill pass (mid/small-scale exits plus
 * additional India-region companies) brought it to 77 companies. It is
 * expected to grow toward ~150 in Phase 2 as more project content is built
 * out.
 *
 * Barred companies — DO NOT re-add these. Prior research passes confirmed
 * they have no verifiable exit event (still private, or no confirmed
 * acquisition/IPO/listing at the time of research):
 *   CRED, Zerodha, Zoho, Dream11, Glossier, Away, Harry's, Figma
 *
 * If a future research pass finds a confirmed exit for any barred company,
 * update this comment and AGENTS.md Rule 37 together, do not just add the
 * entry.
 */
import type { CaseCompany } from "@/lib/projects/types";

export const CASE_COMPANIES: CaseCompany[] = [
  // ---------------------------------------------------------------------
  // Global
  // ---------------------------------------------------------------------
  {
    id: "slack",
    name: "Slack",
    website: "https://slack.com",
    industry: "Business messaging / team collaboration SaaS",
    sector: "SaaS",
    region: "global",
    hq: "San Francisco, USA",
    founded: 2013,
    sizeAtExit: "~2,500 employees, 10M+ daily active users, 85,000+ paid customers",
    revenueAtExit: "~$900M revenue (FY2020)",
    bestKnownFor:
      "Freemium, product-led growth with a viral team-invite loop that turned internal workplace chat into its own SaaS category",
    disciplines: ["growth", "product-marketing", "content", "brand-strategy"],
    exit: {
      type: "acquisition",
      scale: "mega",
      date: "2021-07-21",
      valueLabel: "$27.7B (cash and stock)",
      acquirer: "Salesforce",
      source: "https://www.salesforce.com/news/press-releases/2021/07/21/salesforce-slack-deal-close/",
    },
    keyNumbers: [
      "$27.7B acquisition price, Salesforce's largest deal ever",
      "10M+ daily active users at acquisition",
      "85,000+ paid customers",
      "~$900M revenue in 2020",
    ],
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    website: "https://mailchimp.com",
    industry: "Email marketing & marketing automation SaaS",
    sector: "SaaS",
    region: "global",
    hq: "Atlanta, USA",
    founded: 2001,
    sizeAtExit: "1,200+ employees",
    revenueAtExit: "$800M revenue (2020), expected to cross $1B in 2021",
    bestKnownFor:
      "Bootstrapped SMB email-marketing brand built on freemium onboarding and the distinctive Freddie-the-chimp mascot identity, sold for $12B without ever raising outside VC funding",
    disciplines: ["email", "brand-strategy", "content", "growth"],
    exit: {
      type: "acquisition",
      scale: "mega",
      date: "2021-11-01",
      valueLabel: "$12B ($5.7B cash + $6.3B stock)",
      acquirer: "Intuit",
      source: "https://mailchimp.com/newsroom/intuit-completes-mailchimp-acquisition/",
    },
    keyNumbers: [
      "$12B deal, largest bootstrapped startup exit on record",
      "$800M revenue in 2020",
      "1,200+ employees at close",
      "Never raised outside venture funding before the sale",
    ],
  },
  {
    id: "dollar-shave-club",
    name: "Dollar Shave Club",
    website: "https://www.dollarshaveclub.com",
    industry: "DTC grooming / subscription ecommerce",
    sector: "D2C",
    region: "global",
    hq: "Venice, California, USA",
    founded: 2011,
    sizeAtExit: "3.2M subscribers",
    revenueAtExit: "$152M revenue (2015), on pace for $200M+ in 2016",
    bestKnownFor:
      "The 2012 low-budget viral founder-led launch video that became the textbook case study for scrappy DTC video marketing and subscription-commerce growth",
    disciplines: ["content", "brand-strategy", "growth", "copywriting"],
    exit: {
      type: "acquisition",
      scale: "mega",
      date: "2016-07-19",
      valueLabel: "$1B cash",
      acquirer: "Unilever",
      source: "https://www.forbes.com/sites/ryanmac/2016/07/20/unilever-purchases-dollar-shave-club-for-1-billion/",
    },
    keyNumbers: [
      "$1B acquisition price",
      "3.2M subscribers at acquisition",
      "$152M revenue in 2015",
      "One of the largest ecommerce acquisitions at the time, alongside Amazon-Zappos",
    ],
  },
  {
    id: "jet-com",
    name: "Jet.com",
    website: "https://en.wikipedia.org/wiki/Jet.com",
    industry: "Ecommerce marketplace with dynamic bulk-discount pricing",
    sector: "Ecommerce",
    region: "global",
    hq: "Hoboken, New Jersey, USA",
    founded: 2014,
    sizeAtExit: "1,000-5,000 employees (2016)",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "A 'basket size' dynamic-pricing engine paired with an aggressive growth-marketing land grab that made it the most expensive US ecommerce acquisition of all time at the deal date",
    disciplines: ["growth", "paid-ads", "product-marketing", "analytics"],
    exit: {
      type: "acquisition",
      scale: "mega",
      date: "2016-09-19",
      valueLabel: "$3.3B ($3B cash + $300M stock)",
      acquirer: "Walmart",
      source: "https://corporate.walmart.com/news/2016/09/19/walmart-completes-acquisition-of-jet-com-inc",
    },
    keyNumbers: [
      "$3.3B acquisition, most expensive US ecommerce deal at the time",
      "1,000-5,000 employees at acquisition",
      "Wound down by Walmart in 2020, four years after the deal",
    ],
  },
  {
    id: "bonobos",
    name: "Bonobos",
    website: "https://bonobos.com",
    industry: "DTC menswear / vertical apparel brand",
    sector: "D2C",
    region: "global",
    hq: "New York City, USA",
    founded: 2007,
    sizeAtExit: "300+ employees",
    revenueAtExit: "~$115M revenue",
    bestKnownFor:
      "Pioneering the no-inventory 'Guideshop' retail model, showrooms for trying on product where every order ships to the customer's home",
    disciplines: ["brand-strategy", "content", "cro", "product-marketing"],
    exit: {
      type: "acquisition",
      scale: "large",
      date: "2017-06-16",
      valueLabel: "$310M cash",
      acquirer: "Walmart",
      source:
        "https://techcrunch.com/2017/06/16/walmart-to-buy-bonobos-for-310m-in-its-bigger-push-into-fashion-retail/",
    },
    keyNumbers: [
      "$310M acquisition price",
      "~$115M revenue prior to acquisition",
      "300+ employees",
      "Later resold by Walmart to Express/WHP Global for $75M in 2023",
    ],
  },
  {
    id: "zendesk",
    name: "Zendesk",
    website: "https://www.zendesk.com",
    industry: "Customer service & support-ticketing SaaS",
    sector: "SaaS",
    region: "global",
    hq: "San Francisco, USA (founded in Copenhagen, Denmark)",
    founded: 2007,
    sizeAtExit: "5,860+ employees (2021), 100,000+ brand customers",
    revenueAtExit: "$1.34B revenue (2021)",
    bestKnownFor:
      "Land-and-expand product-led growth, selling helpdesk software bottom-up to support teams before moving upmarket into enterprise accounts",
    disciplines: ["growth", "product-marketing", "content", "analytics"],
    exit: {
      type: "acquisition",
      scale: "mega",
      date: "2022-11-22",
      valueLabel: "$10.2B ($77.50/share cash)",
      acquirer: "Hellman & Friedman and Permira (investor consortium, with ADIA and GIC)",
      source:
        "https://www.permira.com/news-and-insights/announcements/consortium-led-by-hellman-friedman-and-permira-completes-acquisition-of-zendesk",
    },
    keyNumbers: [
      "$10.2B take-private deal",
      "$77.50 per share cash",
      "100,000+ brand customers",
      "$1.34B revenue in 2021",
    ],
  },
  {
    id: "trade-desk",
    name: "The Trade Desk",
    website: "https://www.thetradedesk.com",
    industry: "Programmatic advertising demand-side platform (adtech)",
    sector: "SaaS",
    region: "global",
    hq: "Ventura, California, USA",
    founded: 2009,
    sizeAtExit: "undisclosed",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "Built the leading independent, non-walled-garden programmatic ad-buying platform, positioned as the transparent alternative to Google/Facebook ad tech during the rise of real-time bidding",
    disciplines: ["paid-ads", "analytics", "product-marketing"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2016-09-21",
      valueLabel:
        "$18.00/share IPO price (~$74.1M net proceeds raised); began trading on Nasdaq as TTD, closed first day at $30.10 (+67%)",
      source:
        "https://investors.thetradedesk.com/news-and-events/news/news-details/2016/The-Trade-Desk-Announces-Pricing-of-Initial-Public-Offering-09-20-2016/default.aspx",
    },
    keyNumbers: [
      "IPO priced at $18.00/share, closed first day at $30.10 (+67%)",
      "~$74.1M net proceeds raised at IPO",
      "5,366,667 Class A shares sold (incl. full over-allotment)",
      "Founded 2009 by Jeff Green",
    ],
  },
  {
    id: "care-com",
    name: "Care.com",
    website: "https://www.care.com",
    industry: "Online marketplace for family/child/senior/pet care services",
    sector: "Marketplace",
    region: "global",
    hq: "Waltham, Massachusetts, USA",
    founded: 2006,
    sizeAtExit: "31.7M members in 2019 (16.9M families, 12.7M caregivers)",
    revenueAtExit: "$192M revenue (2018)",
    bestKnownFor:
      "Built the largest online marketplace matching families with caregivers, driven by local-search SEO demand and a trust/safety-focused conversion funnel",
    disciplines: ["seo", "growth", "cro", "content"],
    exit: {
      type: "acquisition",
      scale: "large",
      date: "2020-02-11",
      valueLabel: "$500M enterprise value ($15.00/share; ~$627.5M total consideration incl. equity settlement)",
      acquirer: "IAC",
      source: "https://www.iac.com/press-releases/iac-announces-close-of-500-million-care-com-acquisition",
    },
    keyNumbers: [
      "$500M enterprise value at $15.00/share",
      "31.7M members in 2019 (16.9M families, 12.7M caregivers)",
      "$192M revenue in 2018",
      "Later resold by IAC to Pacific Avenue Capital Partners for $320M in 2023",
    ],
  },
  {
    id: "instacart",
    name: "Instacart",
    website: "https://instacart.com",
    industry: "Grocery delivery / on-demand marketplace",
    sector: "Foodtech",
    region: "global",
    hq: "San Francisco, USA",
    founded: 2012,
    sizeAtExit: "undisclosed employee count; serves 1,400+ retail banners and 85% of US grocery market at IPO",
    revenueAtExit: "$2.55B revenue (FY2022, per S-1)",
    bestKnownFor:
      "Building a two-sided grocery marketplace via retailer co-marketing partnerships and in-app retail media/ads business instead of consumer mass-advertising",
    disciplines: ["growth", "product-marketing", "brand-strategy", "analytics"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2023-09-19",
      valueLabel: "$30/share IPO price, ~$10B valuation (fully diluted); opened at $42/share on Nasdaq",
      source: "https://www.cnbc.com/2023/09/18/instacart-prices-ipo-at-30-a-share.html",
    },
    keyNumbers: [
      "IPO priced at $30/share, ~$10B fully diluted valuation (Sept 18, 2023)",
      "Shares opened at $42 on Nasdaq debut, closed at $33.70",
      "Valuation down from a $39B peak private valuation in early 2021",
      "$2.55B FY2022 revenue at time of IPO filing",
    ],
  },
  {
    id: "klaviyo",
    name: "Klaviyo",
    website: "https://klaviyo.com",
    industry: "Email/SMS marketing automation SaaS for ecommerce",
    sector: "SaaS",
    region: "global",
    hq: "Boston, USA",
    founded: 2012,
    sizeAtExit: "undisclosed employee count; 130,000+ customers at IPO",
    revenueAtExit: "undisclosed exact figure; reported profitable at scale pre-IPO",
    bestKnownFor:
      "Product-led growth via deep Shopify integration and data-driven, owned-channel (email/SMS) marketing for DTC brands",
    disciplines: ["email", "growth", "product-marketing", "analytics"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2023-09-20",
      valueLabel: "$30/share IPO price, $9.2B valuation; opened at $36.75 on NYSE",
      source: "https://www.cnbc.com/2023/09/19/klaviyo-considers-pricing-ipo-at-top-of-range-or-above-reuters.html",
    },
    keyNumbers: [
      "IPO priced at $30/share above range, $9.2B valuation (Sept 19, 2023)",
      "Sold 19.2M shares, raising ~$576M",
      "Stock rose ~9% on NYSE debut, closing at $32.76",
      "130,000+ customers at time of IPO",
    ],
  },
  {
    id: "airbnb",
    name: "Airbnb",
    website: "https://airbnb.com",
    industry: "Short-term rental / travel marketplace",
    sector: "Travel",
    region: "global",
    hq: "San Francisco, USA",
    founded: 2008,
    sizeAtExit: "~5,600 employees; 4M+ hosts, 220+ countries at IPO",
    revenueAtExit: "$3.4B revenue (FY2020, pandemic-depressed)",
    bestKnownFor:
      "Community-driven brand storytelling (\"Belong Anywhere\") and host-generated content/UGC as the core acquisition engine instead of paid performance marketing",
    disciplines: ["brand-strategy", "content", "growth", "pr-communications"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2020-12-10",
      valueLabel: "$68/share IPO price, $47B fully diluted valuation; closed first day near $99.5B market cap",
      source: "https://www.cnbc.com/2020/12/09/airbnb-sells-shares-at-68-in-ipo-pricing-above-range.html",
    },
    keyNumbers: [
      "IPO priced at $68/share, $47B valuation (Dec 9, 2020)",
      "First trade at $146/share; closed day one near $99.5B valuation",
      "Raised ~$3.5B in the offering",
      "Stock rose ~113% on debut day",
    ],
  },
  {
    id: "doordash",
    name: "DoorDash",
    website: "https://doordash.com",
    industry: "Food delivery / local commerce logistics",
    sector: "Foodtech",
    region: "global",
    hq: "San Francisco, USA",
    founded: 2013,
    sizeAtExit: "undisclosed employee count; ~450,000 merchants, ~20M consumers at IPO",
    revenueAtExit: "$2.9B revenue (FY2020)",
    bestKnownFor:
      "Winning suburban/lower-density markets via aggressive local merchant-acquisition and city-by-city growth marketing that out-executed better-funded rivals in dense urban cores",
    disciplines: ["growth", "analytics", "product-marketing", "affiliate-marketing"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2020-12-09",
      valueLabel: "$102/share IPO price, $32.4B valuation; first-day close valuation ~$60.2B",
      source: "https://www.forbes.com/sites/jonathanponciano/2020/12/09/doordash-ipo-shares-first-day-of-trading/",
    },
    keyNumbers: [
      "IPO priced at $102/share, $32.4B valuation (Dec 9, 2020)",
      "Stock opened at $182/share, closed at $189.51, up ~86%",
      "Raised ~$3.3B net proceeds",
      "$2.9B FY2020 revenue",
    ],
  },
  {
    id: "warby-parker",
    name: "Warby Parker",
    website: "https://warbyparker.com",
    industry: "DTC eyewear / omnichannel retail",
    sector: "D2C",
    region: "global",
    hq: "New York, USA",
    founded: 2010,
    sizeAtExit: "~3,000 employees; 161 retail stores at IPO",
    revenueAtExit: "$540M revenue (FY2021)",
    bestKnownFor:
      "Pioneering the DTC playbook: home try-on program, buy-one-give-one social mission storytelling, and brand-led content as an alternative to traditional optical retail advertising",
    disciplines: ["brand-strategy", "content", "pr-communications", "cro"],
    exit: {
      type: "direct-listing",
      scale: "large",
      date: "2021-09-29",
      valueLabel: "$40 reference price, ~$4.98B valuation; opened at $54.05/share (~$6B+ valuation)",
      source: "https://www.cnbc.com/2021/09/29/warby-parker-direct-listing-wrby-starts-trading-on-the-nyse.html",
    },
    keyNumbers: [
      "Reference price $40/share, $4.98B valuation (Sept 29, 2021)",
      "Opened at $54.05/share, implied valuation over $6B",
      "Closed first day up 36% at $54.49, valuation over $6B",
      "$540M FY2021 revenue",
    ],
  },
  {
    id: "chewy",
    name: "Chewy",
    website: "https://chewy.com",
    industry: "Pet products ecommerce / subscription (Autoship)",
    sector: "Ecommerce",
    region: "global",
    hq: "Plantation, USA",
    founded: 2011,
    sizeAtExit: "undisclosed employee count at IPO; majority-owned by PetSmart",
    revenueAtExit: "$3.5B net sales (FY2018, per S-1)",
    bestKnownFor:
      "Legendary customer-service-as-marketing (handwritten condolence cards, oil-painting pet portraits) driving word-of-mouth loyalty and retention in a commodity category",
    disciplines: ["brand-strategy", "cro", "email", "content"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2019-06-14",
      valueLabel:
        "$22/share IPO price, ~$8.8B valuation at pricing; opened at $36/share (~$14B market cap)",
      source:
        "https://www.cnbc.com/2019/06/14/chewycom-petsmarts-online-business-opens-at-36-after-pricing-at-22-per-share.html",
    },
    keyNumbers: [
      "IPO priced at $22/share, raising $1.02B (June 14, 2019)",
      "Opened at $36/share, up 64%, market cap over $14B",
      "$3.5B net sales in FY2018 per S-1 filing",
      "46.5M shares offered, mostly by parent PetSmart",
    ],
  },
  {
    id: "duolingo",
    name: "Duolingo",
    website: "https://duolingo.com",
    industry: "Language-learning mobile app / edtech",
    sector: "Edtech",
    region: "global",
    hq: "Pittsburgh, USA",
    founded: 2011,
    sizeAtExit: "undisclosed employee count; ~500M+ registered users at IPO",
    revenueAtExit: "undisclosed exact figure at IPO; grew from ~$2.4B private valuation in 2020",
    bestKnownFor:
      "Gamification and habit-loop product marketing (streaks, leaderboards, the viral \"unhinged owl\" social-media persona) driving organic growth with near-zero paid acquisition",
    disciplines: ["growth", "social", "product-marketing", "analytics"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2021-07-28",
      valueLabel: "$102/share IPO price, $3.7B valuation; closed first day up 36% near $5B",
      source:
        "https://www.cnbc.com/2021/07/28/language-learning-app-duolingo-pops-35percent-in-public-debut-on-the-nasdaq.html",
    },
    keyNumbers: [
      "IPO priced at $102/share, $3.7B valuation, raising $521M (July 28, 2021)",
      "Opened at $141.40/share, intraday valuation ~$6.5B",
      "Closed first day up ~36%, valuation near $5B",
      "Up from a ~$2.4B private valuation in 2020",
    ],
  },
  {
    id: "squarespace",
    name: "Squarespace",
    website: "https://squarespace.com",
    industry: "Website builder / SMB SaaS platform",
    sector: "SaaS",
    region: "global",
    hq: "New York, USA",
    founded: 2003,
    sizeAtExit: "undisclosed employee count; 4M+ subscriptions at take-private close",
    revenueAtExit: "undisclosed exact figure; publicly reported ~$1B+ run-rate revenue in 2023",
    bestKnownFor:
      "Category-defining Super Bowl brand advertising (annual Super Bowl spots since 2014) that built mainstream awareness for a self-serve SMB SaaS product",
    disciplines: ["brand-strategy", "content", "pr-communications", "product-marketing"],
    exit: {
      type: "acquisition",
      scale: "mega",
      date: "2024-10-17",
      valueLabel: "$46.50/share cash, ~$7.2B enterprise value (raised from initial $44/share, $6.9B offer)",
      acquirer: "Permira",
      source: "https://www.squarespace.com/press-releases/2024/10/17/permira-completes-acquisition-of-squarespace",
    },
    keyNumbers: [
      "Deal announced May 13, 2024 at $44/share, $6.9B enterprise value",
      "Bid raised to $46.50/share in Sept 2024 after shareholder pushback",
      "Deal closed Oct 17, 2024 at ~$7.2B enterprise value",
      "Was previously a 2021 direct listing before this 2024 take-private",
    ],
  },
  {
    id: "nubank",
    name: "Nubank (Nu Holdings)",
    website: "https://nubank.com.br",
    industry: "Digital banking / neobank",
    sector: "Fintech",
    region: "global",
    hq: "São Paulo, Brazil",
    founded: 2013,
    sizeAtExit: "48.1M customers (Q3 2021, per IPO prospectus)",
    revenueAtExit: "undisclosed exact FY2021 revenue in search results; scale confirmed via 48.1M customer base",
    bestKnownFor:
      "Purple minimalist brand identity and a fee-free, anti-incumbent-bank positioning that turned Brazil's famously high banking fees into a word-of-mouth growth engine",
    disciplines: ["growth", "brand-strategy", "social", "product-marketing"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2021-12-09",
      valueLabel: "$9.00/share IPO price; $45B market cap after +15% day-1 pop ($41-50B range reported); $2.6B raised",
      source: "https://www.cnbc.com/2021/12/09/buffett-backed-nubank-rises-in-trading-on-the-nyse-in-blockbuster-ipo.html",
    },
    keyNumbers: [
      "48.1M customers at time of IPO filing (Q3 2021)",
      "$2.6B raised on NYSE debut Dec 9, 2021",
      "Shares priced $9.00, rose 15% on day one to a $45B valuation",
      "Warren Buffett's Berkshire Hathaway was a pre-IPO investor",
    ],
  },
  {
    id: "grab",
    name: "Grab Holdings",
    website: "https://www.grab.com",
    industry: "Ride-hailing, food delivery and fintech superapp",
    sector: "Logistics",
    region: "global",
    hq: "Singapore",
    founded: 2012,
    sizeAtExit: "187M+ users across 350+ cities in 8 Southeast Asian countries",
    revenueAtExit: "undisclosed net revenue; $11.5B GMV through Q3 2021, $12.5B full-year GMV in 2020",
    bestKnownFor:
      "Building a single 'everyday superapp' (rides + food + payments) through hyperlocal, city-by-city launch marketing across Southeast Asia's fragmented markets",
    disciplines: ["growth", "brand-strategy", "paid-ads", "product-marketing"],
    exit: {
      type: "spac",
      scale: "mega",
      date: "2021-12-01",
      valueLabel:
        "$39.6B pro forma valuation; $4.5B gross proceeds — largest SPAC merger and largest-ever US listing by a Southeast Asian company",
      acquirer: "Altimeter Growth Corp (SPAC merger, Nasdaq debut Dec 2, 2021 under GRAB)",
      source: "https://technode.global/2021/12/01/grab-to-debut-on-nasdaq-after-investors-approve-spac-merger/",
    },
    keyNumbers: [
      "$39.6B pro forma valuation, world's largest SPAC merger at the time",
      "$4.5B gross proceeds raised",
      "187M+ users across 8 countries, 350+ cities",
      "$11.5B GMV through the first nine months of 2021",
    ],
  },
  {
    id: "goto-gojek-tokopedia",
    name: "GoTo (Gojek + Tokopedia)",
    website: "https://www.gotocompany.com",
    industry: "Ride-hailing, ecommerce and fintech ecosystem",
    sector: "Ecommerce",
    region: "global",
    hq: "Jakarta, Indonesia",
    founded: 2021,
    sizeAtExit: "100M combined active users, 14M merchants, 2.5M drivers",
    revenueAtExit: "undisclosed net revenue; IDR 414.2T (~$28.8B) GTV in 2021",
    bestKnownFor:
      "Merging a super-app (Gojek: rides, delivery) with Indonesia's largest ecommerce marketplace (Tokopedia) into one ecosystem, then cross-selling a shared fintech wallet (GoPay) across both user bases",
    disciplines: ["brand-strategy", "product-marketing", "growth", "pr-communications"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2022-04-11",
      valueLabel:
        "IDR 400.3T (~$28B) market cap; $1.1B raised — third-largest Asia IPO and fifth-largest global IPO of 2022",
      source:
        "https://www.businesswire.com/news/home/20220410005062/en/GoTo-Completes-Landmark-Listing-on-the-Indonesia-Stock-Exchange",
    },
    keyNumbers: [
      "100M combined active users across Gojek and Tokopedia",
      "14M merchants, 2.5M drivers on the platform",
      "$1.1B raised; ~$28-32B market cap on debut",
      "~300,000 retail investors participated, a record for the Indonesia Stock Exchange",
    ],
  },
  {
    id: "adyen",
    name: "Adyen",
    website: "https://www.adyen.com",
    industry: "Global payments platform for enterprise merchants",
    sector: "Fintech",
    region: "global",
    hq: "Amsterdam, Netherlands",
    founded: 2006,
    sizeAtExit: "undisclosed headcount; €159B cumulative processed volume by end of 2018",
    revenueAtExit: "$255M net revenue FY2017 (+38% YoY)",
    bestKnownFor:
      "Winning global enterprise merchants (eBay, Uber, Spotify) through a single-platform, no-legacy-tech pitch delivered via direct enterprise sales rather than paid brand marketing",
    disciplines: ["product-marketing", "content", "pr-communications", "brand-strategy"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2018-06-13",
      valueLabel: "€7.1B IPO market cap (€240/share); closed day one up ~90% at a €13.4B valuation",
      source: "https://www.cnbc.com/2018/06/13/adyen-ipo-shares-rise-on-first-day-of-trade.html",
    },
    keyNumbers: [
      "€7.1B IPO market cap, jumped to €13.4B after a ~90% first-day pop",
      "€108B processed payment volume in 2017, up 63% YoY",
      "$255M net revenue in FY2017, up 38% YoY",
      "Landed eBay as its largest Platforms client in 2018",
    ],
  },
  {
    id: "wise",
    name: "Wise (formerly TransferWise)",
    website: "https://wise.com",
    industry: "Cross-border money transfer and multi-currency accounts",
    sector: "Fintech",
    region: "global",
    hq: "London, United Kingdom",
    founded: 2011,
    sizeAtExit: "10M customers at time of listing",
    revenueAtExit: "$586M revenue (FY ending March 2021, up from $422M)",
    bestKnownFor:
      "Transparent 'true exchange rate' comparison marketing that publicly exposed hidden bank FX fees, paired with a viral customer referral program",
    disciplines: ["brand-strategy", "growth", "content", "pr-communications"],
    exit: {
      type: "direct-listing",
      scale: "mega",
      date: "2021-07-07",
      valueLabel: "£8B+ (~$11B) market value on debut — first tech direct listing on the London Stock Exchange",
      source: "https://www.cnbc.com/2021/07/07/wise-direct-listing-london.html",
    },
    keyNumbers: [
      "10M customers at the time of listing",
      "$11B (£8B+) market value on LSE debut, up from a $6-7B pre-listing estimate",
      "$586M revenue in the FY prior to listing, up 39% YoY",
      "First-ever tech company direct listing on the London Stock Exchange",
    ],
  },
  {
    id: "sea-limited",
    name: "Sea Limited (Shopee, Garena parent)",
    website: "https://www.sea.com",
    industry: "Ecommerce (Shopee), gaming (Garena) and digital financial services",
    sector: "Ecommerce",
    region: "global",
    hq: "Singapore",
    founded: 2009,
    sizeAtExit: "undisclosed employee count at IPO",
    revenueAtExit: "undisclosed at IPO (search did not surface a confirmed FY2017 figure)",
    bestKnownFor:
      "Hyper-localized ecommerce growth playbook for Shopee — gamified in-app engagement (Shopee Shake), celebrity endorsements and heavy shipping subsidies to out-market incumbents across Southeast Asia and Taiwan",
    disciplines: ["growth", "paid-ads", "social", "affiliate-marketing"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2017-10-20",
      valueLabel: "$4.9B market cap at IPO ($15/share); $884M raised",
      source: "https://www.cnbc.com/2017/10/20/sea-se-ipo-stock-starts-trading-on-nyse.html",
    },
    keyNumbers: [
      "$4.9B market cap at IPO pricing of $15/share",
      "$884M raised on NYSE debut",
      "Shares closed up ~8% on first day of trading",
      "Rebranded from Garena to Sea in 2017 to reflect expansion beyond gaming into ecommerce (Shopee) and fintech",
    ],
  },
  {
    id: "hellofresh",
    name: "HelloFresh",
    website: "https://www.hellofresh.com",
    industry: "Meal-kit subscription delivery",
    sector: "Foodtech",
    region: "global",
    hq: "Berlin, Germany",
    founded: 2011,
    sizeAtExit: "1.3M active customers (Q3 2017)",
    revenueAtExit: "~€1B run-rate revenue cited at IPO; US sales alone up 98% YoY to €263.4M in H1 2017",
    bestKnownFor:
      "Making meal-kit subscriptions mainstream through aggressive, always-on performance marketing (TV, direct mail, affiliate) that outspent rival Blue Apron on customer acquisition",
    disciplines: ["paid-ads", "affiliate-marketing", "growth", "cro"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2017-11-02",
      valueLabel:
        "€10.25/share pricing, just under €1.7B valuation (below a €2B private-market target); ~€277-318M raised",
      source: "https://www.bloomberg.com/news/articles/2017-10-22/hellofresh-aims-for-1-8-billion-ipo-valuation-amid-food-wars",
    },
    keyNumbers: [
      "1.3M active customers at Q3 2017",
      "€1.7B IPO valuation, below the €2B private-market target",
      "US segment sales up 98% YoY to €263.4M in H1 2017",
      "~€277-318M raised on the Frankfurt Stock Exchange",
    ],
  },
  {
    id: "stoneco",
    name: "StoneCo",
    website: "https://www.stone.com.br",
    industry: "Merchant payments and financial technology for SMBs",
    sector: "Fintech",
    region: "global",
    hq: "São Paulo, Brazil",
    founded: 2012,
    sizeAtExit: "200,000+ merchant clients pre-IPO",
    revenueAtExit: "Revenue doubled 2017-to-2018 per company reporting; undisclosed exact FY2018 total in search results",
    bestKnownFor:
      "A high-touch, boots-on-the-ground local sales force ('hubs') that won small-merchant payments accounts away from entrenched incumbents Cielo and Rede, rather than competing on national brand advertising",
    disciplines: ["growth", "pr-communications", "brand-strategy", "product-marketing"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2018-10-25",
      valueLabel:
        "$24.00/share IPO price; ~$6.1B valuation at midpoint pricing, topped $9.9B after a 31% first-day pop; $1.22-1.5B raised",
      source:
        "https://www.globenewswire.com/news-release/2018/10/25/1626782/0/en/StoneCo-Ltd-Announces-Pricing-of-Initial-Public-Offering.html",
    },
    keyNumbers: [
      "200,000+ merchant clients across Brazil pre-IPO",
      "$1.22-1.5B raised on Nasdaq debut",
      "Valuation topped $9.9B after a 31% first-day stock pop",
      "Warren Buffett's Berkshire Hathaway took an 11.3% stake; Ant Financial invested $100M concurrently",
    ],
  },
  {
    id: "zillow",
    name: "Zillow",
    website: "https://www.zillow.com",
    industry: "Online real estate marketplace / home value estimates",
    sector: "Ecommerce",
    region: "global",
    hq: "Seattle, USA",
    founded: 2006,
    sizeAtExit: "undisclosed employee count; ~950 -1000 estimated at IPO",
    revenueAtExit: "$30.5M revenue (FY2010, year before IPO, +74% YoY)",
    bestKnownFor:
      "The Zestimate, a free automated home-value tool that turned home browsing into a habitual, sharable product and made Zillow a household verb",
    disciplines: ["seo", "content", "product-marketing", "brand-strategy"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2011-07-20",
      valueLabel: "~$950M market cap at IPO close ($20/share priced, closed at $35.77)",
      source: "https://zillow.mediaroom.com/2011-07-19-Zillow-Announces-Pricing-of-Initial-Public-Offering",
    },
    keyNumbers: [
      "$30.5M revenue in FY2010 (+74% YoY)",
      "IPO priced at $20/share, closed first day at $35.77 (+79%)",
      "~$950M market cap at IPO close",
    ],
  },
  {
    id: "yelp",
    name: "Yelp",
    website: "https://www.yelp.com",
    industry: "Local business reviews & discovery platform",
    sector: "Media",
    region: "global",
    hq: "San Francisco, USA",
    founded: 2004,
    sizeAtExit: "66M monthly unique visitors, 5.7M monthly mobile users (Q4 2011)",
    revenueAtExit: "$83.3M revenue (FY2011)",
    bestKnownFor:
      "Building an organic, review-driven local-discovery flywheel via the 'Yelp Elite Squad' ambassador program that turned power users into free content and word-of-mouth marketing",
    disciplines: ["content", "seo", "pr-communications", "growth"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2012-03-02",
      valueLabel: "$1.47B valuation at IPO close",
      source: "https://techcrunch.com/2012/03/02/yelp-closes-5-star-ipo-day-with-1-47-billion-valuation/",
    },
    keyNumbers: [
      "Priced at $15/share, closed first day at $24.58 (+63%)",
      "$83.3M revenue in FY2011",
      "66M monthly unique visitors pre-IPO",
      "$1.47B valuation at IPO close",
    ],
  },
  {
    id: "snowflake",
    name: "Snowflake",
    website: "https://www.snowflake.com",
    industry: "Cloud data warehousing / Data Cloud platform",
    sector: "SaaS",
    region: "global",
    hq: "San Mateo, USA",
    founded: 2012,
    sizeAtExit: "Customers incl. Capital One, Sony, Adobe, McKesson; 41% of customers had >$1M product revenue in FY2020",
    revenueAtExit: "$264.7M revenue (FY2020, ended Jan 31 2020)",
    bestKnownFor:
      "Category-defining 'Data Cloud' positioning and enterprise land-and-expand ABM that made it the largest software IPO in history",
    disciplines: ["product-marketing", "brand-strategy", "content", "analytics"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2020-09-16",
      valueLabel: "$33.2B valuation at $120/share IPO price, ~$68B implied after first-day pop",
      source: "https://www.cnbc.com/2020/09/16/snowflake-snow-opening-trading-on-the-nyse.html",
    },
    keyNumbers: [
      "$264.7M revenue in FY2020",
      "Raised $3.4B, largest software IPO ever at the time",
      "Stock closed +112% on first trading day",
      "Backed by a direct Berkshire Hathaway investment at IPO",
    ],
  },
  {
    id: "robinhood",
    name: "Robinhood",
    website: "https://robinhood.com",
    industry: "Commission-free stock & crypto trading app",
    sector: "Fintech",
    region: "global",
    hq: "Menlo Park, USA",
    founded: 2013,
    sizeAtExit: "18M funded accounts (Q1 2021), up from 500K in 2015",
    revenueAtExit: "$959M revenue (FY2020, +245% YoY)",
    bestKnownFor:
      "Viral 'free stock' referral waitlist and gamified, confetti-driven UX that made retail investing feel like a consumer app rather than a brokerage",
    disciplines: ["growth", "product-marketing", "social", "email"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2021-07-29",
      valueLabel: "$32B valuation, priced at $38/share",
      source:
        "https://www.cnbc.com/2021/07/28/robinhood-valued-at-32-billion-after-selling-shares-in-ipo-at-38-per-share-source-says.html",
    },
    keyNumbers: [
      "18M funded accounts as of Q1 2021",
      "$959M FY2020 revenue (+245% YoY)",
      "Grew from 500K funded accounts (2015) to 18M (2021)",
      "~$1.89B net proceeds raised in IPO",
    ],
  },
  {
    id: "coinbase",
    name: "Coinbase",
    website: "https://www.coinbase.com",
    industry: "Cryptocurrency exchange platform",
    sector: "Fintech",
    region: "global",
    hq: "San Francisco, USA",
    founded: 2012,
    sizeAtExit: "43M verified users, 2.8M monthly transacting users (end of 2020)",
    revenueAtExit: "$1.2B+ revenue, $322M profit (FY2020)",
    bestKnownFor:
      "Going public via a direct listing (skipping a traditional roadshow), a landmark PR and legitimacy event for the entire crypto industry",
    disciplines: ["pr-communications", "brand-strategy", "content", "growth"],
    exit: {
      type: "direct-listing",
      scale: "mega",
      date: "2021-04-14",
      valueLabel: "$65.3B reference valuation at $250/share; closed day one near $85.8B fully diluted",
      source:
        "https://www.coindesk.com/markets/2021/04/14/coinbase-direct-listing-gets-100b-valuation-as-share-price-jumps-in-nasdaq-debut/",
    },
    keyNumbers: [
      "43M verified users at end of 2020",
      "$1.2B+ revenue / $322M profit in FY2020",
      "Closed first day at $328.28, ~$85.8B fully diluted valuation",
      "Most valuable company to complete a direct listing at the time",
    ],
  },
  {
    id: "rent-the-runway",
    name: "Rent the Runway",
    website: "https://www.renttherunway.com",
    industry: "Fashion rental subscription ecommerce",
    sector: "D2C",
    region: "global",
    hq: "New York, USA",
    founded: 2009,
    sizeAtExit: "54,797 active subscribers (2020, pandemic-depressed); 2.5M+ customers served cumulatively as of July 2021",
    revenueAtExit: "$80.2M revenue (6 months ended July 31, 2021)",
    bestKnownFor: "Pioneering the 'closet in the cloud' subscription rental model that created the fashion-rental category itself",
    disciplines: ["growth", "email", "brand-strategy", "content"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2021-10-27",
      valueLabel: "$1.7B+ fully diluted valuation at IPO close ($21/share, top of upsized range)",
      source: "https://www.cnbc.com/2021/10/27/rent-the-runway-ipo-rent-to-start-trading-on-nasdaq-.html",
    },
    keyNumbers: [
      "Priced at $21/share, top of upsized range",
      "Raised $357M in IPO",
      "54,797 active subscribers in 2020 (pandemic low)",
      "Over 2.5M customers served cumulatively pre-IPO",
    ],
  },
  {
    id: "thredup",
    name: "ThredUp",
    website: "https://www.thredup.com",
    industry: "Online secondhand/resale apparel marketplace",
    sector: "D2C",
    region: "global",
    hq: "Oakland, USA",
    founded: 2009,
    sizeAtExit: "1.24M active buyers (Dec 31, 2020)",
    revenueAtExit: "$186M revenue (FY2020, +14% YoY)",
    bestKnownFor:
      "Creating the online resale category and marketing secondhand fashion as sustainable, mainstream shopping rather than niche thrifting",
    disciplines: ["content", "brand-strategy", "seo", "social"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2021-03-26",
      valueLabel: "$1.3B valuation, priced at $14/share",
      source: "https://www.bloomberg.com/news/articles/2021-03-25/secondhand-clothing-site-thredup-raises-168-million-in-ipo",
    },
    keyNumbers: [
      "1.24M active buyers at end of 2020",
      "$186M FY2020 revenue (+14% YoY)",
      "Priced at $14/share (top of range); debuted +30% at $18.25",
      "Raised $168M in IPO",
    ],
  },
  {
    id: "beyond-meat",
    name: "Beyond Meat",
    website: "https://www.beyondmeat.com",
    industry: "Plant-based meat alternative CPG brand",
    sector: "Foodtech",
    region: "global",
    hq: "El Segundo, USA",
    founded: 2009,
    sizeAtExit: "undisclosed employee count; $87.9M FY2018 revenue base",
    revenueAtExit: "$87.9M revenue (FY2018, +170% YoY)",
    bestKnownFor:
      "Positioning plant-based meat in the grocery meat case instead of the vegan aisle, backed by celebrity-investor PR (Leonardo DiCaprio, Bill Gates) as the first plant-based meat IPO",
    disciplines: ["pr-communications", "brand-strategy", "product-marketing"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2019-05-02",
      valueLabel: "$1.46B valuation at $25/share IPO price, ~$3.8B market cap at first-day close",
      source: "https://www.cnbc.com/2019/05/02/beyond-meat-ipo.html",
    },
    keyNumbers: [
      "$87.9M FY2018 revenue (+170% YoY)",
      "Priced at $25/share, closed first day at $65.75 (+163%)",
      "IPO 30x oversubscribed",
      "Raised $241M in IPO",
    ],
  },

  // ---------------------------------------------------------------------
  // India
  // ---------------------------------------------------------------------
  {
    id: "flipkart",
    name: "Flipkart",
    website: "https://www.flipkart.com",
    industry: "Horizontal ecommerce marketplace",
    sector: "Ecommerce",
    region: "india",
    hq: "Bengaluru, India",
    founded: 2007,
    sizeAtExit: "~54M active users, 100,000+ sellers, 261M units sold (FY17, pre-deal)",
    revenueAtExit: "$8.1B (2018)",
    bestKnownFor: "Pioneering India's annual ecommerce flash-sale calendar with 'Big Billion Days'",
    disciplines: ["growth", "paid-ads", "cro", "brand-strategy"],
    exit: {
      type: "acquisition",
      scale: "mega",
      date: "2018-05-09",
      valueLabel:
        "₹1,07,680 Cr (~$16B cash, May 2018) for 77% stake; implied full valuation ~₹1,39,984 Cr (~$20.8B)",
      acquirer: "Walmart Inc.",
      source: "https://www.bloomberg.com/news/articles/2018-05-09/walmart-to-buy-77-percent-of-india-s-flipkart-for-16-billion",
    },
    keyNumbers: [
      "77% stake acquired for $16B cash, implying ~$20.8B valuation",
      "54M active users, 100,000+ sellers pre-deal (FY17)",
      "$8.1B revenue (2018)",
    ],
  },
  {
    id: "zomato",
    name: "Zomato",
    website: "https://www.zomato.com",
    industry: "Food delivery & restaurant discovery platform",
    sector: "Foodtech",
    region: "india",
    hq: "Gurugram, India",
    founded: 2008,
    sizeAtExit: "32.1M average monthly active users, ~389,932 active restaurant listings (FY21)",
    revenueAtExit: "₹1,994 Cr (~$267M, FY21)",
    bestKnownFor:
      "Viral witty push-notification and social-media copywriting (e.g. the 'Akansha is on leave' notification) that turned brand voice into an organic growth engine",
    disciplines: ["copywriting", "social", "brand-strategy", "content"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2021-07-23",
      valueLabel: "₹1,00,000 Cr market cap (~$13.4B) crossed on listing day, Jul 23 2021",
      source: "https://kr-asia.com/zomato-makes-steller-debut-on-bourses-market-cap-hits-inr-1-trillion",
    },
    keyNumbers: [
      "Listed at ~53% premium to ₹76 issue price",
      "Market cap crossed ₹1 lakh crore (~$13.4B) on debut",
      "32.1M average MAU in FY21",
      "IPO oversubscribed 35x",
    ],
  },
  {
    id: "nykaa",
    name: "Nykaa (FSN E-Commerce Ventures)",
    website: "https://www.nykaa.com",
    industry: "Beauty & fashion ecommerce (D2C + marketplace)",
    sector: "D2C",
    region: "india",
    hq: "Mumbai, India",
    founded: 2012,
    sizeAtExit: "100+ physical stores, 1,200+ brands, 100,000+ products at IPO (Oct 2021)",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "Content-first, founder-led beauty influencer and creator marketing (tutorials, long-term creator partnerships, celebrity co-created brands like Kay Beauty) building a media-plus-commerce flywheel",
    disciplines: ["social", "content", "brand-strategy", "affiliate-marketing"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2021-11-10",
      valueLabel: "₹1,04,000 Cr market cap (~$14B) crossed on listing day, Nov 10 2021",
      source:
        "https://www.businesstoday.in/markets/company-stock/story/nykaa-crosses-rs-1-lakh-crore-market-cap-on-listing-day-311753-2021-11-10",
    },
    keyNumbers: [
      "Market cap crossed ₹1 lakh crore (~$14B) on debut day",
      "Shares surged up to ~89% intraday vs ₹1,125 issue price",
      "100+ stores, 1,200+ brands, 100,000+ products at IPO",
    ],
  },
  {
    id: "policybazaar",
    name: "PolicyBazaar (PB Fintech)",
    website: "https://www.policybazaar.com",
    industry: "Online insurance & lending comparison marketplace",
    sector: "Fintech",
    region: "india",
    hq: "Gurugram, India",
    founded: 2008,
    sizeAtExit: "undisclosed",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "SEO- and comparison-content-driven customer acquisition that made 'PolicyBazaar' synonymous with buying insurance online in India",
    disciplines: ["seo", "content", "paid-ads", "cro"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2021-11-15",
      valueLabel: "~₹51,300 Cr market cap (~$6.9B) at listing, Nov 15 2021",
      source:
        "https://www.business-standard.com/amp/article/markets/policybazaar-gains-23-on-debut-sigachi-soars-3-7x-121111501284_1.html",
    },
    keyNumbers: [
      "Raised ₹5,625 Cr (~$700M) via IPO",
      "Shares up 23% on debut day, later up 43% vs ₹980 issue price",
      "IPO subscribed 16.6x",
    ],
  },
  {
    id: "freshworks",
    name: "Freshworks",
    website: "https://www.freshworks.com",
    industry: "Customer engagement / helpdesk & CRM SaaS",
    sector: "SaaS",
    region: "india",
    hq: "San Mateo, California, USA (founded in Chennai, India, 2010)",
    founded: 2010,
    sizeAtExit: "50,000+ paying customers across 120+ countries; 11,570 customers >$5,000 ARR (Dec 2020)",
    revenueAtExit: "$249.7M revenue (2020); $300M ARR pre-IPO, +40% YoY",
    bestKnownFor:
      "Positioning as the affordable, easy-to-adopt 'anti-Salesforce' for SMBs via product-led growth and a freemium-to-paid content funnel",
    disciplines: ["product-marketing", "content", "growth", "paid-ads"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2021-09-22",
      valueLabel: "$10.13B valuation at NASDAQ debut, Sep 22 2021 (raised $1.03B)",
      source: "https://www.pymnts.com/news/ipo/2021/freshworks-valued-at-10b-in-nasdaq-trading-debut/",
    },
    keyNumbers: [
      "$10.13B valuation on Nasdaq debut",
      "$249.7M revenue in 2020, ARR grew 40% YoY to $300M",
      "50,000+ paying customers in 10 years of operation",
      "First India-founded SaaS company listed on Nasdaq",
    ],
  },
  {
    id: "delhivery",
    name: "Delhivery",
    website: "https://www.delhivery.com",
    industry: "Third-party logistics & ecommerce fulfillment",
    sector: "Logistics",
    region: "india",
    hq: "Gurugram, India",
    founded: 2011,
    sizeAtExit: "17,488 pin codes served, 23,113 customers, 1.2B+ cumulative orders delivered (FY22 DRHP)",
    revenueAtExit: "₹3,647 Cr revenue (FY21); ₹4,911 Cr total income through Dec 2021",
    bestKnownFor:
      "B2B trust-and-scale positioning — marketing its pan-India logistics network and tech infrastructure directly to ecommerce/D2C brands rather than end consumers",
    disciplines: ["product-marketing", "content", "analytics", "pr-communications"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2022-05-24",
      valueLabel: "₹35,877 Cr market cap (~$4.6B) on listing day, May 24 2022",
      source:
        "https://www.businesstoday.in/markets/company-stock/story/delhivery-stock-makes-flat-market-debut-premium-to-issue-price-334800-2022-05-24",
    },
    keyNumbers: [
      "Raised ₹5,235 Cr via IPO",
      "22% ecommerce parcel market share",
      "Revenue CAGR ~48% FY19-FY21",
      "17,488 pin codes covered in logistics network",
    ],
  },
  {
    id: "honasa-mamaearth",
    name: "Honasa Consumer (Mamaearth)",
    website: "https://www.mamaearth.in",
    industry: "D2C beauty & personal care (toxin-free FMCG)",
    sector: "D2C",
    region: "india",
    hq: "Gurugram, India",
    founded: 2016,
    sizeAtExit: "undisclosed employee count; multi-brand portfolio (Mamaearth, The Derma Co, Aqualogica, BBlunt, etc.) at IPO",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "Building India's first D2C-beauty unicorn almost entirely through influencer/mom-blogger marketing (500+ influencers) rather than celebrity TV ads, with ~90% of marketing spend digital",
    disciplines: ["social", "content", "brand-strategy", "growth"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2023-11-07",
      valueLabel: "₹10,846 Cr market cap at listing (~$1.3B, Nov 2023); ₹1,701.44 Cr issue size",
      source: "https://www.chittorgarh.com/ipo/mamaearth-ipo/1551/",
    },
    keyNumbers: [
      "₹1,701.44 Cr IPO issue size",
      "₹324/share listing price",
      "~₹10,846 Cr market cap at listing (~$1.3B)",
      "500+ influencer/mom-blogger partnerships cited as core growth channel",
    ],
  },
  {
    id: "swiggy",
    name: "Swiggy",
    website: "https://www.swiggy.com",
    industry: "Food delivery & quick commerce (Instamart)",
    sector: "Foodtech",
    region: "india",
    hq: "Bengaluru, India",
    founded: 2014,
    sizeAtExit: "~17,000+ employees (Feb 2025); #2 food delivery platform in India",
    revenueAtExit: "₹11,634.4 Cr FY24 (~$1.4B)",
    bestKnownFor:
      "Hyperlocal on-demand delivery growth engine plus quirky, meme-friendly brand voice on social/OOH; credited with creating and scaling India's quick-commerce category via Instamart",
    disciplines: ["growth", "social", "brand-strategy", "paid-ads"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2024-11-13",
      valueLabel: "₹11,327.43 Cr issue size at ~$11.3B valuation (~₹95,000 Cr, Nov 2024)",
      source:
        "https://www.business-standard.com/markets/ipo/swiggy-seeks-valuation-of-11-3-billion-ipo-to-open-on-wednesday-124110500677_1.html",
    },
    keyNumbers: [
      "$11.3B IPO valuation (~₹95,000 Cr)",
      "₹11,327.43 Cr issue size",
      "₹11,634.4 Cr FY24 revenue",
      "~17,000+ employees as of Feb 2025",
    ],
  },
  {
    id: "ola-electric",
    name: "Ola Electric",
    website: "https://www.olaelectric.com",
    industry: "Electric two-wheeler manufacturing & D2C retail",
    sector: "EV/Automotive",
    region: "india",
    hq: "Bengaluru, India",
    founded: 2017,
    sizeAtExit: "undisclosed employee count; India's top-selling electric two-wheeler brand by volume (FY24)",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "Founder-led, direct-to-consumer EV marketing that bypassed traditional dealerships entirely, building India's first D2C-only two-wheeler distribution and experience-center model",
    disciplines: ["brand-strategy", "growth", "pr-communications", "social"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2024-08",
      valueLabel: "₹6,145.56 Cr issue size at ~$4.0-4.5B valuation (~₹33,000-37,500 Cr, Aug 2024)",
      source: "https://www.chittorgarh.com/ipo/ola-electric-ipo/1765/",
    },
    keyNumbers: [
      "₹6,145.56 Cr IPO issue size",
      "~$4.0B post-IPO valuation, down 26% from $5.4B last private round",
      "4.27x overall IPO subscription",
      "₹72-76/share price band",
    ],
  },
  {
    id: "firstcry-brainbees",
    name: "FirstCry (Brainbees Solutions)",
    website: "https://www.firstcry.com",
    industry: "Omnichannel baby, kids & maternity products retail",
    sector: "Ecommerce",
    region: "india",
    hq: "Pune, India",
    founded: 2010,
    sizeAtExit: "6,000+ employees (FY24)",
    revenueAtExit: "₹6,481 Cr FY24 (~$770M)",
    bestKnownFor:
      "Building a trust-led omnichannel parenting/baby-care brand that fused ecommerce scale with an offline franchise network, becoming India's default parenting content-plus-commerce destination",
    disciplines: ["content", "cro", "growth", "brand-strategy"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2024-08-13",
      valueLabel: "₹4,193.73 Cr issue size; ₹24,142 Cr market cap (~$2.9B, Aug 2024)",
      source: "https://www.chittorgarh.com/ipo/brainbees-solutions-firstcry-ipo/1801/",
    },
    keyNumbers: [
      "₹6,481 Cr FY24 revenue (~$770M)",
      "₹24,142 Cr market cap at IPO (~$2.9B)",
      "₹4,193.73 Cr issue size",
      "SoftBank (SVF Frog) held 25.55% pre-IPO, Mahindra & Mahindra 10.98%",
    ],
  },
  {
    id: "lenskart",
    name: "Lenskart",
    website: "https://www.lenskart.com",
    industry: "Omnichannel eyewear retail (D2C + stores)",
    sector: "D2C",
    region: "india",
    hq: "Faridabad, India",
    founded: 2010,
    sizeAtExit: "1,100+ stores across India; ~$350M revenue (FY24)",
    revenueAtExit: "~$350M (FY2024)",
    bestKnownFor:
      "Pivoting from pure-online to a data-driven omnichannel retail model after recognizing ~90% of Indian eyewear purchases happen offline, paired with virtual try-on tech and celebrity-led brand campaigns",
    disciplines: ["cro", "brand-strategy", "growth", "content"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2025-11-10",
      valueLabel: "₹7,278.02 Cr issue size at ~$8B valuation (~₹70,000 Cr, Nov 2025)",
      source:
        "https://www.business-standard.com/markets/ipo/lenskart-eyes-8-billion-valuation-as-it-plans-fifth-largest-ipo-of-2025-125102701160_1.html",
    },
    keyNumbers: [
      "$8B IPO valuation (~₹70,000 Cr)",
      "₹7,278.02 Cr issue size",
      "28.26x overall IPO subscription",
      "1,100+ stores across India",
    ],
  },

  // ---------------------------------------------------------------------
  // Gap-fill: mid/small-scale exits + additional India companies
  // ---------------------------------------------------------------------

  // --- Global, mid/small/large gap-fill ---
  {
    id: "native-deodorant",
    name: "Native",
    website: "https://www.nativecos.com",
    industry: "Natural Deodorant & Personal Care",
    sector: "Beauty",
    region: "global",
    hq: "San Francisco, CA, USA",
    founded: 2015,
    sizeAtExit: "$100M acquisition price",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "Scrappy founder-led Facebook/Instagram direct-response ads and transparent-ingredient positioning that took the brand from launch to a $100M exit in under 3 years on just $500K raised",
    disciplines: ["paid-ads", "growth", "brand-strategy", "copywriting"],
    exit: {
      type: "acquisition",
      scale: "mid",
      date: "2017-11-15",
      valueLabel: "$100M (cash)",
      acquirer: "Procter & Gamble",
      source:
        "https://techcrunch.com/2017/11/15/procter-gamble-just-bought-this-venture-backed-deodorant-startup-for-100-million-cash/",
    },
    keyNumbers: [
      "$100M all-cash acquisition price (Nov 2017)",
      "Reached acquisition just 2.5 years after launch",
      "Raised only $500K in outside funding pre-exit",
      "Over 1 million customers at time of sale",
    ],
  },
  {
    id: "trunk-club",
    name: "Trunk Club",
    website: "https://www.trunkclub.com",
    industry: "Personalized Menswear Styling",
    sector: "D2C",
    region: "global",
    hq: "Chicago, IL, USA",
    founded: 2009,
    sizeAtExit: "$350M acquisition (Nordstrom stock)",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "Human-stylist-plus-curated-box model that pioneered 'styling as a service' as a customer acquisition and retention loop, later shut down by its acquirer in 2019 as a lesson in post-acquisition integration risk",
    disciplines: ["growth", "email", "brand-strategy", "cro"],
    exit: {
      type: "acquisition",
      scale: "large",
      date: "2014-07-31",
      valueLabel: "$350M in Nordstrom stock, plus up to $100M in management incentives",
      acquirer: "Nordstrom",
      source: "https://www.chicagobusiness.com/article/20140814/NEWS07/140819906/nordstrom-s-trunk-club-purchase-price-350-million",
    },
    keyNumbers: [
      "$350M acquisition price in Nordstrom stock",
      "Up to $100M in additional management incentive payments",
      "Nordstrom shut the brand down in 2019, five years post-acquisition",
    ],
  },
  {
    id: "modcloth",
    name: "ModCloth",
    website: "https://www.modcloth.com",
    industry: "Indie & Vintage-Inspired Fashion Ecommerce",
    sector: "Ecommerce",
    region: "global",
    hq: "Los Angeles, CA (originally Pittsburgh, PA), USA",
    founded: 2002,
    sizeAtExit: "undisclosed (analysts estimated $50M-75M)",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "The 'Be The Buyer' program that crowdsourced merchandising decisions from its community, turning customer votes into both product selection and viral user-generated content",
    disciplines: ["social", "content", "brand-strategy", "cro"],
    exit: {
      type: "acquisition",
      scale: "small",
      date: "2017-03-16",
      valueLabel: "undisclosed (analysts estimated $50M-75M)",
      acquirer: "Walmart (via Jet.com)",
      source: "https://techcrunch.com/2017/03/16/walmart-subsidiary-jet-com-to-buy-modcloth-for-less-than-75m/",
    },
    keyNumbers: [
      "Deal price never officially disclosed; analysts estimated $50M-75M",
      "Sold again in 2019 to Go Global Retail after becoming unprofitable under Walmart",
      "Changed hands a third time to ecommerce platform Nogin",
    ],
  },
  {
    id: "birchbox",
    name: "Birchbox",
    website: "https://www.birchbox.com",
    industry: "Beauty Sample Subscription Box",
    sector: "Beauty",
    region: "global",
    hq: "New York, NY, USA",
    founded: 2010,
    sizeAtExit: "~$45M acquisition",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "Created the monthly beauty-sample 'discovery box' subscription format, turning try-before-you-buy sampling into a repeatable acquisition and email-nurture funnel that spawned an entire subscription-commerce category",
    disciplines: ["email", "content", "growth", "brand-strategy"],
    exit: {
      type: "acquisition",
      scale: "mid",
      date: "2021-10-01",
      valueLabel: "~$45M",
      acquirer: "FemTec Health",
      source: "https://www.retaildive.com/news/birchbox-customer-complaints-website-down-vendor-debts/643963/",
    },
    keyNumbers: [
      "~$45M acquisition price (Oct 2021)",
      "Category-defining launch in 2010, years before Ipsy/BoxyCharm followed",
      "Assets changed hands again in 2023 to Retention Brands after FemTec Health struggled to pay vendors",
    ],
  },
  {
    id: "mvmt-watches",
    name: "MVMT",
    website: "https://www.mvmt.com",
    industry: "Direct-to-Consumer Fashion Watches & Accessories",
    sector: "D2C",
    region: "global",
    hq: "Santa Monica, CA, USA",
    founded: 2013,
    sizeAtExit: "$100M initial payment, up to $200M total with earnouts",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "Instagram micro-influencer seeding at massive scale, paired with a 2013 Indiegogo crowdfunding launch, that built brand awareness almost entirely through paid and organic social before any traditional retail presence",
    disciplines: ["social", "paid-ads", "affiliate-marketing", "brand-strategy"],
    exit: {
      type: "acquisition",
      scale: "large",
      date: "2018-10-01",
      valueLabel: "$100M upfront, plus up to $100M in earnouts (up to $200M total)",
      acquirer: "Movado Group",
      source: "https://www.jckonline.com/editorial-article/movado-pays-100-million-for-mvmt/",
    },
    keyNumbers: [
      "$100M initial payment plus up to $100M in performance earnouts",
      "Launched via Indiegogo crowdfunding campaign in 2013",
      "Acquired just 5 years after founding",
    ],
  },
  {
    id: "halo-top",
    name: "Halo Top",
    website: "https://www.halotop.com",
    industry: "Low-Calorie Ice Cream",
    sector: "Food & Beverage",
    region: "global",
    hq: "Los Angeles, CA, USA",
    founded: 2011,
    sizeAtExit: "undisclosed",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "Flipped the ice-cream category's marketing convention by putting calorie counts front-and-center on packaging, turning a nutrition label into the core brand message and driving explosive viral/social word-of-mouth",
    disciplines: ["social", "brand-strategy", "content", "pr-communications"],
    exit: {
      type: "acquisition",
      scale: "small",
      date: "2019-09-11",
      valueLabel: "undisclosed",
      acquirer: "Wells Enterprises (Blue Bunny)",
      source: "https://www.fooddive.com/news/blue-bunny-ice-cream-maker-wells-enterprises-to-buy-halo-top/562552/",
    },
    keyNumbers: [
      "Became the best-selling pint of ice cream in US grocery by 2017",
      "Unilever reportedly offered ~$2B in Jan 2018 but the deal collapsed",
      "Acquirer Wells Enterprises was itself later bought by Ferrero in Dec 2022",
    ],
  },
  {
    id: "rxbar",
    name: "RXBAR",
    website: "https://www.rxbar.com",
    industry: "Protein & Nutrition Bars",
    sector: "Food & Beverage",
    region: "global",
    hq: "Chicago, IL, USA",
    founded: 2013,
    sizeAtExit: "$600M acquisition",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "The 'No B.S.' ingredient-first package design that lists the entire recipe (egg whites, dates, almonds) on the front of the wrapper, making the packaging itself the brand's core marketing asset",
    disciplines: ["brand-strategy", "content", "pr-communications", "growth"],
    exit: {
      type: "acquisition",
      scale: "large",
      date: "2017-10-27",
      valueLabel: "$600M ($400M net of tax benefits)",
      acquirer: "Kellogg Company",
      source: "https://www.fooddive.com/news/kellogg-broadens-snack-reach-with-600m-purchase-of-rxbar/506699/",
    },
    keyNumbers: [
      "$600M acquisition price, ~$400M net of tax benefits",
      "Started with $10,000 in founder capital",
      "Was the fastest-growing nutrition bar brand in the US at time of sale",
    ],
  },
  {
    id: "walker-and-company",
    name: "Walker & Company Brands (Bevel)",
    website: "https://www.bevel.com",
    industry: "Grooming Products for People of Color",
    sector: "Beauty",
    region: "global",
    hq: "Palo Alto, CA, USA (relocated to Atlanta, GA post-acquisition)",
    founded: 2013,
    sizeAtExit: "estimated $20M-40M (undisclosed)",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "Built an entire brand and go-to-market strategy around an underserved audience (men of color's grooming needs) that legacy CPG brands ignored, becoming the first Black-founded, venture-backed startup acquired by a Fortune 500 company",
    disciplines: ["brand-strategy", "pr-communications", "content", "social"],
    exit: {
      type: "acquisition",
      scale: "mid",
      date: "2018-12-12",
      valueLabel: "undisclosed (Recode estimated $20M-40M)",
      acquirer: "Procter & Gamble",
      source: "https://www.retaildive.com/news/pg-purchases-walker-company-a-disruptor-marketer-catering-to-consumers/544350/",
    },
    keyNumbers: [
      "Estimated $20M-40M acquisition value (unconfirmed, per Recode)",
      "First Black-founded VC-backed startup acquired by a Fortune 500 company",
      "Founder Tristan Walker remained CEO post-acquisition, relocating HQ to Atlanta",
    ],
  },
  {
    id: "blue-bottle-coffee",
    name: "Blue Bottle Coffee",
    website: "https://bluebottlecoffee.com",
    industry: "Specialty Coffee Retail & Roasting",
    sector: "Food & Beverage",
    region: "global",
    hq: "Oakland, CA, USA",
    founded: 2002,
    sizeAtExit: "$425M for 68% stake (implied valuation $700M+)",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "Minimalist branding and a deliberately slow, ritualized pour-over experience that turned specialty coffee into an aspirational lifestyle brand, a template later copied across the whole third-wave coffee category",
    disciplines: ["brand-strategy", "content", "cro", "pr-communications"],
    exit: {
      type: "acquisition",
      scale: "large",
      date: "2017-09-14",
      valueLabel: "$425M for a 68% stake (implied valuation over $700M)",
      acquirer: "Nestle",
      source: "https://techcrunch.com/2017/09/14/nestle-acquires-a-majority-stake-in-blue-bottle-coffee/",
    },
    keyNumbers: [
      "$425M for a 68% majority stake",
      "Implied company valuation north of $700M",
      "Nestle reportedly explored a resale of Blue Bottle as of late 2025",
    ],
  },
  {
    id: "drunk-elephant",
    name: "Drunk Elephant",
    website: "https://www.drunkelephant.com",
    industry: "Clean Skincare",
    sector: "Beauty",
    region: "global",
    hq: "Houston, TX, USA",
    founded: 2012,
    sizeAtExit: "$845M acquisition",
    revenueAtExit: "expected to surpass $100M in 2019",
    bestKnownFor:
      "The 'Suspicious 6' ingredient-exclusion promise (no essential oils, silicones, chemical sunscreens, etc.) that built cult loyalty almost entirely through Sephora sell-through and organic social, without a traditional ad-led launch",
    disciplines: ["brand-strategy", "social", "pr-communications", "cro"],
    exit: {
      type: "acquisition",
      scale: "large",
      date: "2019-10-07",
      valueLabel: "$845M (8.5x trailing sales)",
      acquirer: "Shiseido",
      source: "https://www.jonesday.com/en/practices/experience/2019/11/shiseido-to-acquire-drunk-elephant-for-845-million",
    },
    keyNumbers: [
      "$845M acquisition price, 8.5x trailing sales",
      "Revenue expected to pass $100M in 2019",
      "Sold almost exclusively through Sephora and its own DTC site",
    ],
  },
  {
    id: "glossybox",
    name: "Glossybox",
    website: "https://www.glossybox.com",
    industry: "Beauty Subscription Box",
    sector: "Beauty",
    region: "global",
    hq: "Berlin, Germany",
    founded: 2011,
    sizeAtExit: "undisclosed",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "A Rocket Internet-style rapid multi-country launch playbook that took the beauty subscription-box format to 10 countries within its first year, proving the model was internationally replicable",
    disciplines: ["growth", "email", "social", "brand-strategy"],
    exit: {
      type: "acquisition",
      scale: "small",
      date: "2017-08-14",
      valueLabel: "undisclosed",
      acquirer: "The Hut Group (THG)",
      source: "https://techcrunch.com/2017/08/14/rocket-internets-glossybox-acquired-by-uk-ecommerce-platform-player-thg/",
    },
    keyNumbers: [
      "Deal terms undisclosed",
      "Raised $72M from investors over its 6-year run pre-acquisition",
      "Was active in 10 international markets at time of sale",
    ],
  },
  {
    id: "winc-club-w",
    name: "Winc (formerly Club W)",
    website: "https://www.winc.com",
    industry: "Direct-to-Consumer Wine Subscription",
    sector: "Food & Beverage",
    region: "global",
    hq: "Los Angeles, CA, USA",
    founded: 2012,
    sizeAtExit: "IPO raised $22.1M gross ($17.9M net)",
    revenueAtExit: "$72.1M (reported, never profitable)",
    bestKnownFor:
      "The 'Palate Profile' quiz that personalized wine recommendations as the core acquisition funnel, later studied as a cautionary case of scaling paid customer acquisition without matching unit economics",
    disciplines: ["growth", "email", "cro", "analytics"],
    exit: {
      type: "ipo",
      scale: "small",
      date: "2021-11-10",
      valueLabel: "$22.1M gross IPO proceeds ($17.9M net) at $13.00/share on NYSE American (WBEV)",
      source: "https://www.prnewswire.com/news-releases/winc-inc-prices-22-0-million-initial-public-offering-301421870.html",
    },
    keyNumbers: [
      "IPO priced at $13.00/share, raising $22.1M gross ($17.9M net), Nov 2021",
      "Reported $72.1M in revenue but was never profitable",
      "Filed for Chapter 11 bankruptcy in Dec 2022, just over a year after its IPO",
      "Operating assets acquired by Amass Brands in early 2023",
    ],
  },
  {
    id: "casper-sleep",
    name: "Casper Sleep",
    website: "https://casper.com",
    industry: "Mattresses & Sleep Products",
    sector: "D2C",
    region: "global",
    hq: "New York City, NY, USA",
    founded: 2014,
    sizeAtExit: "~$310M going-private acquisition (94% premium to trading price, but well below its ~$1.1B 2020 IPO valuation)",
    revenueAtExit: "~$580M FY2021 net revenue (record fiscal year, per company Q3 2021 results)",
    bestKnownFor:
      "Creating the 'bed-in-a-box' DTC mattress category through whimsical NYC subway takeovers, heavy podcast advertising, and meme-able unboxing moments",
    disciplines: ["brand-strategy", "pr-communications", "content", "growth"],
    exit: {
      type: "acquisition",
      scale: "large",
      date: "2021-11-15",
      valueLabel: "$310M ($6.90/share, 94% premium to prior close)",
      acquirer: "Durational Capital Management",
      source: "https://www.cnbc.com/2021/11/15/mattress-maker-casper-to-be-taken-private-by-pe-firm-durational-capital.html",
    },
    keyNumbers: [
      "Invested over $500M in brand marketing since its 2014 founding",
      "Converted entire NYC subway cars into branded illustrated 'sleeper cars' in 2015",
      "$580M FY2021 revenue against a $310M take-private price - sold below 1x revenue",
      "Stock fell roughly 94% from its Feb 2020 IPO price to the 2022 take-private buyout",
    ],
  },
  {
    id: "peloton",
    name: "Peloton Interactive",
    website: "https://www.onepeloton.com",
    industry: "Connected Fitness Equipment",
    sector: "D2C",
    region: "global",
    hq: "New York City, NY, USA",
    founded: 2012,
    sizeAtExit: "$8.1B IPO valuation ($9.6B fully diluted) - the largest-ever IPO valuation for a New York-based startup at the time",
    revenueAtExit: "$915M FY2019 revenue (fiscal year ended June 30, 2019), up 110% year-over-year",
    bestKnownFor:
      "Building a media/community company disguised as exercise equipment - instructor personalities and live leaderboards drove retention, until the notorious 2019 'The Gift That Gives Back' holiday ad became a widely-taught PR-crisis case study",
    disciplines: ["content", "social", "brand-strategy", "pr-communications"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2019-09-26",
      valueLabel: "$8.1B IPO valuation ($29/share, raised $1.16B)",
      source: "https://www.cnbc.com/2019/09/25/peloton-prices-ipo-at-29-per-share.html",
    },
    keyNumbers: [
      "$915M FY2019 revenue at IPO, up from $435M in FY2018",
      "Connected Fitness subscribers grew from 35K (2016) to 511K (June 2019) - ~144% annualized growth",
      "2019 holiday ad backlash was blamed for a same-day ~10% stock drop and remains a standard marketing-crisis teaching example",
      "IPO raised $1.16B at a $9.6B fully-diluted valuation, then the highest ever for a NY-based startup listing",
    ],
  },
  {
    id: "framebridge",
    name: "Framebridge",
    website: "https://framebridge.com",
    industry: "Custom Picture Framing",
    sector: "D2C",
    region: "global",
    hq: "Washington, D.C., USA",
    founded: 2014,
    sizeAtExit: "Undisclosed price; Graham Holdings raised its stake to 93.4% control in a majority-acquisition deal",
    revenueAtExit: "Not publicly disclosed at the 2020 acquisition; had reached $58M revenue within its first 3 years per contemporaneous press coverage",
    bestKnownFor:
      "Turning an intimidating, opaque category (custom framing) into a simple DTC e-commerce experience with flat pricing and mail-in-your-art convenience",
    disciplines: ["brand-strategy", "cro", "product-marketing", "content"],
    exit: {
      type: "acquisition",
      scale: "small",
      date: "2020-05-15",
      valueLabel: "undisclosed (Graham Holdings increased its ownership stake to 93.4% control; deal price not publicly disclosed)",
      acquirer: "Graham Holdings Company",
      source: "https://www.businesswire.com/news/home/20200515005260/en/Graham-Holdings-Company-Acquires-Framebridge-Inc.",
    },
    keyNumbers: [
      "Grew from $0 to $58M revenue in its first three years",
      "Raised $81M+ in VC funding - the most ever for a woman-founded company in the DC area at the time",
      "Expanded to 43 physical stores and 4 factories with 750 employees by ~2019",
      "Graham Holdings took majority control (93.4%) via an additional-stake acquisition in May 2020",
    ],
  },
  {
    id: "stitch-fix",
    name: "Stitch Fix",
    website: "https://www.stitchfix.com",
    industry: "Personalized Apparel & Styling",
    sector: "D2C",
    region: "global",
    hq: "San Francisco, CA, USA",
    founded: 2011,
    sizeAtExit: "$1.5B IPO valuation ($15/share, raised $120M)",
    revenueAtExit: "$977M FY2017 revenue (fiscal year ended July 2017) with $33M net income",
    bestKnownFor:
      "Blending human stylists with a recommendation algorithm to reinvent product discovery as a personalized subscription 'Fix' box - low-paid-media, high-retention growth",
    disciplines: ["growth", "analytics", "product-marketing", "cro"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2017-11-17",
      valueLabel: "$1.5B IPO valuation ($15/share, below its $18-20 target range)",
      source: "https://www.forbes.com/sites/laurengensler/2017/11/17/stitch-fix-ipo-first-day-of-trading/",
    },
    keyNumbers: [
      "$977M FY2017 revenue with $33M net income at time of IPO",
      "Grew from $0 to $730M revenue in roughly 6 years pre-IPO",
      "Over 100 data scientists building personalization algorithms by IPO",
      "Katrina Lake became the youngest female founder to lead a company through IPO at the time",
    ],
  },
  {
    id: "blue-apron",
    name: "Blue Apron",
    website: "https://www.blueapron.com",
    industry: "Meal-Kit Delivery",
    sector: "Foodtech",
    region: "global",
    hq: "New York City, NY, USA",
    founded: 2012,
    sizeAtExit: "$103M acquisition (down from a $1.89B 2017 IPO valuation - a roughly 95% decline over six years)",
    revenueAtExit: "$458.5M FY2022 net revenue (down 2.5% from $470.4M in FY2021), the last full reported fiscal year before the sale",
    bestKnownFor:
      "Pioneering the meal-kit-subscription category and becoming the definitive cautionary tale of unsustainable customer-acquisition spend - podcast/radio ad spend jumped from $293,900 (2015) to $2.41M (2016) while CAC estimates ran $150-$400+ per customer",
    disciplines: ["paid-ads", "growth", "content", "pr-communications"],
    exit: {
      type: "acquisition",
      scale: "large",
      date: "2023-09-29",
      valueLabel: "$103M ($13.00/share, a 137% premium to prior close but far below its 2017 IPO value)",
      acquirer: "Wonder Group",
      source: "https://www.cnbc.com/2023/09/29/blue-apron-to-be-acquired-by-wonder-group-for-103-million.html",
    },
    keyNumbers: [
      "IPO'd in 2017 at a $1.89B valuation; sold six years later for $103M - a ~95% collapse",
      "Total marketing expense grew from $14M (2014) to $144M (2016) chasing growth",
      "Outspent its nearest competitor on podcast advertising by nearly 5x in 2016, co-creating a branded Gimlet Media podcast",
      "FY2022 revenue of $458.5M, down from a post-IPO peak, driven by shrinking customer/order counts",
    ],
  },
  {
    id: "yeti",
    name: "YETI Holdings",
    website: "https://www.yeti.com",
    industry: "Outdoor Gear & Coolers",
    sector: "D2C",
    region: "global",
    hq: "Austin, TX, USA",
    founded: 2006,
    sizeAtExit: "~$1.4-1.7B IPO valuation ($18/share, ~$288M raised)",
    revenueAtExit: "$778M FY2018 revenue, the fiscal year of its IPO (up from $639M in FY2017)",
    bestKnownFor:
      "Building premium brand loyalty through grassroots ambassador programs (hunters, anglers, snowboarders) and cinematic 'YETI Presents' documentary-style films instead of discounting",
    disciplines: ["brand-strategy", "content", "social", "pr-communications"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2018-10-25",
      valueLabel: "$18/share IPO pricing, ~$1.4-1.7B initial valuation",
      source: "https://sgbonline.com/yeti-valued-at-1-7-billion-in-ipo/",
    },
    keyNumbers: [
      "$778M FY2018 revenue at IPO, up from $639M FY2017",
      "DTC channel grew from 8% of revenue (2015) to 30% (2017) as the brand-loyalty strategy took hold",
      "Revenue grew from $90M (2013) to $1.83B (2024), a 33% 10-year CAGR",
      "IPO priced 16M shares at $18 on Oct 25, 2018 on NYSE under ticker YETI",
    ],
  },
  {
    id: "allbirds",
    name: "Allbirds",
    website: "https://www.allbirds.com",
    industry: "Sustainable Footwear & Apparel",
    sector: "D2C",
    region: "global",
    hq: "San Francisco, CA, USA",
    founded: 2016,
    sizeAtExit: "$39M asset sale - down roughly 99% from its $4.1B first-day IPO valuation (Nov 2021)",
    revenueAtExit: "$189.8M FY2024 revenue (down 25.3% year-over-year), its last full reported fiscal year before the sale",
    bestKnownFor:
      "Pioneering 'sustainability as the whole brand story' DTC positioning (\"the world's most comfortable shoe\") - and later becoming the definitive case study for over-relying on values-based marketing without renewing product and style relevance",
    disciplines: ["brand-strategy", "pr-communications", "content", "social"],
    exit: {
      type: "acquisition",
      scale: "mid",
      date: "2026-03-31",
      valueLabel: "$39M asset purchase (estimated transaction value)",
      acquirer: "American Exchange Group",
      source: "https://sgbonline.com/allbirds-to-be-sold-to-american-exchange-group-for-39m/",
    },
    keyNumbers: [
      "IPO priced at a $1.6B expected valuation but closed day one at ~$4.1B (Nov 2021)",
      "Revenue grew from $126M (2018) to $219.3M (2020), a 31.9% CAGR, then declined to $189.8M by 2024",
      "Sold nearly all IP and assets for just $39M in 2026 - roughly a 99% collapse from peak valuation",
      "Buyer American Exchange Group also owns/licenses Aerosoles, Ed Hardy, and Jonathan Adler",
    ],
  },

  // --- India, additional gap-fill ---
  {
    id: "ustraa",
    name: "Ustraa",
    website: "https://www.ustraa.com",
    industry: "Men's Grooming & Personal Care",
    sector: "Beauty",
    region: "india",
    hq: "Gurugram, India",
    founded: 2015,
    sizeAtExit: "~₹61 Cr deal value at acquisition",
    revenueAtExit: "undisclosed",
    bestKnownFor:
      "Building India's first mainstream men's grooming D2C brand almost entirely on category-education content (blog, YouTube, packaging copy explaining 'why' behind ingredients) rather than paid reach, in a market with near-zero existing demand for men's skincare",
    disciplines: ["content", "social", "growth", "brand-strategy"],
    exit: {
      type: "acquisition",
      scale: "small",
      date: "2023-06-09",
      valueLabel: "₹61 Cr (~$7.4M, as of Jun 2023)",
      acquirer: "VLCC Health Care",
      source: "https://www.business-standard.com/companies/news/vlcc-health-care-to-acquire-d2c-men-s-grooming-brand-ustraa-for-rs-61-crore-123060900986_1.html",
    },
    keyNumbers: [
      "Acquired by VLCC via a mix of secondary buyout and share swap, deal pegged at ~₹61 Cr",
      "Parent entity Happily Unmarried Marketing Pvt Ltd originally started in 2003 selling quirky merchandise, pivoted to the Ustraa grooming brand in 2015",
      "Founders Rahul Anand and Rajat Tuli stayed on to lead VLCC's D2C business post-acquisition",
      "One of the first Indian D2C brands to build a dedicated men's grooming category from near-zero prior demand",
    ],
  },
  {
    id: "mapmyindia",
    name: "MapmyIndia (CE Info Systems)",
    website: "https://www.mapmyindia.com",
    industry: "Digital Mapping & Geospatial Technology",
    sector: "SaaS",
    region: "india",
    hq: "New Delhi, India",
    founded: 1995,
    sizeAtExit: "₹1,039.61 Cr IPO issue size; ~₹7,420 Cr market cap on listing day",
    revenueAtExit: "~₹270 Cr FY21 revenue (per IPO prospectus-era reporting)",
    bestKnownFor:
      "Turning 'Made in India, Made for India' sovereignty and data-privacy positioning into its core marketing narrative against Google Maps, timed with government Atmanirbhar Bharat sentiment and China-app bans",
    disciplines: ["pr-communications", "brand-strategy", "product-marketing", "content"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2021-12-21",
      valueLabel: "₹1,039.61 Cr raised (~$140M); market cap ~₹7,420 Cr (~$996M) on listing, Dec 2021",
      source: "https://www.business-standard.com/article/markets/mapmyindia-plots-stellar-market-debut-as-it-lists-with-53-premium-121122101333_1.html",
    },
    keyNumbers: [
      "IPO subscribed 154.71x overall",
      "Listed at ₹1,581, a 53% premium over the ₹1,033 issue price on Dec 21, 2021",
      "Market cap of ~₹7,420 Cr on listing day",
      "Positioned as India's home-grown, self-reliant alternative to Google Maps",
    ],
  },
  {
    id: "rategain-travel-technologies",
    name: "RateGain Travel Technologies",
    website: "https://www.rategain.com",
    industry: "Travel & Hospitality SaaS (Distribution, Pricing Intelligence)",
    sector: "SaaS",
    region: "india",
    hq: "Noida, India",
    founded: 2004,
    sizeAtExit: "₹1,335.74 Cr IPO issue size; ~₹3,630 Cr market cap on listing day",
    revenueAtExit: "undisclosed at listing",
    bestKnownFor:
      "Building its enterprise SaaS pipeline through data-and-research-led thought leadership (proprietary travel demand/pricing intelligence reports) aimed at hotel and OTA decision-makers rather than broad-audience advertising",
    disciplines: ["content", "pr-communications", "product-marketing", "seo"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2021-12-17",
      valueLabel: "₹1,335.74 Cr raised (~$179M); market cap ~₹3,630 Cr (~$487M) on listing, Dec 2021",
      source: "https://www.business-standard.com/amp/article/markets/rategain-makes-weak-stock-market-debut-lists-15-below-issue-price-121121700285_1.html",
    },
    keyNumbers: [
      "IPO subscribed 17.4x, driven mainly by HNI demand",
      "Listed at ₹360, a 15% discount to the ₹425 issue price on Dec 17, 2021",
      "One of the first India-origin, globally-serving SaaS companies to go public on Indian exchanges",
      "Market cap of ~₹3,630 Cr on listing day",
    ],
  },
  {
    id: "five-star-business-finance",
    name: "Five-Star Business Finance",
    website: "https://www.fivestargroup.in",
    industry: "MSME Secured Lending (NBFC)",
    sector: "Fintech",
    region: "india",
    hq: "Chennai, India",
    founded: 1984,
    sizeAtExit: "₹1,960 Cr IPO issue size (entirely OFS); ~₹13,110 Cr market cap on listing day",
    revenueAtExit: "undisclosed at listing",
    bestKnownFor:
      "Growing an underserved-MSME lending brand almost entirely through hyperlocal, branch-level trust-building and word-of-mouth in tier 2/3 towns rather than mass digital or brand advertising",
    disciplines: ["brand-strategy", "growth", "pr-communications", "content"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2022-11-21",
      valueLabel: "₹1,960 Cr raised via Offer for Sale (~$240M); market cap ~₹13,110 Cr (~$1.6B) on listing, Nov 2022",
      source: "https://www.businesstoday.in/markets/ipo-corner/story/five-star-business-finance-lists-at-5-discount-to-issue-price-m-cap-at-rs-13110-crore-353503-2022-11-21",
    },
    keyNumbers: [
      "IPO entirely an Offer for Sale of ₹1,960 Cr by existing investors and promoter entities",
      "Listed at a 5% discount to issue price, but still debuted at a ~₹13,110 Cr market cap",
      "Backed by Matrix Partners, TPG and Norwest Venture Partners pre-IPO",
      "Built its loan book almost entirely branch-by-branch in underserved MSME markets",
    ],
  },
  {
    id: "yatra-online",
    name: "Yatra Online",
    website: "https://www.yatra.com",
    industry: "Online Travel Agency (OTA)",
    sector: "Travel",
    region: "india",
    hq: "Gurugram, India",
    founded: 2006,
    sizeAtExit: "₹775 Cr IPO issue size; ~₹2,132 Cr market cap on listing day",
    revenueAtExit: "undisclosed at listing",
    bestKnownFor:
      "Being one of India's earliest online travel agencies, building the category through early SEO/search dominance for flight and hotel booking queries plus a dedicated corporate-travel B2B sales motion",
    disciplines: ["seo", "paid-ads", "affiliate-marketing", "brand-strategy"],
    exit: {
      type: "ipo",
      scale: "mid",
      date: "2023-09-28",
      valueLabel: "₹775 Cr raised (~$93M); market cap ~₹2,132 Cr (~$256M) on listing, Sept 2023",
      source: "https://investors.yatra.com/press-releases/press-release-details/2023/Yatra-Online-Inc.s-Indian-subsidiary-to-list-on-the-Bombay-Stock-Exchange-on-September-28-2023/",
    },
    keyNumbers: [
      "Indian subsidiary Yatra Online Limited raised ₹775 Cr in its BSE/NSE IPO, listing Sept 28, 2023",
      "Listed at ₹127.50, a ~10.2% discount to the ₹142 issue price",
      "Note: the Yatra Online Inc. US entity had separately reached Nasdaq in Dec 2016 via a SPAC merger with Terrapin 3 Acquisition Corp — a distinct, earlier listing event from the 2023 Indian-subsidiary IPO",
      "Founded 2006, among the first online-first OTAs in India",
    ],
  },
  {
    id: "tac-security",
    name: "TAC Security (TAC Infosec)",
    website: "https://tacsecurity.com",
    industry: "Cybersecurity — Vulnerability & Risk Management SaaS",
    sector: "SaaS",
    region: "india",
    hq: "Mumbai, India",
    founded: 2013,
    sizeAtExit: "₹29.99 Cr SME IPO issue size",
    revenueAtExit: "₹11.84 Cr FY24 operating revenue",
    bestKnownFor:
      "A founder-led (Trishneet Arora) niche B2B cybersecurity brand built on personal-brand thought leadership and analyst/media visibility to win enterprise vulnerability-management accounts, well before the company was large enough for mainstream marketing spend",
    disciplines: ["content", "product-marketing", "pr-communications", "seo"],
    exit: {
      type: "ipo",
      scale: "small",
      date: "2024-04-05",
      valueLabel: "₹29.99 Cr raised (~$3.6M), NSE SME (Emerge) platform, Apr 2024",
      source: "https://www.chittorgarh.com/ipo/tac-infosec-ipo/1687/",
    },
    keyNumbers: [
      "SME IPO raised ₹29.99 Cr via NSE Emerge platform",
      "Listed at ₹290, a 173.6% premium over the ₹106 issue price on Apr 5, 2024",
      "FY24 operating revenue grew 17% to ₹11.84 Cr with net profit up 23%",
      "Founded 2013 by Trishneet Arora; serves 10,000+ clients across ~100 countries",
    ],
  },
  {
    id: "sula-vineyards",
    name: "Sula Vineyards",
    website: "https://www.sulavineyards.com",
    industry: "Wine & Beverages",
    sector: "Food & Beverage",
    region: "india",
    hq: "Nashik, Maharashtra, India",
    founded: 1999,
    sizeAtExit: "₹2,789 Cr market cap at listing (~$338M, Dec 2022)",
    revenueAtExit: "₹553.2 Cr revenue in FY23 (up from ~₹70 Cr in FY10)",
    bestKnownFor:
      "Turning wine into a lifestyle category in India through SulaFest, the country's first wine-and-music festival, and building vineyard wine-tourism into a standalone, revenue-generating brand experience rather than just a distribution channel for the winery.",
    disciplines: ["brand-strategy", "content", "pr-communications", "growth"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2022-12-22",
      valueLabel: "₹2,789 Cr (~$338M, as of Dec 2022 listing)",
      source: "https://www.business-standard.com/amp/article/news-cm/sula-vineyards-slips-on-debut-122122200291_1.html",
    },
    keyNumbers: [
      "60%+ share of India's premium wine market",
      "Revenue grew from ~₹70 Cr (FY10) to ₹553.2 Cr (FY23)",
      "SulaFest launched 2008 as India's first wine-and-music festival",
      "FY25 revenue hit an all-time high of ₹618.8 Cr, wine tourism segment up 10.2%",
    ],
  },
  {
    id: "utkarsh-small-finance-bank",
    name: "Utkarsh Small Finance Bank",
    website: "https://www.utkarsh.bank.in",
    industry: "Small Finance Banking / Microfinance",
    sector: "Fintech",
    region: "india",
    hq: "Varanasi, Uttar Pradesh, India",
    founded: 2009,
    sizeAtExit: "₹5,254 Cr market cap at listing (~$637M, Jul 2023)",
    revenueAtExit: "FY23 net interest income up 44.1% YoY; interest income up 35.5% YoY (bank financials, not a single revenue line)",
    bestKnownFor:
      "Rebuilding trust with rural and semi-urban borrowers across UP and Bihar by converting a grassroots joint-liability-group microfinance lender into a full-service bank without losing its door-step, community-outreach acquisition model.",
    disciplines: ["brand-strategy", "pr-communications", "growth", "content"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2023-07-21",
      valueLabel: "₹5,254 Cr (~$637M, as of Jul 2023 listing day)",
      source: "https://www.business-standard.com/markets/news/utkarsh-small-finance-bank-s-stock-soars-nearly-92-on-market-debut-123072100661_1.html",
    },
    keyNumbers: [
      "3.6 million customers across 26 states/UTs as of FY23",
      "830 banking outlets as of March 2023 (grown to 1,105 by Dec 2025)",
      "Stock closed 92% above its ₹25 IPO price on debut day",
      "Started 2009 with just 4 microfinance branches and 8,000 customers",
    ],
  },
  {
    id: "concord-biotech",
    name: "Concord Biotech",
    website: "https://www.concordbiotech.com",
    industry: "Pharmaceutical APIs (Fermentation-based Biopharma)",
    sector: "B2B Services",
    region: "india",
    hq: "Ahmedabad, Gujarat, India",
    founded: 1984,
    sizeAtExit: "₹9,863 Cr market cap at listing (~$1.19B, Aug 2023)",
    revenueAtExit: "₹377.81 Cr revenue from operations in FY23; net profit ₹240.08 Cr",
    bestKnownFor:
      "Building pure B2B scientific and regulatory credibility with global pharma buyers in the US, EU and Japan through manufacturing-quality certifications and technical trust, essentially winning market share with near-zero consumer-facing marketing.",
    disciplines: ["brand-strategy", "pr-communications", "product-marketing"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2023-08-18",
      valueLabel: "₹9,863 Cr (~$1.19B, as of Aug 2023 listing day)",
      source: "https://stockanalysis.com/quote/nse/CONCORDBIO/market-cap/",
    },
    keyNumbers: [
      "Supplies fermentation-based APIs to 70+ countries including US, EU and Japan",
      "Export revenue grew 46% YoY to ₹121.7 Cr; domestic revenue grew 12% to ₹135.8 Cr",
      "IPO subscribed 24.87x overall (67.67x in the QIB category)",
      "Listed at a 21.46% premium to its ₹741 issue price",
    ],
  },
  {
    id: "jyoti-cnc-automation",
    name: "Jyoti CNC Automation",
    website: "https://www.jyoti.co.in",
    industry: "Machine Tools & Precision Engineering",
    sector: "B2B Services",
    region: "india",
    hq: "Rajkot, Gujarat, India",
    founded: 1991,
    sizeAtExit: "₹9,875 Cr market cap at listing (~$1.19B, Jan 2024)",
    revenueAtExit: "₹929 Cr revenue in FY23, growing 44% to ₹1,338 Cr in FY24",
    bestKnownFor:
      "Riding and reinforcing India's 'Make in India' defense-manufacturing narrative to build both domestic procurement trust and export credibility for precision CNC machine tools sold into auto, aerospace and defense.",
    disciplines: ["brand-strategy", "pr-communications", "product-marketing", "content"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2024-01-16",
      valueLabel: "₹9,875 Cr (~$1.19B, as of Jan 2024 listing day)",
      source: "https://www.business-standard.com/amp/markets/news/newly-listed-stock-freezes-at-10-upper-circuit-up-110-over-issue-price-124032200451_1.html",
    },
    keyNumbers: [
      "Revenue grew 44% YoY, from ₹929 Cr (FY23) to ₹1,338 Cr (FY24)",
      "Aerospace and defence made up ~44% of Q4 FY25 revenue",
      "Exports to 40+ countries, roughly 40% of total revenue",
      "₹16.94 billion (₹1,694 Cr) in aerospace/defence orders booked in FY25",
    ],
  },
  {
    id: "go-digit-insurance",
    name: "Go Digit General Insurance",
    website: "https://www.godigit.com",
    industry: "General Insurance",
    sector: "Insurance",
    region: "india",
    hq: "Bengaluru, Karnataka, India",
    founded: 2017,
    sizeAtExit: "₹28,066 Cr market cap at listing (~$3.37B, May 2024)",
    revenueAtExit: "₹8,443 Cr total income in FY24 (GWP ₹9,016 Cr), up from ₹5,780 Cr in FY23",
    bestKnownFor:
      "The 'That's It!' campaign fronted by investor and brand ambassador Virat Kohli, using deliberately plain-language, no-jargon messaging to differentiate a digital-first insurer at the single most distrusted moment in the category: filing a claim.",
    disciplines: ["brand-strategy", "social", "pr-communications", "copywriting"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2024-05-23",
      valueLabel: "₹28,066 Cr (~$3.37B, as of May 2024 listing day)",
      source: "https://www.business-standard.com/amp/markets/capital-market-news/go-digit-general-insurance-ipo-subscribed-79-124051601147_1.html",
    },
    keyNumbers: [
      "FY24 GWP of ₹9,016 Cr, up 24.5% from ₹7,243 Cr in FY23",
      "FY24 total income ₹8,443 Cr; PAT up over 5x to ₹182 Cr",
      "'That's It!' brand campaign clip drew 20.7M views on Instagram alone",
      "Founded 2017 by Kamesh Goyal, with cricketer Virat Kohli as both investor and brand ambassador",
    ],
  },
  {
    id: "tbo-tek",
    name: "TBO Tek",
    website: "https://www.tbo.com",
    industry: "B2B Travel Distribution Platform",
    sector: "Travel",
    region: "india",
    hq: "Gurugram, Haryana, India",
    founded: 2006,
    sizeAtExit: "₹14,932 Cr market cap at listing (~$1.79B, May 2024)",
    revenueAtExit: "Recent reported annual revenue ~₹3,092 Cr; ~₹250 Cr PAT on ~₹2,000 Cr turnover cited around IPO timing",
    bestKnownFor:
      "Building a 147,000+ travel-buyer B2B network purely through agent-community trust, training and platform stickiness (TBO Academy-style enablement) rather than consumer advertising, in a category with almost no brand awareness outside the trade.",
    disciplines: ["growth", "content", "product-marketing", "pr-communications"],
    exit: {
      type: "ipo",
      scale: "mega",
      date: "2024-05-15",
      valueLabel: "₹14,932 Cr (~$1.79B, as of May 2024 listing day)",
      source: "https://www.business-standard.com/amp/markets/capital-market-news/tbo-tek-spurts-on-debut-124051500288_1.html",
    },
    keyNumbers: [
      "147,000+ registered travel buyers on the platform",
      "IPO subscribed 86.69x; listed at a 50% premium to its ₹920 issue price",
      "Serves agents across the Americas, UK, Europe, Africa, Middle East, India and APAC",
      "Platform traces back to 2006 as Travel Boutique Online, rebranded to TBO Tek for its IPO",
    ],
  },
  {
    id: "awfis-space-solutions",
    name: "Awfis Space Solutions",
    website: "https://www.awfis.com",
    industry: "Flexible Workspace / Coworking",
    sector: "B2B Services",
    region: "india",
    hq: "New Delhi, India",
    founded: 2015,
    sizeAtExit: "₹2,928 Cr market cap at listing (~$351M, May 2024)",
    revenueAtExit: "₹619 Cr total operating revenue in FY24, up from ₹419 Cr in FY23",
    bestKnownFor:
      "Becoming India's largest coworking brand by number of centres through aggressive city-tier expansion and enterprise account-based sales, then converting that scale claim into the marketing hook for being the first Indian coworking company to IPO.",
    disciplines: ["brand-strategy", "growth", "product-marketing", "pr-communications"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2024-05-30",
      valueLabel: "₹2,928 Cr (~$351M, as of May 2024 listing day)",
      source: "https://www.business-standard.com/amp/markets/news/ipo-alert-awfis-space-solutions-opens-today-should-you-subscribe-124052200230_1.html",
    },
    keyNumbers: [
      "200+ centres, 135,000+ seats across 18+ cities",
      "First Indian coworking company to go public; IPO oversubscribed 108.7x",
      "FY24 operating revenue ₹619 Cr, up from ₹419 Cr in FY23",
      "Listed at ₹435, a 13.58% premium to its ₹383 issue price",
    ],
  },
  {
    id: "yatharth-hospital",
    name: "Yatharth Hospital & Trauma Care Services",
    website: "https://www.yatharthhospitals.com",
    industry: "Hospital Chain / Healthcare Delivery",
    sector: "Healthtech",
    region: "india",
    hq: "Noida, Uttar Pradesh, India",
    founded: 2008,
    sizeAtExit: "₹2,866 Cr market cap at listing (~$346M, Aug 2023)",
    revenueAtExit: "₹184.81 Cr total income in FY23; net profit ₹32.10 Cr",
    bestKnownFor:
      "Building a trusted regional hospital brand across NCR's Tier-2 satellite cities by anchoring patient acquisition around government health-scheme empanelment (ESIS, ECHS, CGHS) rather than premium private-pay marketing.",
    disciplines: ["brand-strategy", "pr-communications", "growth", "content"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2023-08-07",
      valueLabel: "₹2,866 Cr (~$346M, as of Aug 2023 listing day)",
      source: "https://stockanalysis.com/quote/nse/YATHARTH/market-cap/",
    },
    keyNumbers: [
      "9 hospitals, 2,800+ beds, 12 Centres of Excellence",
      "Government schemes (ESIS/ECHS/CGHS) contributed ~40% of FY24 revenue",
      "FY25 revenue ₹880.5 Cr, up over 30% YoY",
      "Founded 2008 by two orthopedic doctors, Dr. Ajay Kumar Tyagi and Dr. Kapil Kumar",
    ],
  },
  {
    id: "bansal-wire-industries",
    name: "Bansal Wire Industries",
    website: "https://www.bansalwire.com",
    industry: "Steel Wire Manufacturing",
    sector: "B2B Services",
    region: "india",
    hq: "Ghaziabad, Uttar Pradesh, India",
    founded: 1985,
    sizeAtExit: "₹4,008 Cr market cap at listing (~$481M, Jul 2024)",
    revenueAtExit: "₹2,466 Cr revenue in FY24, up to ₹3,520 Cr in FY25",
    bestKnownFor:
      "A four-decade family manufacturer building export credibility across 60+ countries purely on certifications and OEM-relationship trust, then using its scale claim (India's largest stainless steel wire maker) as the entire IPO growth narrative rather than brand advertising.",
    disciplines: ["brand-strategy", "pr-communications", "product-marketing", "content"],
    exit: {
      type: "ipo",
      scale: "large",
      date: "2024-07-10",
      valueLabel: "₹4,008 Cr (~$481M, as of Jul 2024 listing)",
      source: "https://www.business-standard.com/amp/markets/news/bansal-wire-industries-lists-39-premium-over-its-issue-price-124071000231_1.html",
    },
    keyNumbers: [
      "India's largest stainless steel wire manufacturer, ~20% category market share",
      "Exports to 60+ countries",
      "Revenue grew from ₹2,466 Cr (FY24) to ₹3,520 Cr (FY25)",
      "Listed at ₹356, a 39% premium to its ₹256 issue price",
    ],
  },
];
