/**
 * GENERATED by scripts/build-projects-index.mjs — do not hand-edit once the
 * generator script exists and per-category modules are populated. Currently
 * hand-written as a Phase 1 scaffold with one example entry (see
 * PROJECTS_PLAN.md section 5.1 and AGENTS.md Rule 37/41).
 *
 * This is a SLIM CARD PROJECTION, not the full Project data. The /projects
 * hub client bundle reads only this file, never a src/lib/projects/*.ts
 * category module directly (AGENTS.md Rule 41: never ship a large data
 * module, including long strings like outputSample/dashboard, to a
 * "use client" file that every hub visitor downloads). Full Project objects
 * are dynamically imported one category at a time, on demand, by
 * ProjectDrawer.tsx when a learner opens a specific card.
 *
 * Regenerate with: node --import tsx scripts/build-projects-index.mjs
 */

import type { ProjectTier, Archetype, ProjectMode } from "@/lib/projects/types";

export type ProjectCardData = {
  id: string;
  category: string;
  lessonSlug: string;
  lessonTitle: string;
  tier: ProjectTier;
  archetype: Archetype;
  mode: ProjectMode;
  title: string;
  timeMinutes: number;
  companyId: string;
  conceptsCovered: string[];
};

export const PROJECTS_INDEX: ProjectCardData[] = [
  {
    "id": "paid-ads-101-learning-phase-sim",
    "category": "paid-ads",
    "lessonSlug": "paid-ads-101",
    "lessonTitle": "Paid Ads 101",
    "tier": "core",
    "archetype": "simulation",
    "mode": "simulation",
    "title": "The 14-Day Learning Phase: A Google Search Campaign Simulation",
    "timeMinutes": 45,
    "companyId": "freshworks",
    "conceptsCovered": [
      "auction mechanics (bid x quality score)",
      "CTR vs. conversion-rate diagnosis",
      "the 7-14 day learning phase",
      "ROAS interpretation",
      "one-change-at-a-time discipline"
    ]
  }
];
