/**
 * GENERATED by scripts/build-projects-index.mjs — do not hand-edit once the
 * generator script exists and per-category modules are populated. Currently
 * hand-written as a Phase 1 scaffold with one example entry (see
 * PROJECTS_PLAN.md section 5.1 and AGENTS.md Rule 37/41).
 *
 * This is a SLIM CARD PROJECTION, not the full Project data. The /projects
 * hub client bundle reads only this file, never a src/lib/projects/*.ts
 * category module directly (AGENTS.md Rule 41: never ship a large data
 * module, including long strings like outputSample/dashboard, to a
 * "use client" file that every hub visitor downloads). Full Project objects
 * are dynamically imported one category at a time, on demand, by
 * ProjectDrawer.tsx when a learner opens a specific card.
 *
 * Regenerate with: node --import tsx scripts/build-projects-index.mjs
 */

import type { ProjectTier, Archetype, ProjectMode } from "@/lib/projects/types";

export type ProjectCardData = {
  id: string;
  category: string;
  lessonSlug: string;
  lessonTitle: string;
  tier: ProjectTier;
  archetype: Archetype;
  mode: ProjectMode;
  title: string;
  timeMinutes: number;
  companyId: string;
  conceptsCovered: string[];
};

export const PROJECTS_INDEX: ProjectCardData[] = [
  {
    "id": "analytics-101-instacart-tracking-audit",
    "category": "analytics",
    "lessonSlug": "analytics-101",
    "lessonTitle": "Analytics 101",
    "tier": "big",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "The Full GA4 Tracking Audit: Instacart's Marketing Funnel",
    "timeMinutes": 70,
    "companyId": "instacart",
    "conceptsCovered": [
      "Session",
      "Engaged Session",
      "User (vs. Active User)",
      "Key Event",
      "Actionable vs. Vanity Metrics"
    ]
  },
  {
    "id": "analytics-101-chewy-broken-tracking-rebuild",
    "category": "analytics",
    "lessonSlug": "analytics-101",
    "lessonTitle": "Analytics 101",
    "tier": "core",
    "archetype": "rebuild",
    "mode": "build",
    "title": "Rebuild Chewy's Broken Analytics Setup from a Handoff Doc",
    "timeMinutes": 45,
    "companyId": "chewy",
    "conceptsCovered": [
      "Event",
      "Session",
      "Key Event",
      "Actionable vs. Vanity Metrics"
    ]
  },
  {
    "id": "what-is-content-marketing-teardown",
    "category": "content",
    "lessonSlug": "what-is-content-marketing",
    "lessonTitle": "What Content Marketing Really Is",
    "tier": "mini",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "Content Marketing or Disguised Ad? Three Specimens, One Test",
    "timeMinutes": 20,
    "companyId": "mailchimp",
    "conceptsCovered": [
      "What It Actually Is",
      "Common Mistakes"
    ]
  },
  {
    "id": "what-is-content-marketing-brief-build",
    "category": "content",
    "lessonSlug": "what-is-content-marketing",
    "lessonTitle": "What Content Marketing Really Is",
    "tier": "mini",
    "archetype": "build-the-asset",
    "mode": "build",
    "title": "Write a One-Page Brief That Passes the Logo Test",
    "timeMinutes": 35,
    "companyId": "chewy",
    "conceptsCovered": [
      "What It Actually Is",
      "How It Works / The Playbook"
    ]
  },
  {
    "id": "content-strategy-pillar-doc-build",
    "category": "content",
    "lessonSlug": "content-strategy",
    "lessonTitle": "Content Strategy",
    "tier": "core",
    "archetype": "build-the-asset",
    "mode": "build",
    "title": "Build Freshworks' Two-Page Content Strategy Document",
    "timeMinutes": 75,
    "companyId": "freshworks",
    "conceptsCovered": [
      "Step 1: Pick one primary audience",
      "Step 2: Map their journey to three stages",
      "Step 3: Choose two channels, maximum",
      "Step 4: Define what \"worked\" looks like per format",
      "Step 5: Commit to a cadence you can sustain for 12 months",
      "Step 6: Write the \"will not publish\" list"
    ]
  },
  {
    "id": "content-strategy-channel-audit",
    "category": "content",
    "lessonSlug": "content-strategy",
    "lessonTitle": "Content Strategy",
    "tier": "core",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "Audit PolicyBazaar's Content Channel Mix Against the Two-Channel Rule",
    "timeMinutes": 50,
    "companyId": "policybazaar",
    "conceptsCovered": [
      "Checking whether content investment is actually running through 2 channels or quietly spread across more",
      "Checking whether each channel is judged on its own metric or lumped into one blanket KPI",
      "Checking how much published content never gets indexed, a sign the 'will not publish' list isn't being enforced"
    ]
  },
  {
    "id": "copywriting-101-landing-copy-teardown",
    "category": "copywriting",
    "lessonSlug": "copywriting-101",
    "lessonTitle": "Copywriting 101",
    "tier": "core",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "Spot the Copy Killers: A Landing Page Teardown",
    "timeMinutes": 35,
    "companyId": "dollar-shave-club",
    "conceptsCovered": [
      "Step 1: Attention",
      "Step 3: Desire",
      "Step 4: Action",
      "Mistake 1: Writing About Yourself Instead of the Reader",
      "Mistake 3: Vague, Weak CTAs",
      "Mistake 4: No Specificity",
      "Mistake 5: Ignoring Skimmers"
    ]
  },
  {
    "id": "copywriting-101-rebuild-the-page",
    "category": "copywriting",
    "lessonSlug": "copywriting-101",
    "lessonTitle": "Copywriting 101",
    "tier": "core",
    "archetype": "rebuild",
    "mode": "build",
    "title": "Rebuild It: Turn Weak Copy Into a Converting Page",
    "timeMinutes": 40,
    "companyId": "zomato",
    "conceptsCovered": [
      "How It Works: The AIDA Playbook",
      "Step 1: Attention",
      "Step 3: Desire",
      "Step 4: Action",
      "Mistake 1: Writing About Yourself Instead of the Reader",
      "Mistake 2: Burying the Benefit",
      "Mistake 4: No Specificity",
      "Mistake 5: Ignoring Skimmers"
    ]
  },
  {
    "id": "headlines-head-to-head-scoring",
    "category": "copywriting",
    "lessonSlug": "headlines",
    "lessonTitle": "Headline Writing",
    "tier": "core",
    "archetype": "head-to-head",
    "mode": "build",
    "title": "Head-to-Head: Score Four Term-Insurance Blog Headlines",
    "timeMinutes": 30,
    "companyId": "policybazaar",
    "conceptsCovered": [
      "How It Works",
      "Psychological Triggers That Work",
      "Common Mistakes"
    ]
  },
  {
    "id": "headlines-build-the-asset",
    "category": "copywriting",
    "lessonSlug": "headlines",
    "lessonTitle": "Headline Writing",
    "tier": "core",
    "archetype": "build-the-asset",
    "mode": "build",
    "title": "Build the Asset: Write 5 Original Headlines and Score Your Own Work",
    "timeMinutes": 35,
    "companyId": "nykaa",
    "conceptsCovered": [
      "How It Works",
      "Psychological Triggers That Work",
      "Common Mistakes",
      "Key Takeaways"
    ]
  },
  {
    "id": "email-marketing-101-ten-campaign-audit",
    "category": "email",
    "lessonSlug": "email-marketing-101",
    "lessonTitle": "Email Marketing 101",
    "tier": "core",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "Ten Campaigns, One Real Problem: Auditing a Live Email Export",
    "timeMinutes": 40,
    "companyId": "freshworks",
    "conceptsCovered": [
      "Key Metrics to Track",
      "Segmentation and Automation: Where the Money Is",
      "Writing Emails That Get Opened and Clicked"
    ]
  },
  {
    "id": "email-marketing-101-trigger-vs-batch-headtohead",
    "category": "email",
    "lessonSlug": "email-marketing-101",
    "lessonTitle": "Email Marketing 101",
    "tier": "mini",
    "archetype": "head-to-head",
    "mode": "diagnostic",
    "title": "Triggered Send vs. Scheduled Batch: A Head-to-Head from the Same Export",
    "timeMinutes": 25,
    "companyId": "mailchimp",
    "conceptsCovered": [
      "Automation",
      "Subject lines",
      "Key Metrics to Track"
    ]
  },
  {
    "id": "welcome-series-draft-three-email-sequence",
    "category": "email",
    "lessonSlug": "welcome-series",
    "lessonTitle": "The Welcome Series",
    "tier": "core",
    "archetype": "build-the-asset",
    "mode": "build",
    "title": "Draft a Real 3-Email Welcome Series",
    "timeMinutes": 50,
    "companyId": "chewy",
    "conceptsCovered": [
      "How the Series Works",
      "Subject Line Strategy",
      "Common Mistakes to Avoid",
      "The Timing That Matters Most"
    ]
  },
  {
    "id": "welcome-series-teardown-specimen",
    "category": "email",
    "lessonSlug": "welcome-series",
    "lessonTitle": "The Welcome Series",
    "tier": "core",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "Teardown: A Welcome Series That's Losing Money",
    "timeMinutes": 35,
    "companyId": "bonobos",
    "conceptsCovered": [
      "How the Series Works",
      "Common Mistakes to Avoid",
      "Conditional Splits: The Feature Most Brands Ignore",
      "Subject Line Strategy",
      "The Timing That Matters Most"
    ]
  },
  {
    "id": "value-proposition-seed-deck-build",
    "category": "fundamentals",
    "lessonSlug": "value-proposition",
    "lessonTitle": "The Value Proposition",
    "tier": "core",
    "archetype": "build-the-asset",
    "mode": "build",
    "title": "The Seed Deck Value Prop: Writing One a VC Can't Poke Holes In",
    "timeMinutes": 40,
    "companyId": "native-deodorant",
    "conceptsCovered": [
      "How It Works",
      "How to Write Your First Draft",
      "Common Mistakes"
    ]
  },
  {
    "id": "value-proposition-two-drafts-head-to-head",
    "category": "fundamentals",
    "lessonSlug": "value-proposition",
    "lessonTitle": "The Value Proposition",
    "tier": "mini",
    "archetype": "head-to-head",
    "mode": "diagnostic",
    "title": "Two Drafts, One Board Meeting: Judging Value Props Against the Framework",
    "timeMinutes": 20,
    "companyId": "walker-and-company",
    "conceptsCovered": [
      "Common Mistakes"
    ]
  },
  {
    "id": "marketing-math-cfo-unit-economics-audit",
    "category": "fundamentals",
    "lessonSlug": "marketing-math",
    "lessonTitle": "Marketing Math: CAC, LTV, ROAS, Payback",
    "tier": "core",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "The CFO Meeting: Auditing a Paid Social Channel's Real Unit Economics",
    "timeMinutes": 35,
    "companyId": "freshworks",
    "conceptsCovered": [
      "1. CAC, Customer Acquisition Cost",
      "2. LTV, Lifetime Value (also called CLV or Customer Lifetime Value)",
      "3. ROAS, Return on Ad Spend",
      "4. Payback Period",
      "How the Four Metrics Work Together"
    ]
  },
  {
    "id": "marketing-math-rapid-fire-drills",
    "category": "fundamentals",
    "lessonSlug": "marketing-math",
    "lessonTitle": "Marketing Math: CAC, LTV, ROAS, Payback",
    "tier": "mini",
    "archetype": "forecast",
    "mode": "drill",
    "title": "Investor Q&A Drills: Six Rapid CAC/LTV/ROAS/Payback Reps",
    "timeMinutes": 25,
    "companyId": "zomato",
    "conceptsCovered": [
      "1. CAC, Customer Acquisition Cost",
      "2. LTV, Lifetime Value (also called CLV or Customer Lifetime Value)",
      "3. ROAS, Return on Ad Spend",
      "4. Payback Period"
    ]
  },
  {
    "id": "pmf-retention-audit-signals",
    "category": "fundamentals",
    "lessonSlug": "product-market-fit",
    "lessonTitle": "Product–Market Fit",
    "tier": "core",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "Reading the Three PMF Signals: A Real Retention-Curve and Survey Audit",
    "timeMinutes": 40,
    "companyId": "duolingo",
    "conceptsCovered": [
      "Signal 1: The Sean Ellis Test",
      "Signal 2: Retention Curves That Flatten",
      "Signal 3: Word-of-Mouth Without Prompting"
    ]
  },
  {
    "id": "pmf-vanity-growth-teardown",
    "category": "fundamentals",
    "lessonSlug": "product-market-fit",
    "lessonTitle": "Product–Market Fit",
    "tier": "mini",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "Vanity Growth or Real PMF? Tearing Down a Pre-Series-B Growth Memo",
    "timeMinutes": 25,
    "companyId": "winc-club-w",
    "conceptsCovered": [
      "Signal 1: The Sean Ellis Test",
      "Signal 2: Retention Curves That Flatten",
      "Common Mistakes to Avoid"
    ]
  },
  {
    "id": "what-is-growth-vanity-metrics-teardown",
    "category": "growth",
    "lessonSlug": "what-is-growth",
    "lessonTitle": "What Growth Marketing Really Is",
    "tier": "core",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "The Vanity Metrics Deck: Spot What's Actually Growth",
    "timeMinutes": 30,
    "companyId": "duolingo",
    "conceptsCovered": [
      "Choose Your North Star Metric",
      "Map the AARRR Funnel",
      "Measuring outputs instead of outcomes"
    ]
  },
  {
    "id": "what-is-growth-loop-plateau-forecast",
    "category": "growth",
    "lessonSlug": "what-is-growth",
    "lessonTitle": "What Growth Marketing Really Is",
    "tier": "core",
    "archetype": "forecast",
    "mode": "diagnostic",
    "title": "Loop or Funnel? Forecasting Whether Swiggy Instamart's Growth Holds",
    "timeMinutes": 40,
    "companyId": "swiggy",
    "conceptsCovered": [
      "Map the AARRR Funnel",
      "Growth Loops vs. Linear Funnels",
      "Measuring outputs instead of outcomes"
    ]
  },
  {
    "id": "north-star-metric-policybazaar-nsm-defense",
    "category": "growth",
    "lessonSlug": "north-star-metric",
    "lessonTitle": "The North Star Metric",
    "tier": "core",
    "archetype": "forecast",
    "mode": "build",
    "title": "Pick and Defend PolicyBazaar's North Star Metric",
    "timeMinutes": 50,
    "companyId": "policybazaar",
    "conceptsCovered": [
      "Write the Value Statement",
      "Test Against Three Criteria",
      "Decompose into Input Metrics",
      "Before Product-Market Fit: A Special Case"
    ]
  },
  {
    "id": "north-star-metric-zomato-head-to-head",
    "category": "growth",
    "lessonSlug": "north-star-metric",
    "lessonTitle": "The North Star Metric",
    "tier": "mini",
    "archetype": "head-to-head",
    "mode": "drill",
    "title": "Orders Placed vs. App Opens: A Head-to-Head NSM Drill",
    "timeMinutes": 20,
    "companyId": "zomato",
    "conceptsCovered": [
      "The Three Games Your Product Can Play",
      "Test Against Three Criteria"
    ]
  },
  {
    "id": "first-principles-thinking-memo-teardown",
    "category": "mental-models",
    "lessonSlug": "first-principles-thinking",
    "lessonTitle": "First-Principles Thinking",
    "tier": "core",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "Borrowed Reasoning or Derived Truth? A Growth Memo Teardown",
    "timeMinutes": 30,
    "companyId": "allbirds",
    "conceptsCovered": [
      "What It Actually Is",
      "The Playbook: The Three-Step Method",
      "Common Mistakes"
    ]
  },
  {
    "id": "first-principles-thinking-rebuild-assumption",
    "category": "mental-models",
    "lessonSlug": "first-principles-thinking",
    "lessonTitle": "First-Principles Thinking",
    "tier": "core",
    "archetype": "build-the-asset",
    "mode": "build",
    "title": "Rebuild One Assumption-Driven Decision From Scratch",
    "timeMinutes": 45,
    "companyId": "casper-sleep",
    "conceptsCovered": [
      "The Playbook: The Three-Step Method",
      "Why It Matters",
      "A Real Example"
    ]
  },
  {
    "id": "writing-to-think-decision-memo",
    "category": "mental-models",
    "lessonSlug": "writing-to-think",
    "lessonTitle": "Writing to Think",
    "tier": "core",
    "archetype": "build-the-asset",
    "mode": "build",
    "title": "The Prose Test: Write a Real Decision Memo",
    "timeMinutes": 40,
    "companyId": "klaviyo",
    "conceptsCovered": [
      "The Playbook: The Prose Test",
      "What Actually Improves From Writing",
      "Common Mistakes"
    ]
  },
  {
    "id": "writing-to-think-memo-head-to-head",
    "category": "mental-models",
    "lessonSlug": "writing-to-think",
    "lessonTitle": "Writing to Think",
    "tier": "mini",
    "archetype": "head-to-head",
    "mode": "teardown",
    "title": "Two Memos, Same Decision: Which One Actually Thought It Through?",
    "timeMinutes": 25,
    "companyId": "chewy",
    "conceptsCovered": [
      "The Playbook: The Prose Test",
      "What It Actually Is",
      "Common Mistakes"
    ]
  },
  {
    "id": "paid-ads-101-learning-phase-sim",
    "category": "paid-ads",
    "lessonSlug": "paid-ads-101",
    "lessonTitle": "Paid Ads 101",
    "tier": "core",
    "archetype": "simulation",
    "mode": "simulation",
    "title": "The 14-Day Learning Phase: A Google Search Campaign Simulation",
    "timeMinutes": 45,
    "companyId": "freshworks",
    "conceptsCovered": [
      "auction mechanics (bid x quality score)",
      "CTR vs. conversion-rate diagnosis",
      "the 7-14 day learning phase",
      "ROAS interpretation",
      "one-change-at-a-time discipline"
    ]
  },
  {
    "id": "paid-ads-101-account-teardown",
    "category": "paid-ads",
    "lessonSlug": "paid-ads-101",
    "lessonTitle": "Paid Ads 101",
    "tier": "mini",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "Spot the Structural Mistakes: A Google Ads Account Teardown",
    "timeMinutes": 20,
    "companyId": "hellofresh",
    "conceptsCovered": [
      "Mistake 1: sending ad traffic to your homepage",
      "Ad Group / Ad Set level: one keyword theme per group (The Full Campaign Structure)",
      "Ad level: run at least 2 ads per group to compare (The Full Campaign Structure)",
      "Mistake 2: starting with too broad a target before narrowing"
    ]
  },
  {
    "id": "keyword-research-export-audit",
    "category": "seo",
    "lessonSlug": "keyword-research",
    "lessonTitle": "Keyword Research",
    "tier": "core",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "The Prioritization Call: Auditing a Real Keyword Export",
    "timeMinutes": 40,
    "companyId": "freshworks",
    "conceptsCovered": [
      "Filtering by search intent before filtering by anything else",
      "Scoring realistic targets with the volume/difficulty/relevance table",
      "Treating search volume as the only metric that matters (Mistake 2)",
      "Fixing keywords you already rank for before chasing new ones (Mistake 3)"
    ]
  },
  {
    "id": "keyword-research-targeting-showdown",
    "category": "seo",
    "lessonSlug": "keyword-research",
    "lessonTitle": "Keyword Research",
    "tier": "mini",
    "archetype": "head-to-head",
    "mode": "diagnostic",
    "title": "One Page, Two Strategies: Broad Head Term vs. Long-Tail Cluster",
    "timeMinutes": 20,
    "companyId": "policybazaar",
    "conceptsCovered": [
      "Comparing a head term against a long-tail cluster using the lesson's own realistic-target framework",
      "Applying the Airbnb long-tail case to justify the cluster strategy"
    ]
  },
  {
    "id": "on-page-seo-title-tag-audit",
    "category": "seo",
    "lessonSlug": "on-page-seo",
    "lessonTitle": "On-Page SEO",
    "tier": "core",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "The Striking-Distance Audit: Fixing Titles Before Writing Anything New",
    "timeMinutes": 35,
    "companyId": "zillow",
    "conceptsCovered": [
      "Title tag length and keyword position",
      "URL slug clarity",
      "Meta description as a CTR lever, not a ranking factor",
      "Connecting the fix to the lesson's CTR-by-position numbers"
    ]
  },
  {
    "id": "on-page-seo-rebuild-the-page",
    "category": "seo",
    "lessonSlug": "on-page-seo",
    "lessonTitle": "On-Page SEO",
    "tier": "mini",
    "archetype": "rebuild",
    "mode": "build",
    "title": "Rebuild a Broken Page: Title, URL, H1, Meta, and Internal Links",
    "timeMinutes": 30,
    "companyId": "care-com",
    "conceptsCovered": [
      "Title Tag rules",
      "URL Slug cleanliness",
      "H1 Heading matching search intent",
      "Meta Description as a CTR lever",
      "Internal Links and descriptive anchor text"
    ]
  },
  {
    "id": "mobile-first-indexing-parity-teardown",
    "category": "seo",
    "lessonSlug": "mobile-first-indexing",
    "lessonTitle": "Mobile-First Indexing",
    "tier": "mini",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "Mobile-First Content Parity Teardown: Care.com Profile Templates",
    "timeMinutes": 25,
    "companyId": "care-com",
    "conceptsCovered": [
      "The Content Parity Problem",
      "Why Marketers Should Care, Not Just Developers"
    ]
  },
  {
    "id": "mobile-first-indexing-gsc-audit",
    "category": "seo",
    "lessonSlug": "mobile-first-indexing",
    "lessonTitle": "Mobile-First Indexing",
    "tier": "core",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "Mobile-First Indexing Audit: Diagnosing Chewy's Redesign Regression",
    "timeMinutes": 45,
    "companyId": "chewy",
    "conceptsCovered": [
      "How to Check Your Own Site",
      "The Content Parity Problem",
      "Why Marketers Should Care, Not Just Developers"
    ]
  },
  {
    "id": "how-search-works-outrank-reverse-engineer",
    "category": "seo",
    "lessonSlug": "how-search-works",
    "lessonTitle": "How Search Engines Actually Work",
    "tier": "mini",
    "archetype": "reverse-engineer",
    "mode": "diagnostic",
    "title": "Why This Page Outranks Yours: Reverse-Engineering the Crawl-Index-Rank Gap",
    "timeMinutes": 20,
    "companyId": "zendesk",
    "conceptsCovered": [
      "Stage 2: Indexing",
      "Stage 3: Ranking"
    ]
  },
  {
    "id": "how-search-works-crawl-budget-audit",
    "category": "seo",
    "lessonSlug": "how-search-works",
    "lessonTitle": "How Search Engines Actually Work",
    "tier": "core",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "The Crawl Budget Audit: Finding Where Snowflake's Docs Section Loses Google's Attention",
    "timeMinutes": 40,
    "companyId": "snowflake",
    "conceptsCovered": [
      "Crawl budget as a finite daily allocation",
      "Orphan pages that crawlers rarely find",
      "Not every crawled page gets indexed"
    ]
  },
  {
    "id": "technical-seo-indexability-triage",
    "category": "seo",
    "lessonSlug": "technical-seo",
    "lessonTitle": "Technical SEO",
    "tier": "mini",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "The Indexability Triage: Reading a Real GSC Export Before Touching Code",
    "timeMinutes": 20,
    "companyId": "squarespace",
    "conceptsCovered": [
      "robots.txt",
      "Indexability"
    ]
  },
  {
    "id": "technical-seo-robots-canonical-teardown",
    "category": "seo",
    "lessonSlug": "technical-seo",
    "lessonTitle": "Technical SEO",
    "tier": "mini",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "The robots.txt & Canonical Teardown: Spot the Defect Before It Ships",
    "timeMinutes": 20,
    "companyId": "mapmyindia",
    "conceptsCovered": [
      "robots.txt",
      "Canonical Tags"
    ]
  },
  {
    "id": "core-web-vitals-field-vs-lab-audit",
    "category": "seo",
    "lessonSlug": "core-web-vitals",
    "lessonTitle": "Core Web Vitals",
    "tier": "mini",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "The Field-vs-Lab Audit: Finding Which Template Is Actually 'Poor'",
    "timeMinutes": 20,
    "companyId": "rategain-travel-technologies",
    "conceptsCovered": [
      "LCP, Largest Contentful Paint",
      "CLS, Cumulative Layout Shift"
    ]
  },
  {
    "id": "core-web-vitals-lcp-business-case-forecast",
    "category": "seo",
    "lessonSlug": "core-web-vitals",
    "lessonTitle": "Core Web Vitals",
    "tier": "mini",
    "archetype": "forecast",
    "mode": "diagnostic",
    "title": "The Business Case: Forecasting What a Faster Currency Converter Is Worth",
    "timeMinutes": 20,
    "companyId": "wise",
    "conceptsCovered": [
      "How Google Actually Measures This",
      "Nykaa, 28% more organic traffic from LCP improvement"
    ]
  },
  {
    "id": "https-security-seo-mixed-content-hsts-teardown",
    "category": "seo",
    "lessonSlug": "https-security-seo",
    "lessonTitle": "HTTPS & Security Headers for SEO",
    "tier": "mini",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "The Mixed-Content & HSTS Teardown: Spot the Broken Padlock Before It Ships",
    "timeMinutes": 20,
    "companyId": "adyen",
    "conceptsCovered": [
      "HTTPS Migration, Done Right",
      "Testing Your Setup"
    ]
  },
  {
    "id": "https-security-seo-migration-audit",
    "category": "seo",
    "lessonSlug": "https-security-seo",
    "lessonTitle": "HTTPS & Security Headers for SEO",
    "tier": "core",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "The HTTPS Migration Audit: Verifying the Redirect Chain Didn't Leak Signal",
    "timeMinutes": 40,
    "companyId": "flipkart",
    "conceptsCovered": [
      "HTTPS Migration, Done Right",
      "Security Headers That Actually Matter",
      "Testing Your Setup"
    ]
  },
  {
    "id": "internal-linking-orphan-anchor-audit",
    "category": "seo",
    "lessonSlug": "internal-linking",
    "lessonTitle": "Internal Linking & Site Architecture",
    "tier": "mini",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "Finding the Ghost Pages: An Orphan Page & Anchor Text Audit",
    "timeMinutes": 25,
    "companyId": "thredup",
    "conceptsCovered": [
      "Orphaned pages",
      "Anchor Text: The Overlooked Relevance Signal"
    ]
  },
  {
    "id": "internal-linking-pillar-cluster-map",
    "category": "seo",
    "lessonSlug": "internal-linking",
    "lessonTitle": "Internal Linking & Site Architecture",
    "tier": "mini",
    "archetype": "build-the-asset",
    "mode": "build",
    "title": "Build the Web: A Pillar-Cluster Internal Linking Map",
    "timeMinutes": 30,
    "companyId": "klaviyo",
    "conceptsCovered": [
      "The Topic Cluster Model: The Best Architecture in 2025",
      "The Three-Click Rule"
    ]
  },
  {
    "id": "schema-structured-data-broken-jsonld-teardown",
    "category": "seo",
    "lessonSlug": "schema-structured-data",
    "lessonTitle": "Schema & Structured Data",
    "tier": "mini",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "Spot the Schema Violations: A Broken Product JSON-LD Teardown",
    "timeMinutes": 20,
    "companyId": "lenskart",
    "conceptsCovered": [
      "Common Mistakes",
      "How It Works"
    ]
  },
  {
    "id": "schema-structured-data-build-product-schema",
    "category": "seo",
    "lessonSlug": "schema-structured-data",
    "lessonTitle": "Schema & Structured Data",
    "tier": "core",
    "archetype": "build-the-asset",
    "mode": "build",
    "title": "Ship It Right: Building a Valid Product Schema Block From Scratch",
    "timeMinutes": 45,
    "companyId": "firstcry-brainbees",
    "conceptsCovered": [
      "The Schema Types That Actually Move the Needle",
      "How It Works",
      "Common Mistakes"
    ]
  },
  {
    "id": "duplicate-thin-content-variant-teardown",
    "category": "seo",
    "lessonSlug": "duplicate-thin-content",
    "lessonTitle": "Duplicate & Thin Content Cleanup",
    "tier": "mini",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "40 Pages, One Root Cause: A Duplicate & Thin Content Teardown",
    "timeMinutes": 20,
    "companyId": "rent-the-runway",
    "conceptsCovered": [
      "Where Duplicate Content Actually Comes From",
      "Fixing It: Canonicalize, Noindex, or Consolidate",
      "Word count is not the fix, added value is."
    ]
  },
  {
    "id": "duplicate-thin-content-gsc-coverage-audit",
    "category": "seo",
    "lessonSlug": "duplicate-thin-content",
    "lessonTitle": "Duplicate & Thin Content Cleanup",
    "tier": "mini",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "Reading the Warning Signs: A Search Console Coverage Audit",
    "timeMinutes": 20,
    "companyId": "hellofresh",
    "conceptsCovered": [
      "Watch for 'Crawled, currently not indexed'",
      "Fixing It: Canonicalize, Noindex, or Consolidate"
    ]
  },
  {
    "id": "ecommerce-product-page-seo-variant-schema-audit",
    "category": "seo",
    "lessonSlug": "ecommerce-product-page-seo",
    "lessonTitle": "SEO for Ecommerce Product Pages",
    "tier": "mini",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "One Page or Five? A Variant & Schema-Parity Audit",
    "timeMinutes": 25,
    "companyId": "warby-parker",
    "conceptsCovered": [
      "Why variants cause duplication",
      "Product Schema and Rich Results"
    ]
  },
  {
    "id": "ecommerce-product-page-seo-outofstock-teardown",
    "category": "seo",
    "lessonSlug": "ecommerce-product-page-seo",
    "lessonTitle": "SEO for Ecommerce Product Pages",
    "tier": "mini",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "Delete, Redirect, or Keep? An Out-of-Stock Decision Teardown",
    "timeMinutes": 20,
    "companyId": "honasa-mamaearth",
    "conceptsCovered": [
      "Handling Out-of-Stock and Discontinued Products"
    ]
  },
  {
    "id": "log-file-analysis-bot-verification-teardown",
    "category": "seo",
    "lessonSlug": "log-file-analysis",
    "lessonTitle": "Log File Analysis for SEO",
    "tier": "mini",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "The Impostor Crawler: Verifying Bot Identity in Raw Log Lines",
    "timeMinutes": 25,
    "companyId": "tac-security",
    "conceptsCovered": [
      "Verify bot identity via reverse DNS, do not trust the user-agent string alone",
      "Response codes served to bots specifically",
      "Orphaned pages that bots reach only via the sitemap, never through an internal link"
    ]
  },
  {
    "id": "log-file-analysis-gsc-indexing-diagnostic",
    "category": "seo",
    "lessonSlug": "log-file-analysis",
    "lessonTitle": "Log File Analysis for SEO",
    "tier": "core",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "Flat Traffic, Full Index? Diagnosing a Real Indexing Export",
    "timeMinutes": 45,
    "companyId": "yatra-online",
    "conceptsCovered": [
      "Which pages get crawled most and least often, revealing a mismatch between what you consider important and what bots actually prioritize",
      "Exactly which AI crawlers visit, how often, and which pages they touch, data that exists nowhere else",
      "Orphaned pages that bots reach only via the sitemap, never through an internal link",
      "Crawl behavior shifts after every major release, a monthly cadence tells you whether things are trending right or quietly breaking"
    ]
  },
  {
    "id": "llms-txt-ai-crawler-management-robots-teardown",
    "category": "seo",
    "lessonSlug": "llms-txt-ai-crawler-management",
    "lessonTitle": "llms.txt and AI Crawler Management",
    "tier": "mini",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "Blocked Everything, Cited Nothing: A Broken robots.txt and llms.txt Pair",
    "timeMinutes": 20,
    "companyId": "coinbase",
    "conceptsCovered": [
      "Training bots and retrieval bots from the same company are different user-agents, you can block one and allow the other",
      "What llms.txt actually is: a proposed convention, not an enforced standard"
    ]
  },
  {
    "id": "llms-txt-ai-crawler-management-bot-policy-audit",
    "category": "seo",
    "lessonSlug": "llms-txt-ai-crawler-management",
    "lessonTitle": "llms.txt and AI Crawler Management",
    "tier": "mini",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "Write the Policy, Then Prove It Holds: An AI Bot Access Audit",
    "timeMinutes": 25,
    "companyId": "robinhood",
    "conceptsCovered": [
      "Training bots and retrieval bots from the same AI company are different user-agents, you can allow one and block the other",
      "Revisit the whole setup quarterly, this space moves fast and last quarter's setup may already be outdated"
    ]
  },
  {
    "id": "international-seo-hreflang-teardown",
    "category": "seo",
    "lessonSlug": "international-seo",
    "lessonTitle": "International SEO",
    "tier": "mini",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "48 Hours to Launch: A Broken hreflang Rollout",
    "timeMinutes": 25,
    "companyId": "grab",
    "conceptsCovered": [
      "Every tagged page must include tags pointing to ALL alternate versions (including itself)",
      "Language codes use ISO 639-1 format and country codes use ISO 3166-1 alpha-2",
      "The most common hreflang mistake: adding tags to a few top pages but leaving thousands of pages untagged"
    ]
  },
  {
    "id": "international-seo-market-expansion-audit",
    "category": "seo",
    "lessonSlug": "international-seo",
    "lessonTitle": "International SEO",
    "tier": "core",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "One Quarter, One Market: The Poland Expansion Call",
    "timeMinutes": 50,
    "companyId": "sea-limited",
    "conceptsCovered": [
      "Choose the right URL structure (ccTLD, subfolder, or subdomain) based on your budget and goals",
      "Validate demand first: check Search Console for organic impressions from target countries before building anything",
      "Localization means more than translation: keyword research must be done natively in each market",
      "Hreflang must be implemented on every page consistently, partial rollouts create confusion"
    ]
  },
  {
    "id": "seo-site-migrations-redirect-and-noindex-teardown",
    "category": "seo",
    "lessonSlug": "seo-site-migrations",
    "lessonTitle": "SEO for Site Migrations",
    "tier": "mini",
    "archetype": "teardown",
    "mode": "teardown",
    "title": "30 Minutes to Go/No-Go: A Redirect Map and Staging Leftovers",
    "timeMinutes": 25,
    "companyId": "doordash",
    "conceptsCovered": [
      "Missing or many-to-one redirects",
      "Build a 1:1 redirect map for every indexed URL",
      "Leftover staging noindex tags, the single most common cause of a post-launch traffic cliff"
    ]
  },
  {
    "id": "seo-site-migrations-post-launch-gsc-diagnostic",
    "category": "seo",
    "lessonSlug": "seo-site-migrations",
    "lessonTitle": "SEO for Site Migrations",
    "tier": "core",
    "archetype": "audit",
    "mode": "diagnostic",
    "title": "Week Six: Normal Volatility or Hangover in Progress?",
    "timeMinutes": 45,
    "companyId": "stoneco",
    "conceptsCovered": [
      "Build a 1:1 redirect map for every indexed URL; never redirect multiple pages to one destination",
      "Leftover staging noindex tags or a robots.txt Disallow rule that was fine on staging but never got removed for production",
      "A 10-30% dip that stabilizes within 2-6 weeks is normal volatility; still falling after 4 weeks is a hangover in progress",
      "Use Google Search Console's Change of Address tool and add the new property alongside the old one, don't delete the old property"
    ]
  }
];
