export type PricingTier = "Free" | "Freemium" | "Paid" | "Open Source";

export type ToolCategory =
  | "SEO"
  | "Paid Advertising"
  | "Content Marketing"
  | "Email & CRM"
  | "Analytics"
  | "Social Media"
  | "CRO & Testing"
  | "Design & Brand"
  | "AI Marketing"
  | "Marketing Automation"
  | "Video & Podcast";

export type MarketingTool = {
  name: string;
  description: string;
  category: ToolCategory;
  pricing: PricingTier;
  url: string;
  emoji: string;
  tags: string[];
  popular?: boolean;
  note?: string;
};

export const TOOLS: MarketingTool[] = [
  // ── SEO ──────────────────────────────────────────────────────────────────
  {
    name: "Google Search Console",
    description: "Monitor your site's presence in Google Search results, track clicks and impressions, and fix indexing issues.",
    category: "SEO",
    pricing: "Free",
    url: "https://search.google.com/search-console",
    emoji: "🔍",
    tags: ["search", "analytics", "google"],
    popular: true,
  },
  {
    name: "Google Keyword Planner",
    description: "Research keywords and get search volume estimates directly from Google's advertising data.",
    category: "SEO",
    pricing: "Free",
    url: "https://ads.google.com/home/tools/keyword-planner/",
    emoji: "🔑",
    tags: ["keywords", "google", "research"],
  },
  {
    name: "Ahrefs",
    description: "All-in-one SEO platform for backlink analysis, keyword research, site audits, and competitor intelligence.",
    category: "SEO",
    pricing: "Paid",
    url: "https://ahrefs.com",
    emoji: "🕷️",
    tags: ["backlinks", "keywords", "site audit"],
    popular: true,
  },
  {
    name: "SEMrush",
    description: "Comprehensive SEO and competitive research suite covering keywords, backlinks, PPC, and content marketing.",
    category: "SEO",
    pricing: "Freemium",
    url: "https://semrush.com",
    emoji: "📊",
    tags: ["keywords", "competitive research", "backlinks"],
    popular: true,
  },
  {
    name: "Moz Pro",
    description: "SEO toolset with domain authority metrics, keyword explorer, rank tracking, and site crawl.",
    category: "SEO",
    pricing: "Freemium",
    url: "https://moz.com/products/pro",
    emoji: "📈",
    tags: ["domain authority", "rank tracking", "site audit"],
  },
  {
    name: "Screaming Frog SEO Spider",
    description: "Desktop crawler that audits websites for broken links, redirects, duplicate content, and on-page SEO issues.",
    category: "SEO",
    pricing: "Freemium",
    url: "https://www.screamingfrog.co.uk/seo-spider/",
    emoji: "🐸",
    tags: ["crawler", "technical SEO", "site audit"],
  },
  {
    name: "Ubersuggest",
    description: "Keyword research and SEO analysis tool with site audit, backlink data, and content ideas.",
    category: "SEO",
    pricing: "Freemium",
    url: "https://neilpatel.com/ubersuggest/",
    emoji: "💡",
    tags: ["keywords", "content ideas", "site audit"],
  },
  {
    name: "Surfer SEO",
    description: "Content optimization tool that uses NLP to help you write pages that rank by analyzing top-ranking competitors.",
    category: "SEO",
    pricing: "Paid",
    url: "https://surferseo.com",
    emoji: "🌊",
    tags: ["content optimization", "NLP", "on-page SEO"],
  },
  {
    name: "Clearscope",
    description: "AI-powered content optimization platform that grades your content against top search results.",
    category: "SEO",
    pricing: "Paid",
    url: "https://clearscope.io",
    emoji: "🎯",
    tags: ["content optimization", "keyword grading", "NLP"],
  },
  {
    name: "AnswerThePublic",
    description: "Visualizes search questions and phrases people type around any keyword, surfacing content opportunities.",
    category: "SEO",
    pricing: "Freemium",
    url: "https://answerthepublic.com",
    emoji: "❓",
    tags: ["keyword research", "questions", "content ideas"],
  },
  {
    name: "Mangools",
    description: "Suite of five SEO tools including KWFinder, SERPChecker, and LinkMiner at an approachable price.",
    category: "SEO",
    pricing: "Paid",
    url: "https://mangools.com",
    emoji: "🔧",
    tags: ["keywords", "SERP analysis", "backlinks"],
  },
  {
    name: "Rank Math",
    description: "WordPress SEO plugin with schema markup, rank tracking, and advanced on-page optimization built in.",
    category: "SEO",
    pricing: "Freemium",
    url: "https://rankmath.com",
    emoji: "🏆",
    tags: ["WordPress", "on-page SEO", "schema"],
  },
  {
    name: "SE Ranking",
    description: "Cloud-based SEO platform with rank tracking, competitor analysis, website audit, and white-label reporting.",
    category: "SEO",
    pricing: "Freemium",
    url: "https://seranking.com",
    emoji: "📡",
    tags: ["rank tracking", "competitor analysis", "white-label"],
  },

  // ── Paid Advertising ─────────────────────────────────────────────────────
  {
    name: "Google Ads",
    description: "Run search, display, shopping, and YouTube ad campaigns across Google's massive network.",
    category: "Paid Advertising",
    pricing: "Free",
    url: "https://ads.google.com",
    emoji: "🎯",
    tags: ["search ads", "display ads", "PPC"],
    popular: true,
    note: "Free to use; you pay for ad spend",
  },
  {
    name: "Meta Ads Manager",
    description: "Create and manage ad campaigns across Facebook, Instagram, Messenger, and the Audience Network.",
    category: "Paid Advertising",
    pricing: "Free",
    url: "https://www.facebook.com/business/tools/ads-manager",
    emoji: "📘",
    tags: ["Facebook", "Instagram", "social ads"],
    popular: true,
    note: "Free to use; you pay for ad spend",
  },
  {
    name: "Microsoft Advertising",
    description: "Run PPC campaigns on Bing, Yahoo, and DuckDuckGo, often with lower CPCs than Google.",
    category: "Paid Advertising",
    pricing: "Free",
    url: "https://ads.microsoft.com",
    emoji: "🪟",
    tags: ["Bing ads", "PPC", "search"],
    note: "Free to use; you pay for ad spend",
  },
  {
    name: "LinkedIn Campaign Manager",
    description: "B2B-focused ad platform for reaching professionals by job title, company, industry, and seniority.",
    category: "Paid Advertising",
    pricing: "Free",
    url: "https://business.linkedin.com/marketing-solutions/ads",
    emoji: "💼",
    tags: ["B2B", "LinkedIn", "sponsored content"],
    note: "Free to use; you pay for ad spend",
  },
  {
    name: "TikTok Ads",
    description: "Reach TikTok's massive Gen Z and millennial audience with in-feed, brand takeover, and TopView ads.",
    category: "Paid Advertising",
    pricing: "Free",
    url: "https://ads.tiktok.com",
    emoji: "🎵",
    tags: ["short video", "Gen Z", "brand awareness"],
    note: "Free to use; you pay for ad spend",
  },
  {
    name: "Triple Whale",
    description: "Ecommerce analytics and attribution platform that consolidates ad performance data across all channels.",
    category: "Paid Advertising",
    pricing: "Paid",
    url: "https://triplewhale.com",
    emoji: "🐋",
    tags: ["ecommerce", "attribution", "ROAS"],
    popular: true,
  },
  {
    name: "Optmyzr",
    description: "PPC management platform that automates bid adjustments, budget pacing, and reporting for Google and Microsoft Ads.",
    category: "Paid Advertising",
    pricing: "Paid",
    url: "https://optmyzr.com",
    emoji: "⚡",
    tags: ["PPC automation", "bid management", "reporting"],
  },
  {
    name: "AdCreative.ai",
    description: "AI-powered platform that generates high-performing ad creatives and copy for Facebook, Google, and more.",
    category: "Paid Advertising",
    pricing: "Freemium",
    url: "https://adcreative.ai",
    emoji: "🤖",
    tags: ["AI ads", "creative", "ad generation"],
  },
  {
    name: "Smartly.io",
    description: "Enterprise social advertising automation platform for creative production, targeting, and bid optimization.",
    category: "Paid Advertising",
    pricing: "Paid",
    url: "https://smartly.io",
    emoji: "🧠",
    tags: ["social ads", "automation", "enterprise"],
  },

  // ── Content Marketing ─────────────────────────────────────────────────────
  {
    name: "WordPress",
    description: "The world's most popular CMS, powering 43% of all websites with thousands of plugins and themes.",
    category: "Content Marketing",
    pricing: "Open Source",
    url: "https://wordpress.org",
    emoji: "📝",
    tags: ["CMS", "blogging", "website"],
    popular: true,
  },
  {
    name: "Webflow",
    description: "No-code web design and CMS platform that gives designers full visual control without writing code.",
    category: "Content Marketing",
    pricing: "Freemium",
    url: "https://webflow.com",
    emoji: "🌐",
    tags: ["no-code", "CMS", "web design"],
  },
  {
    name: "HubSpot CMS",
    description: "Content management system built for marketers, with SEO recommendations, personalization, and A/B testing.",
    category: "Content Marketing",
    pricing: "Freemium",
    url: "https://hubspot.com/products/cms",
    emoji: "🟠",
    tags: ["CMS", "personalization", "inbound marketing"],
  },
  {
    name: "BuzzSumo",
    description: "Content research and monitoring tool that shows what content performs best for any topic or competitor.",
    category: "Content Marketing",
    pricing: "Freemium",
    url: "https://buzzsumo.com",
    emoji: "📣",
    tags: ["content research", "influencers", "trending"],
  },
  {
    name: "Contentful",
    description: "Headless CMS that separates content from presentation, enabling omnichannel content delivery via API.",
    category: "Content Marketing",
    pricing: "Freemium",
    url: "https://contentful.com",
    emoji: "📦",
    tags: ["headless CMS", "API-first", "omnichannel"],
  },
  {
    name: "CoSchedule",
    description: "Marketing calendar and workflow platform for planning, publishing, and measuring content campaigns.",
    category: "Content Marketing",
    pricing: "Paid",
    url: "https://coschedule.com",
    emoji: "📅",
    tags: ["editorial calendar", "workflow", "team collaboration"],
  },
  {
    name: "Notion",
    description: "All-in-one workspace for notes, wikis, databases, and project management, popular for content planning.",
    category: "Content Marketing",
    pricing: "Freemium",
    url: "https://notion.so",
    emoji: "📓",
    tags: ["project management", "content planning", "wiki"],
    popular: true,
  },
  {
    name: "StoryChief",
    description: "Multi-channel content publishing platform that lets you write once and distribute to all your channels.",
    category: "Content Marketing",
    pricing: "Paid",
    url: "https://storychief.io",
    emoji: "📖",
    tags: ["multi-channel", "content distribution", "editorial"],
  },
  {
    name: "Sanity",
    description: "Flexible headless CMS with a real-time collaborative editor and a powerful query language (GROQ).",
    category: "Content Marketing",
    pricing: "Freemium",
    url: "https://sanity.io",
    emoji: "🏗️",
    tags: ["headless CMS", "developer-friendly", "structured content"],
  },
  {
    name: "Frase",
    description: "AI content tool that researches, outlines, and optimizes long-form SEO content in one workflow.",
    category: "Content Marketing",
    pricing: "Paid",
    url: "https://frase.io",
    emoji: "📑",
    tags: ["AI writing", "SEO content", "research"],
  },

  // ── Email & CRM ───────────────────────────────────────────────────────────
  {
    name: "Mailchimp",
    description: "Email marketing platform and marketing automation suite used by over 13 million businesses worldwide.",
    category: "Email & CRM",
    pricing: "Freemium",
    url: "https://mailchimp.com",
    emoji: "🐵",
    tags: ["email marketing", "automation", "audience"],
    popular: true,
  },
  {
    name: "ConvertKit",
    description: "Creator-focused email platform with visual automations, landing pages, and commerce features.",
    category: "Email & CRM",
    pricing: "Freemium",
    url: "https://convertkit.com",
    emoji: "✉️",
    tags: ["creators", "email sequences", "landing pages"],
    popular: true,
    note: "Now rebranding as Kit",
  },
  {
    name: "Klaviyo",
    description: "Ecommerce-first email and SMS platform with deep Shopify integration and predictive analytics.",
    category: "Email & CRM",
    pricing: "Freemium",
    url: "https://klaviyo.com",
    emoji: "💌",
    tags: ["ecommerce", "SMS", "Shopify"],
    popular: true,
  },
  {
    name: "ActiveCampaign",
    description: "Customer experience automation platform combining email, CRM, and advanced behavioral automations.",
    category: "Email & CRM",
    pricing: "Paid",
    url: "https://activecampaign.com",
    emoji: "⚡",
    tags: ["automation", "CRM", "behavioral triggers"],
    popular: true,
  },
  {
    name: "Brevo",
    description: "Multi-channel marketing platform with email, SMS, WhatsApp, and live chat, formerly Sendinblue.",
    category: "Email & CRM",
    pricing: "Freemium",
    url: "https://brevo.com",
    emoji: "📬",
    tags: ["email", "SMS", "WhatsApp"],
    note: "Formerly Sendinblue",
  },
  {
    name: "Beehiiv",
    description: "Newsletter platform built by ex-Morning Brew team, with monetization, referral programs, and analytics.",
    category: "Email & CRM",
    pricing: "Freemium",
    url: "https://beehiiv.com",
    emoji: "🐝",
    tags: ["newsletter", "monetization", "referral"],
  },
  {
    name: "Drip",
    description: "Ecommerce CRM and email platform with revenue-attributed reporting and smart segmentation.",
    category: "Email & CRM",
    pricing: "Paid",
    url: "https://drip.com",
    emoji: "💧",
    tags: ["ecommerce CRM", "segmentation", "revenue tracking"],
  },
  {
    name: "Customer.io",
    description: "Behavioral messaging platform that sends the right message on the right channel based on user actions.",
    category: "Email & CRM",
    pricing: "Paid",
    url: "https://customer.io",
    emoji: "🎯",
    tags: ["behavioral email", "multi-channel", "product-led"],
  },
  {
    name: "HubSpot CRM",
    description: "Free CRM that integrates with HubSpot's marketing, sales, and service hubs for a full customer view.",
    category: "Email & CRM",
    pricing: "Freemium",
    url: "https://hubspot.com/products/crm",
    emoji: "🟠",
    tags: ["CRM", "sales pipeline", "contact management"],
    popular: true,
  },
  {
    name: "Substack",
    description: "Newsletter publishing platform where writers can build a paid subscriber base with no upfront cost.",
    category: "Email & CRM",
    pricing: "Free",
    url: "https://substack.com",
    emoji: "📰",
    tags: ["newsletter", "paid subscriptions", "publishing"],
    note: "Free to publish; Substack takes 10% of paid subscriptions",
  },
  {
    name: "MailerLite",
    description: "Simple, affordable email marketing tool with landing pages, pop-ups, and automation for small businesses.",
    category: "Email & CRM",
    pricing: "Freemium",
    url: "https://mailerlite.com",
    emoji: "💚",
    tags: ["email marketing", "landing pages", "small business"],
  },
  {
    name: "Salesforce Marketing Cloud",
    description: "Enterprise-grade digital marketing platform for personalized journeys across email, mobile, and social.",
    category: "Email & CRM",
    pricing: "Paid",
    url: "https://salesforce.com/products/marketing-cloud",
    emoji: "☁️",
    tags: ["enterprise", "journey builder", "CDP"],
  },

  // ── Analytics ─────────────────────────────────────────────────────────────
  {
    name: "Google Analytics 4",
    description: "Google's next-generation analytics platform with event-based tracking, predictive metrics, and BigQuery export.",
    category: "Analytics",
    pricing: "Free",
    url: "https://analytics.google.com",
    emoji: "📊",
    tags: ["web analytics", "events", "google"],
    popular: true,
  },
  {
    name: "Mixpanel",
    description: "Product analytics platform for tracking user behavior, funnels, retention, and A/B test results.",
    category: "Analytics",
    pricing: "Freemium",
    url: "https://mixpanel.com",
    emoji: "🔬",
    tags: ["product analytics", "funnels", "retention"],
    popular: true,
  },
  {
    name: "Amplitude",
    description: "Digital analytics platform focused on product intelligence, behavioral cohorts, and experimentation.",
    category: "Analytics",
    pricing: "Freemium",
    url: "https://amplitude.com",
    emoji: "📡",
    tags: ["product analytics", "cohorts", "experimentation"],
    popular: true,
  },
  {
    name: "Hotjar",
    description: "Heatmaps, session recordings, and surveys that reveal how real users experience your website.",
    category: "Analytics",
    pricing: "Freemium",
    url: "https://hotjar.com",
    emoji: "🔥",
    tags: ["heatmaps", "recordings", "user research"],
    popular: true,
  },
  {
    name: "Segment",
    description: "Customer Data Platform that collects, cleans, and routes customer data to 300+ marketing tools.",
    category: "Analytics",
    pricing: "Freemium",
    url: "https://segment.com",
    emoji: "🔀",
    tags: ["CDP", "data pipeline", "integrations"],
    popular: true,
  },
  {
    name: "PostHog",
    description: "Open-source product analytics, session recording, feature flags, and A/B testing in one self-hostable platform.",
    category: "Analytics",
    pricing: "Open Source",
    url: "https://posthog.com",
    emoji: "🦔",
    tags: ["product analytics", "self-hosted", "feature flags"],
  },
  {
    name: "Plausible",
    description: "Lightweight, privacy-first web analytics that is GDPR compliant with no cookies required.",
    category: "Analytics",
    pricing: "Paid",
    url: "https://plausible.io",
    emoji: "🌿",
    tags: ["privacy-first", "lightweight", "GDPR"],
  },
  {
    name: "Heap",
    description: "Auto-captures every user interaction so you can retroactively analyze behavior without pre-defining events.",
    category: "Analytics",
    pricing: "Freemium",
    url: "https://heap.io",
    emoji: "🗂️",
    tags: ["autocapture", "retroactive analysis", "funnels"],
  },
  {
    name: "Fathom Analytics",
    description: "Simple, privacy-focused web analytics that is cookieless and GDPR/CCPA compliant by default.",
    category: "Analytics",
    pricing: "Paid",
    url: "https://usefathom.com",
    emoji: "🏔️",
    tags: ["privacy-first", "cookieless", "simple"],
  },
  {
    name: "Looker Studio",
    description: "Free Google tool for building interactive dashboards and reports from GA4, Sheets, BigQuery, and 800+ connectors.",
    category: "Analytics",
    pricing: "Free",
    url: "https://lookerstudio.google.com",
    emoji: "📈",
    tags: ["dashboards", "google", "reporting"],
  },
  {
    name: "Databox",
    description: "Business analytics platform that pulls KPIs from 70+ integrations into one real-time performance dashboard.",
    category: "Analytics",
    pricing: "Freemium",
    url: "https://databox.com",
    emoji: "📦",
    tags: ["dashboards", "KPIs", "reporting"],
  },

  // ── Social Media ──────────────────────────────────────────────────────────
  {
    name: "Buffer",
    description: "Social media scheduling and analytics tool known for its clean interface and straightforward pricing.",
    category: "Social Media",
    pricing: "Freemium",
    url: "https://buffer.com",
    emoji: "🟦",
    tags: ["scheduling", "analytics", "multi-channel"],
    popular: true,
  },
  {
    name: "Hootsuite",
    description: "Enterprise social media management platform with scheduling, social listening, and team collaboration.",
    category: "Social Media",
    pricing: "Paid",
    url: "https://hootsuite.com",
    emoji: "🦉",
    tags: ["scheduling", "social listening", "enterprise"],
  },
  {
    name: "Later",
    description: "Visual social media planner focused on Instagram, with drag-and-drop calendar and link-in-bio tool.",
    category: "Social Media",
    pricing: "Freemium",
    url: "https://later.com",
    emoji: "📸",
    tags: ["Instagram", "visual planner", "link in bio"],
  },
  {
    name: "Sprout Social",
    description: "All-in-one social media management with publishing, engagement, analytics, and listening tools.",
    category: "Social Media",
    pricing: "Paid",
    url: "https://sproutsocial.com",
    emoji: "🌱",
    tags: ["publishing", "social listening", "analytics"],
    popular: true,
  },
  {
    name: "Metricool",
    description: "Social media scheduling and analytics tool that also covers Google Ads, Facebook Ads, and website traffic.",
    category: "Social Media",
    pricing: "Freemium",
    url: "https://metricool.com",
    emoji: "📊",
    tags: ["scheduling", "analytics", "ads reporting"],
  },
  {
    name: "Publer",
    description: "Multi-platform scheduling tool with AI writing assistant, link-in-bio, and team workflow features.",
    category: "Social Media",
    pricing: "Freemium",
    url: "https://publer.io",
    emoji: "📢",
    tags: ["scheduling", "AI writing", "team collaboration"],
  },
  {
    name: "Loomly",
    description: "Brand success platform with post ideas, scheduling, approvals, and paid promotion management.",
    category: "Social Media",
    pricing: "Paid",
    url: "https://loomly.com",
    emoji: "📅",
    tags: ["scheduling", "approvals", "brand management"],
  },
  {
    name: "Canva for Social",
    description: "Design-first social media tool with templates for every platform, scheduling, and brand kit management.",
    category: "Social Media",
    pricing: "Freemium",
    url: "https://canva.com",
    emoji: "🎨",
    tags: ["design", "templates", "scheduling"],
  },
  {
    name: "Brandwatch",
    description: "Enterprise social listening and consumer intelligence platform for tracking brand mentions at scale.",
    category: "Social Media",
    pricing: "Paid",
    url: "https://brandwatch.com",
    emoji: "👁️",
    tags: ["social listening", "brand monitoring", "enterprise"],
  },

  // ── CRO & Testing ─────────────────────────────────────────────────────────
  {
    name: "Hotjar (CRO)",
    description: "Heatmaps, session recordings, and on-site surveys that diagnose conversion blockers on your pages.",
    category: "CRO & Testing",
    pricing: "Freemium",
    url: "https://hotjar.com",
    emoji: "🔥",
    tags: ["heatmaps", "recordings", "feedback"],
    popular: true,
  },
  {
    name: "Crazy Egg",
    description: "Visual analytics tool offering heatmaps, scroll maps, A/B testing, and traffic analysis for CRO.",
    category: "CRO & Testing",
    pricing: "Paid",
    url: "https://crazyegg.com",
    emoji: "🥚",
    tags: ["heatmaps", "scroll maps", "A/B testing"],
  },
  {
    name: "VWO",
    description: "Full-stack experimentation platform with A/B testing, multivariate testing, heatmaps, and personalization.",
    category: "CRO & Testing",
    pricing: "Paid",
    url: "https://vwo.com",
    emoji: "🧪",
    tags: ["A/B testing", "personalization", "multivariate"],
    popular: true,
  },
  {
    name: "Optimizely",
    description: "Enterprise digital experimentation platform for A/B testing on web, mobile, and server-side.",
    category: "CRO & Testing",
    pricing: "Paid",
    url: "https://optimizely.com",
    emoji: "⚗️",
    tags: ["experimentation", "A/B testing", "feature flags"],
    popular: true,
  },
  {
    name: "Unbounce",
    description: "Landing page builder and A/B testing platform with AI-powered traffic optimization.",
    category: "CRO & Testing",
    pricing: "Paid",
    url: "https://unbounce.com",
    emoji: "🚀",
    tags: ["landing pages", "A/B testing", "AI optimization"],
  },
  {
    name: "Instapage",
    description: "Post-click optimization platform with advanced landing page builder, heatmaps, and collaboration tools.",
    category: "CRO & Testing",
    pricing: "Paid",
    url: "https://instapage.com",
    emoji: "📄",
    tags: ["landing pages", "personalization", "analytics"],
  },
  {
    name: "Leadpages",
    description: "Beginner-friendly landing page and website builder designed to convert traffic into leads and sales.",
    category: "CRO & Testing",
    pricing: "Paid",
    url: "https://leadpages.com",
    emoji: "🎯",
    tags: ["landing pages", "lead capture", "small business"],
  },
  {
    name: "AB Tasty",
    description: "Feature experimentation and personalization platform for web and mobile with audience targeting.",
    category: "CRO & Testing",
    pricing: "Paid",
    url: "https://abtasty.com",
    emoji: "🍬",
    tags: ["A/B testing", "personalization", "experimentation"],
  },
  {
    name: "Convert.com",
    description: "GDPR-compliant A/B testing platform with advanced targeting, multi-page experiments, and integrations.",
    category: "CRO & Testing",
    pricing: "Paid",
    url: "https://convert.com",
    emoji: "🔄",
    tags: ["A/B testing", "GDPR", "privacy-focused"],
  },

  // ── Design & Brand ────────────────────────────────────────────────────────
  {
    name: "Canva",
    description: "Online graphic design platform with 250,000+ templates for social posts, presentations, videos, and more.",
    category: "Design & Brand",
    pricing: "Freemium",
    url: "https://canva.com",
    emoji: "🎨",
    tags: ["templates", "design", "brand kit"],
    popular: true,
  },
  {
    name: "Figma",
    description: "Collaborative interface design tool for UI, branding, and prototyping used by design teams worldwide.",
    category: "Design & Brand",
    pricing: "Freemium",
    url: "https://figma.com",
    emoji: "✏️",
    tags: ["UI design", "prototyping", "collaboration"],
    popular: true,
  },
  {
    name: "Adobe Express",
    description: "Quick, template-driven design tool from Adobe for creating social graphics, flyers, and short videos.",
    category: "Design & Brand",
    pricing: "Freemium",
    url: "https://www.adobe.com/express/",
    emoji: "🅰️",
    tags: ["templates", "quick design", "Adobe"],
  },
  {
    name: "Midjourney",
    description: "AI image generation tool known for photorealistic and artistic image quality, used via Discord.",
    category: "Design & Brand",
    pricing: "Paid",
    url: "https://midjourney.com",
    emoji: "🖼️",
    tags: ["AI image generation", "art", "branding"],
    popular: true,
  },
  {
    name: "Loom",
    description: "Screen and camera recording tool for creating quick video messages, tutorials, and product demos.",
    category: "Design & Brand",
    pricing: "Freemium",
    url: "https://loom.com",
    emoji: "🎬",
    tags: ["screen recording", "video", "async communication"],
    popular: true,
  },
  {
    name: "Visme",
    description: "Visual content creation platform for infographics, presentations, reports, and data visualizations.",
    category: "Design & Brand",
    pricing: "Freemium",
    url: "https://visme.co",
    emoji: "📊",
    tags: ["infographics", "presentations", "data visualization"],
  },
  {
    name: "DALL-E",
    description: "OpenAI's image generation model accessible via ChatGPT and the API for marketing visuals and concepts.",
    category: "Design & Brand",
    pricing: "Freemium",
    url: "https://openai.com/dall-e-3",
    emoji: "🤖",
    tags: ["AI image generation", "OpenAI", "concepts"],
  },
  {
    name: "Looka",
    description: "AI-powered logo maker and brand identity platform that generates brand kits from your preferences.",
    category: "Design & Brand",
    pricing: "Paid",
    url: "https://looka.com",
    emoji: "✨",
    tags: ["logo design", "brand identity", "AI"],
  },
  {
    name: "Piktochart",
    description: "Infographic and visual storytelling tool for creating reports, presentations, and social graphics.",
    category: "Design & Brand",
    pricing: "Freemium",
    url: "https://piktochart.com",
    emoji: "📊",
    tags: ["infographics", "reports", "data storytelling"],
  },

  // ── AI Marketing ──────────────────────────────────────────────────────────
  {
    name: "ChatGPT",
    description: "OpenAI's conversational AI used by marketers for copywriting, brainstorming, research, and content drafting.",
    category: "AI Marketing",
    pricing: "Freemium",
    url: "https://chatgpt.com",
    emoji: "💬",
    tags: ["AI writing", "copywriting", "brainstorming"],
    popular: true,
  },
  {
    name: "Claude",
    description: "Anthropic's AI assistant with strong reasoning and long-context understanding, great for nuanced marketing content.",
    category: "AI Marketing",
    pricing: "Freemium",
    url: "https://claude.ai",
    emoji: "🧠",
    tags: ["AI writing", "reasoning", "long-form content"],
    popular: true,
  },
  {
    name: "Jasper",
    description: "AI writing platform purpose-built for marketing teams, with brand voice controls and campaign workflows.",
    category: "AI Marketing",
    pricing: "Paid",
    url: "https://jasper.ai",
    emoji: "✍️",
    tags: ["AI writing", "copywriting", "brand voice"],
    popular: true,
  },
  {
    name: "Copy.ai",
    description: "AI content platform with 90+ templates for ad copy, emails, blog posts, and social captions.",
    category: "AI Marketing",
    pricing: "Freemium",
    url: "https://copy.ai",
    emoji: "✨",
    tags: ["AI copy", "templates", "marketing"],
  },
  {
    name: "Writesonic",
    description: "AI writing and SEO tool that creates blog posts, ads, landing pages, and chatbots from prompts.",
    category: "AI Marketing",
    pricing: "Freemium",
    url: "https://writesonic.com",
    emoji: "⚡",
    tags: ["AI writing", "SEO content", "chatbot"],
  },
  {
    name: "Perplexity",
    description: "AI-powered search engine that cites sources, useful for real-time market research and fact-checking.",
    category: "AI Marketing",
    pricing: "Freemium",
    url: "https://perplexity.ai",
    emoji: "🔍",
    tags: ["AI search", "research", "cited sources"],
  },
  {
    name: "GrowthBar",
    description: "AI SEO tool that combines keyword research, competitor analysis, and AI blog post generation.",
    category: "AI Marketing",
    pricing: "Paid",
    url: "https://growthbarseo.com",
    emoji: "📈",
    tags: ["AI SEO", "blog writing", "keywords"],
  },
  {
    name: "Surfer AI",
    description: "Surfer SEO's AI writing feature that produces fully optimized, long-form articles ready to rank.",
    category: "AI Marketing",
    pricing: "Paid",
    url: "https://surferseo.com/ai-article-writer/",
    emoji: "🌊",
    tags: ["AI content", "SEO writing", "NLP"],
  },
  {
    name: "Runway",
    description: "AI-powered video generation and editing platform for creating cinematic content from text or images.",
    category: "AI Marketing",
    pricing: "Freemium",
    url: "https://runwayml.com",
    emoji: "🎬",
    tags: ["AI video", "video generation", "creative"],
  },
  {
    name: "ElevenLabs",
    description: "AI voice synthesis platform for generating realistic voiceovers for ads, podcasts, and video content.",
    category: "AI Marketing",
    pricing: "Freemium",
    url: "https://elevenlabs.io",
    emoji: "🎙️",
    tags: ["AI voice", "text-to-speech", "voiceover"],
    popular: true,
  },
  {
    name: "Synthesia",
    description: "AI video platform that creates professional talking-head videos with AI avatars, no camera needed.",
    category: "AI Marketing",
    pricing: "Paid",
    url: "https://synthesia.io",
    emoji: "🎥",
    tags: ["AI video", "avatars", "video production"],
  },
  {
    name: "HeyGen",
    description: "AI video generator for creating personalized marketing videos with realistic AI avatars at scale.",
    category: "AI Marketing",
    pricing: "Freemium",
    url: "https://heygen.com",
    emoji: "🙋",
    tags: ["AI video", "personalization", "avatars"],
  },

  // ── Marketing Automation ──────────────────────────────────────────────────
  {
    name: "HubSpot Marketing Hub",
    description: "All-in-one inbound marketing platform with email, landing pages, workflows, and CRM integration.",
    category: "Marketing Automation",
    pricing: "Freemium",
    url: "https://hubspot.com/products/marketing",
    emoji: "🟠",
    tags: ["inbound marketing", "workflows", "lead nurturing"],
    popular: true,
  },
  {
    name: "Zapier",
    description: "No-code automation tool that connects 6,000+ apps to automate repetitive marketing tasks.",
    category: "Marketing Automation",
    pricing: "Freemium",
    url: "https://zapier.com",
    emoji: "⚡",
    tags: ["no-code", "integrations", "workflow automation"],
    popular: true,
  },
  {
    name: "Make",
    description: "Visual automation platform (formerly Integromat) with more complex logic and lower cost than Zapier.",
    category: "Marketing Automation",
    pricing: "Freemium",
    url: "https://make.com",
    emoji: "🔧",
    tags: ["visual automation", "integrations", "no-code"],
    note: "Formerly Integromat",
  },
  {
    name: "n8n",
    description: "Open-source workflow automation tool you can self-host, with 400+ integrations and custom code support.",
    category: "Marketing Automation",
    pricing: "Open Source",
    url: "https://n8n.io",
    emoji: "🔀",
    tags: ["self-hosted", "automation", "open source"],
  },
  {
    name: "Marketo",
    description: "Adobe's enterprise marketing automation platform for lead management, email, and account-based marketing.",
    category: "Marketing Automation",
    pricing: "Paid",
    url: "https://business.adobe.com/products/marketo/adobe-marketo.html",
    emoji: "🎯",
    tags: ["enterprise", "lead management", "ABM"],
  },
  {
    name: "Pardot",
    description: "Salesforce's B2B marketing automation platform for demand generation, lead scoring, and nurturing.",
    category: "Marketing Automation",
    pricing: "Paid",
    url: "https://salesforce.com/products/marketing/b2b-marketing-automation/",
    emoji: "🌩️",
    tags: ["B2B", "Salesforce", "lead scoring"],
  },
  {
    name: "Klaviyo Flows",
    description: "Klaviyo's visual automation builder for triggered email and SMS sequences based on customer behavior.",
    category: "Marketing Automation",
    pricing: "Freemium",
    url: "https://klaviyo.com/features/flows",
    emoji: "💌",
    tags: ["ecommerce automation", "email flows", "SMS"],
  },
  {
    name: "Ortto",
    description: "Customer journey automation platform with a visual canvas, data activation, and built-in analytics.",
    category: "Marketing Automation",
    pricing: "Paid",
    url: "https://ortto.com",
    emoji: "🗺️",
    tags: ["journey builder", "CDP", "analytics"],
    note: "Formerly Autopilot",
  },

  // ── Video & Podcast ───────────────────────────────────────────────────────
  {
    name: "Loom (Video)",
    description: "Async video messaging for sharing product walkthroughs, feedback, and team updates. Watch rates beat email.",
    category: "Video & Podcast",
    pricing: "Freemium",
    url: "https://loom.com",
    emoji: "🎬",
    tags: ["screen recording", "async video", "tutorials"],
    popular: true,
  },
  {
    name: "Vidyard",
    description: "B2B video platform for hosting, personalizing, and tracking video performance across the sales funnel.",
    category: "Video & Podcast",
    pricing: "Freemium",
    url: "https://vidyard.com",
    emoji: "📹",
    tags: ["B2B video", "video analytics", "personalization"],
  },
  {
    name: "Wistia",
    description: "Video hosting platform for marketers with lead capture, heatmaps, and A/B testing built in.",
    category: "Video & Podcast",
    pricing: "Freemium",
    url: "https://wistia.com",
    emoji: "🎥",
    tags: ["video hosting", "lead capture", "analytics"],
  },
  {
    name: "Descript",
    description: "Podcast and video editor where you edit media by editing the transcript. Includes AI voice cloning.",
    category: "Video & Podcast",
    pricing: "Freemium",
    url: "https://descript.com",
    emoji: "✂️",
    tags: ["podcast editing", "video editing", "transcription"],
    popular: true,
  },
  {
    name: "Riverside.fm",
    description: "Remote recording studio for podcasts and video interviews with 4K local recording and live streaming.",
    category: "Video & Podcast",
    pricing: "Freemium",
    url: "https://riverside.fm",
    emoji: "🎙️",
    tags: ["podcast recording", "remote", "high quality"],
  },
  {
    name: "Buzzsprout",
    description: "Podcast hosting platform with easy distribution to all major directories, analytics, and monetization.",
    category: "Video & Podcast",
    pricing: "Freemium",
    url: "https://buzzsprout.com",
    emoji: "🎧",
    tags: ["podcast hosting", "distribution", "analytics"],
  },
  {
    name: "Spotify for Podcasters",
    description: "Free podcast hosting and analytics from Spotify with direct access to Spotify's 600M+ listener base.",
    category: "Video & Podcast",
    pricing: "Free",
    url: "https://podcasters.spotify.com",
    emoji: "🟢",
    tags: ["podcast hosting", "Spotify", "distribution"],
  },
  {
    name: "Transistor",
    description: "Professional podcast hosting with unlimited shows per account, private podcasts, and team features.",
    category: "Video & Podcast",
    pricing: "Paid",
    url: "https://transistor.fm",
    emoji: "📡",
    tags: ["podcast hosting", "team", "private podcasts"],
  },
  {
    name: "Opus Clip",
    description: "AI-powered tool that automatically clips long videos into short-form highlights for TikTok and Reels.",
    category: "Video & Podcast",
    pricing: "Freemium",
    url: "https://opus.pro",
    emoji: "🎞️",
    tags: ["AI video", "short-form", "repurposing"],
  },
];

export const TOOL_CATEGORIES: ToolCategory[] = [
  "SEO",
  "Paid Advertising",
  "Content Marketing",
  "Email & CRM",
  "Analytics",
  "Social Media",
  "CRO & Testing",
  "Design & Brand",
  "AI Marketing",
  "Marketing Automation",
  "Video & Podcast",
];

export const PRICING_TIERS: PricingTier[] = [
  "Free",
  "Freemium",
  "Paid",
  "Open Source",
];
