export type Track = {
  slug: string;
  title: string;
  emoji: string;
  description: string;
  audience: string;
  duration: string;
  lessons: { category: string; slug: string; title: string }[];
};

export const TRACKS: Track[] = [
  {
    slug: "b2b-marketer",
    title: "B2B Marketing Track",
    emoji: "🏢",
    description:
      "Master the full B2B go-to-market stack: positioning, pipeline, content, email lifecycle, attribution, and product marketing. Built for marketers selling to businesses.",
    audience: "B2B Marketers",
    duration: "18-22 hours",
    lessons: [
      { category: "fundamentals", slug: "what-is-marketing", title: "What Marketing Actually Is" },
      { category: "fundamentals", slug: "stp", title: "Segmentation, Targeting, Positioning" },
      { category: "fundamentals", slug: "value-proposition", title: "The Value Proposition" },
      { category: "fundamentals", slug: "buyer-personas", title: "Buyer Personas (without the fluff)" },
      { category: "fundamentals", slug: "positioning", title: "Positioning" },
      { category: "fundamentals", slug: "customer-journey", title: "The Customer Journey" },
      { category: "mental-models", slug: "first-principles-thinking", title: "First-Principles Thinking" },
      { category: "mental-models", slug: "second-order-thinking", title: "Second-Order Thinking" },
      { category: "mental-models", slug: "base-rates-forecasting", title: "Base Rates and Reference-Class Forecasting" },
      { category: "product-marketing", slug: "pmm-101", title: "Product Marketing 101" },
      { category: "product-marketing", slug: "icp", title: "Ideal Customer Profile (ICP)" },
      { category: "product-marketing", slug: "positioning-doc", title: "The Positioning Doc" },
      { category: "product-marketing", slug: "messaging-hierarchy", title: "Messaging Hierarchy" },
      { category: "product-marketing", slug: "launches", title: "Product Launches" },
      { category: "content", slug: "content-strategy", title: "Content Strategy" },
      { category: "content", slug: "case-studies", title: "Case Studies" },
      { category: "content", slug: "webinars", title: "Webinars and Live Content" },
      { category: "email", slug: "automation-flows", title: "Automation & Drip Flows" },
      { category: "email", slug: "cold-email", title: "Cold Email" },
      { category: "analytics", slug: "analytics-101", title: "Analytics 101" },
      { category: "analytics", slug: "attribution", title: "Attribution Models" },
    ],
  },
  {
    slug: "ecommerce-growth",
    title: "E-commerce Growth Track",
    emoji: "🛒",
    description:
      "The full paid-to-owned playbook for e-commerce: Google Shopping, Meta ads, abandoned cart flows, retention, CRO, and analytics. Grow revenue from every part of the funnel.",
    audience: "E-commerce Marketers",
    duration: "15-18 hours",
    lessons: [
      { category: "paid-ads", slug: "paid-ads-101", title: "Paid Ads 101" },
      { category: "paid-ads", slug: "google-search-ads", title: "Google Search Ads" },
      { category: "paid-ads", slug: "meta-ads", title: "Meta Ads (Facebook & Instagram)" },
      { category: "paid-ads", slug: "google-shopping-pmax", title: "Google Shopping & Performance Max" },
      { category: "paid-ads", slug: "retargeting", title: "Retargeting" },
      { category: "paid-ads", slug: "creative-testing", title: "Creative Testing" },
      { category: "email", slug: "email-marketing-101", title: "Email Marketing 101" },
      { category: "email", slug: "abandon-cart", title: "Abandoned Cart & Browse Flows" },
      { category: "email", slug: "reengagement", title: "Win-back Campaigns" },
      { category: "email", slug: "rfm", title: "RFM Segmentation" },
      { category: "growth", slug: "aarrr", title: "AARRR: Pirate Metrics" },
      { category: "growth", slug: "retention-cohorts", title: "Retention & Cohort Analysis" },
      { category: "growth", slug: "ab-testing", title: "A/B Testing & Statistical Significance" },
      { category: "cro", slug: "cro-101", title: "CRO 101" },
      { category: "cro", slug: "landing-page-anatomy", title: "Landing Page Anatomy" },
      { category: "cro", slug: "checkout-optimization", title: "Checkout Optimization" },
      { category: "analytics", slug: "utm-tagging", title: "UTM Tagging" },
      { category: "analytics", slug: "funnel-analysis", title: "Funnel Analytics" },
    ],
  },
  {
    slug: "solo-founder",
    title: "Solo Founder Track",
    emoji: "🚀",
    description:
      "The lean marketing stack for founders doing it all themselves. Skip the fluff, learn the fundamentals that actually drive early traction, and build a repeatable growth system.",
    audience: "Solo Founders",
    duration: "14-17 hours",
    lessons: [
      { category: "fundamentals", slug: "what-is-marketing", title: "What Marketing Actually Is" },
      { category: "fundamentals", slug: "value-proposition", title: "The Value Proposition" },
      { category: "fundamentals", slug: "marketing-math", title: "Marketing Math: CAC, LTV, ROAS, Payback" },
      { category: "fundamentals", slug: "product-market-fit", title: "Product-Market Fit" },
      { category: "mental-models", slug: "first-principles-thinking", title: "First-Principles Thinking" },
      { category: "mental-models", slug: "opportunity-cost-thinking", title: "Opportunity Cost Thinking" },
      { category: "mental-models", slug: "writing-to-think", title: "Writing to Think" },
      { category: "seo", slug: "keyword-research", title: "Keyword Research" },
      { category: "seo", slug: "on-page-seo", title: "On-Page SEO" },
      { category: "content", slug: "what-is-content-marketing", title: "What Content Marketing Really Is" },
      { category: "content", slug: "content-strategy", title: "Content Strategy" },
      { category: "email", slug: "email-marketing-101", title: "Email Marketing 101" },
      { category: "email", slug: "welcome-series", title: "The Welcome Series" },
      { category: "copywriting", slug: "copywriting-101", title: "Copywriting 101" },
      { category: "copywriting", slug: "headlines", title: "Headline Writing" },
      { category: "growth", slug: "what-is-growth", title: "What Growth Marketing Really Is" },
      { category: "growth", slug: "north-star-metric", title: "The North Star Metric" },
      { category: "analytics", slug: "analytics-101", title: "Analytics 101" },
    ],
  },
  {
    slug: "ai-first-marketer",
    title: "AI-First Marketer Track",
    emoji: "🤖",
    description:
      "Learn how AI is reshaping search, content, and the entire marketing stack. From LLM optimization to AI agents, this track is built for marketers who want to stay ahead of the curve.",
    audience: "AI-Forward Marketers",
    duration: "12-14 hours",
    lessons: [
      { category: "ai-marketing", slug: "ai-marketing-101", title: "AI in Marketing 101" },
      { category: "ai-marketing", slug: "prompt-engineering-marketers", title: "Prompt Engineering for Marketers" },
      { category: "ai-marketing", slug: "ai-content-writing", title: "AI for Content Writing" },
      { category: "ai-marketing", slug: "ai-seo", title: "AI for SEO" },
      { category: "ai-marketing", slug: "ai-email-marketing", title: "AI for Email Marketing" },
      { category: "ai-marketing", slug: "ai-analytics", title: "AI for Analytics & Insights" },
      { category: "ai-marketing", slug: "ai-agents-marketing", title: "AI Agents for Marketing" },
      { category: "ai-marketing", slug: "ai-search-ranking", title: "Ranking Inside AI Answers" },
      { category: "ai-marketing", slug: "rag-for-marketers", title: "RAG for Marketers" },
      { category: "seo", slug: "llmo", title: "LLM Optimization (LLMO)" },
      { category: "seo", slug: "aeo", title: "Answer Engine Optimization (AEO)" },
      { category: "seo", slug: "ai-overviews-geo", title: "AI Overviews & Generative Engine Optimization" },
      { category: "copywriting", slug: "aida-pas-frameworks", title: "AIDA, PAS, and the Core Frameworks" },
      { category: "analytics", slug: "dark-social", title: "Dark Social" },
    ],
  },
  {
    slug: "content-creator",
    title: "Content Creator Track",
    emoji: "✍️",
    description:
      "Build an audience from scratch using content. Covers SEO writing, social media, email list building, copywriting fundamentals, and the tools that let one person produce like a team.",
    audience: "Content Creators",
    duration: "15-18 hours",
    lessons: [
      { category: "content", slug: "what-is-content-marketing", title: "What Content Marketing Really Is" },
      { category: "content", slug: "content-strategy", title: "Content Strategy" },
      { category: "mental-models", slug: "writing-to-think", title: "Writing to Think" },
      { category: "mental-models", slug: "deliberate-practice", title: "Deliberate Practice for Marketers" },
      { category: "seo", slug: "keyword-research", title: "Keyword Research" },
      { category: "seo", slug: "on-page-seo", title: "On-Page SEO" },
      { category: "seo", slug: "content-clusters", title: "Content Clusters and Pillar Pages" },
      { category: "copywriting", slug: "copywriting-101", title: "Copywriting 101" },
      { category: "copywriting", slug: "headlines", title: "Headline Writing" },
      { category: "copywriting", slug: "storytelling-copy", title: "Storytelling in Copy" },
      { category: "email", slug: "email-marketing-101", title: "Email Marketing 101" },
      { category: "email", slug: "welcome-series", title: "The Welcome Series" },
      { category: "email", slug: "subject-lines", title: "Subject Lines" },
      { category: "content", slug: "repurposing", title: "Content Repurposing" },
      { category: "analytics", slug: "analytics-101", title: "Analytics 101" },
      { category: "analytics", slug: "kpis-for-marketers", title: "KPIs for Marketers" },
      { category: "tools", slug: "canva-figma", title: "Canva vs Figma for Marketers" },
      { category: "tools", slug: "ai-tools-overview", title: "AI Tools for Marketers" },
    ],
  },
  {
    slug: "social-media-manager",
    title: "Social Media Manager Track",
    emoji: "📱",
    description:
      "Own the full social media function: platform strategy, content creation, community management, analytics, and paid amplification. Built for anyone managing social at a brand or agency.",
    audience: "Social Media Managers",
    duration: "13-16 hours",
    lessons: [
      { category: "social", slug: "social-strategy-basics", title: "Social Strategy Basics" },
      { category: "social", slug: "instagram", title: "Instagram Playbook" },
      { category: "social", slug: "linkedin", title: "LinkedIn Playbook" },
      { category: "social", slug: "tiktok", title: "TikTok Playbook" },
      { category: "social", slug: "youtube", title: "YouTube Playbook" },
      { category: "social", slug: "community-building", title: "Community Building" },
      { category: "social", slug: "influencer-marketing", title: "Influencer Marketing" },
      { category: "social", slug: "social-listening", title: "Social Listening" },
      { category: "social", slug: "content-calendar", title: "Content Calendar and Scheduling" },
      { category: "content", slug: "repurposing", title: "Content Repurposing" },
      { category: "copywriting", slug: "ad-copy", title: "Ad Copy" },
      { category: "paid-ads", slug: "meta-ads", title: "Meta Ads (Facebook & Instagram)" },
      { category: "analytics", slug: "utm-tagging", title: "UTM Tagging" },
      { category: "tools", slug: "hootsuite-buffer", title: "Hootsuite vs Buffer" },
    ],
  },
  {
    slug: "data-driven-marketer",
    title: "Data-Driven Marketer Track",
    emoji: "📊",
    description:
      "For marketers who want to own the numbers. Covers analytics setup, attribution, experimentation, dashboards, and the measurement frameworks that turn data into decisions.",
    audience: "Analytics-Focused Marketers",
    duration: "16-20 hours",
    lessons: [
      { category: "mental-models", slug: "base-rates-forecasting", title: "Base Rates and Reference-Class Forecasting" },
      { category: "mental-models", slug: "bayesian-updating", title: "Bayesian Updating for Marketers" },
      { category: "mental-models", slug: "goodharts-law", title: "Goodhart's Law: When Metrics Become Targets" },
      { category: "analytics", slug: "analytics-101", title: "Analytics 101" },
      { category: "analytics", slug: "ga4-setup", title: "GA4 Setup" },
      { category: "analytics", slug: "utm-tagging", title: "UTM Tagging" },
      { category: "analytics", slug: "conversion-tracking", title: "Conversion Tracking" },
      { category: "analytics", slug: "funnel-analysis", title: "Funnel Analytics" },
      { category: "analytics", slug: "attribution", title: "Attribution Models" },
      { category: "analytics", slug: "mmm", title: "Marketing Mix Modeling" },
      { category: "analytics", slug: "incrementality", title: "Incrementality Testing" },
      { category: "analytics", slug: "dashboards", title: "Marketing Dashboards" },
      { category: "analytics", slug: "kpis-for-marketers", title: "KPIs for Marketers" },
      { category: "analytics", slug: "dark-social", title: "Dark Social" },
      { category: "analytics", slug: "server-side-tracking", title: "Server-Side Tracking" },
      { category: "analytics", slug: "predictive-analytics", title: "Predictive Analytics" },
      { category: "growth", slug: "ab-testing", title: "A/B Testing & Statistical Significance" },
      { category: "growth", slug: "north-star-metric", title: "The North Star Metric" },
      { category: "fundamentals", slug: "marketing-math", title: "Marketing Math: CAC, LTV, ROAS, Payback" },
    ],
  },
  {
    slug: "freelancer-agency",
    title: "Freelancer & Agency Track",
    emoji: "🎯",
    description:
      "Master every channel clients will ask you to deliver. SEO, paid ads, social, email, analytics, and conversion, the full-stack toolkit for freelancers and agency marketers.",
    audience: "Freelancers & Agency Marketers",
    duration: "14-17 hours",
    lessons: [
      { category: "fundamentals", slug: "what-is-marketing", title: "What Marketing Actually Is" },
      { category: "fundamentals", slug: "value-proposition", title: "The Value Proposition" },
      { category: "fundamentals", slug: "marketing-math", title: "Marketing Math: CAC, LTV, ROAS, Payback" },
      { category: "seo", slug: "how-search-works", title: "How Search Engines Work" },
      { category: "seo", slug: "keyword-research", title: "Keyword Research" },
      { category: "seo", slug: "on-page-seo", title: "On-Page SEO" },
      { category: "paid-ads", slug: "paid-ads-101", title: "Paid Ads 101" },
      { category: "paid-ads", slug: "google-search-ads", title: "Google Search Ads" },
      { category: "paid-ads", slug: "meta-ads", title: "Meta Ads (Facebook & Instagram)" },
      { category: "social", slug: "instagram", title: "Instagram Playbook" },
      { category: "email", slug: "email-marketing-101", title: "Email Marketing 101" },
      { category: "copywriting", slug: "copywriting-101", title: "Copywriting 101" },
      { category: "cro", slug: "cro-101", title: "CRO 101" },
      { category: "analytics", slug: "analytics-101", title: "Analytics 101" },
      { category: "analytics", slug: "utm-tagging", title: "UTM Tagging" },
      { category: "tools", slug: "all-in-one-tools", title: "All-in-One Marketing Tools" },
    ],
  },
  {
    slug: "mental-models",
    title: "Marketing Mental Models Track",
    emoji: "🧠",
    description:
      "The reasoning tools that separate the marketer who executes tactics from the one who chooses the right tactic. First-principles, systems thinking, second-order effects, probabilistic decisions, and the meta-skills that compound across every channel and every era.",
    audience: "Ambitious Marketers at Any Level",
    duration: "10-13 hours",
    lessons: [
      { category: "mental-models", slug: "first-principles-thinking", title: "First-Principles Thinking" },
      { category: "mental-models", slug: "opportunity-cost-thinking", title: "Opportunity Cost Thinking" },
      { category: "mental-models", slug: "writing-to-think", title: "Writing to Think" },
      { category: "mental-models", slug: "pattern-recognition", title: "Pattern Recognition: The Marketer's Meta-Skill" },
      { category: "mental-models", slug: "base-rates-forecasting", title: "Base Rates and Reference-Class Forecasting" },
      { category: "mental-models", slug: "second-order-thinking", title: "Second-Order Thinking" },
      { category: "mental-models", slug: "inversion-thinking", title: "Inversion: Solving Problems Backwards" },
      { category: "mental-models", slug: "goodharts-law", title: "Goodhart's Law: When Metrics Become Targets" },
      { category: "mental-models", slug: "deliberate-practice", title: "Deliberate Practice for Marketers" },
      { category: "mental-models", slug: "systems-thinking", title: "Systems Thinking for Marketers" },
      { category: "mental-models", slug: "pareto-and-constraints", title: "The Pareto Principle and Theory of Constraints" },
      { category: "mental-models", slug: "bayesian-updating", title: "Bayesian Updating for Marketers" },
      { category: "mental-models", slug: "decision-making-under-uncertainty", title: "Decision-Making Under Uncertainty" },
    ],
  },
  {
    slug: "technical-seo",
    title: "Technical SEO Mastery Track",
    emoji: "⚙️",
    description:
      "The plumbing every other SEO discipline depends on. Crawling, indexing, Core Web Vitals, schema, security, log files, and AI-crawler access, the full technical audit skill set from foundations to migrations.",
    audience: "SEO Specialists & Web Developers",
    duration: "13-16 hours",
    lessons: [
      { category: "seo", slug: "how-search-works", title: "How Search Engines Actually Work" },
      { category: "seo", slug: "technical-seo", title: "Technical SEO" },
      { category: "seo", slug: "mobile-first-indexing", title: "Mobile-First Indexing" },
      { category: "seo", slug: "core-web-vitals", title: "Core Web Vitals" },
      { category: "seo", slug: "https-security-seo", title: "HTTPS & Security Headers for SEO" },
      { category: "seo", slug: "internal-linking", title: "Internal Linking & Site Architecture" },
      { category: "seo", slug: "schema-structured-data", title: "Schema & Structured Data" },
      { category: "seo", slug: "duplicate-thin-content", title: "Duplicate & Thin Content Cleanup" },
      { category: "seo", slug: "ecommerce-product-page-seo", title: "SEO for Ecommerce Product Pages" },
      { category: "seo", slug: "log-file-analysis", title: "Log File Analysis for SEO" },
      { category: "seo", slug: "llms-txt-ai-crawler-management", title: "llms.txt and AI Crawler Management" },
      { category: "seo", slug: "international-seo", title: "International SEO" },
      { category: "seo", slug: "seo-site-migrations", title: "SEO for Site Migrations" },
    ],
  },
  {
    slug: "ai-search-optimization",
    title: "AI Search Optimization Track",
    emoji: "🤖",
    description:
      "AEO, GEO, and AI Overview optimization in one place. Learn how ChatGPT, Perplexity, Gemini, Claude, and Google's AI Mode select and cite sources, and how to measure whether it's actually working.",
    audience: "SEO Specialists & AI-Forward Marketers",
    duration: "14-17 hours",
    lessons: [
      { category: "seo", slug: "aeo", title: "Answer Engine Optimization (AEO)" },
      { category: "seo", slug: "voice-search-seo", title: "Voice Search SEO" },
      { category: "seo", slug: "ai-overviews-geo", title: "AI Overviews & Generative Engine Optimization" },
      { category: "seo", slug: "ai-mode-search-optimization", title: "Optimizing for Google AI Mode" },
      { category: "seo", slug: "llmo", title: "LLM Optimization (LLMO)" },
      { category: "seo", slug: "seo-for-ai-platforms", title: "SEO for AI Platforms: Getting Cited in Perplexity, ChatGPT and Claude" },
      { category: "seo", slug: "eeat", title: "E-E-A-T" },
      { category: "seo", slug: "entity-seo", title: "Entity SEO & Knowledge Graph" },
      { category: "seo", slug: "content-clusters", title: "Content Clusters & Pillar Pages" },
      { category: "seo", slug: "zero-click-search", title: "Zero-Click Search" },
      { category: "seo", slug: "brand-serp-control", title: "Brand SERP Optimisation: Control What Google Shows for Your Name" },
      { category: "ai-marketing", slug: "ai-search-ranking", title: "Ranking Inside AI Answers" },
      { category: "ai-marketing", slug: "rag-for-marketers", title: "RAG for Marketers" },
      { category: "seo", slug: "ai-search-visibility-metrics", title: "Measuring AI Search Visibility" },
    ],
  },
  {
    slug: "content-strategy",
    title: "Content Strategy Mastery Track",
    emoji: "📝",
    description:
      "Plan, structure, and sustain content that compounds. Topic clusters, editorial calendars, refresh cycles, repurposing, original research, and using AI responsibly without triggering a scaled-content penalty.",
    audience: "Content Strategists & Marketing Leads",
    duration: "13-16 hours",
    lessons: [
      { category: "content", slug: "what-is-content-marketing", title: "What Content Marketing Really Is" },
      { category: "content", slug: "content-strategy", title: "Content Strategy" },
      { category: "seo", slug: "search-intent", title: "Search Intent" },
      { category: "content", slug: "topic-clusters", title: "Topic Clusters and Pillar Pages" },
      { category: "content", slug: "editorial-calendar", title: "Editorial Calendar" },
      { category: "seo", slug: "content-decay-refresh", title: "Content Decay: Refreshing and Reclaiming Lost Rankings" },
      { category: "content", slug: "repurposing", title: "Content Repurposing" },
      { category: "content", slug: "original-research-content", title: "Original Research as Content: The Link Magnet Strategy" },
      { category: "content", slug: "content-moats", title: "Content Moats" },
      { category: "content", slug: "ai-contentops-workflows", title: "AI Content Operations & Governance" },
      { category: "content", slug: "content-velocity-with-ai", title: "Scaling Content Velocity with AI: 10x Output, Not 10x Noise" },
      { category: "content", slug: "thought-leadership", title: "Thought Leadership" },
      { category: "content", slug: "blog-seo-content", title: "Blog and SEO Content" },
      { category: "content", slug: "long-form-vs-short-form-strategy", title: "Long-Form vs Short-Form Content Strategy: When Depth Wins" },
    ],
  },
  {
    slug: "paid-ads-mastery",
    title: "Paid Ads Mastery Track",
    emoji: "💸",
    description:
      "Every major paid channel in one track: Google Search, Meta, Shopping & PMax, YouTube, LinkedIn, TikTok. Bidding theory, creative testing, attribution, and fraud prevention.",
    audience: "Paid Media Specialists",
    duration: "15-18 hours",
    lessons: [
      { category: "paid-ads", slug: "paid-ads-101", title: "Paid Ads 101" },
      { category: "paid-ads", slug: "google-search-ads", title: "Google Search Ads" },
      { category: "paid-ads", slug: "meta-ads", title: "Meta Ads (Facebook & Instagram)" },
      { category: "paid-ads", slug: "quality-score", title: "Quality Score & Ad Rank" },
      { category: "paid-ads", slug: "bidding-strategies", title: "Bidding Strategies" },
      { category: "paid-ads", slug: "ad-copy-frameworks", title: "Ad Copy Frameworks" },
      { category: "paid-ads", slug: "creative-testing", title: "Creative Testing" },
      { category: "paid-ads", slug: "retargeting", title: "Retargeting" },
      { category: "paid-ads", slug: "google-shopping-pmax", title: "Google Shopping & Performance Max" },
      { category: "paid-ads", slug: "youtube-ads", title: "YouTube Ads" },
      { category: "paid-ads", slug: "linkedin-ads", title: "LinkedIn Ads" },
      { category: "paid-ads", slug: "tiktok-ads", title: "TikTok Ads" },
      { category: "paid-ads", slug: "programmatic-advertising", title: "Programmatic Advertising" },
      { category: "paid-ads", slug: "ios-attribution", title: "iOS 14+ & The Attribution Mess" },
      { category: "paid-ads", slug: "ad-fraud-invalid-traffic", title: "Ad Fraud & Invalid Traffic (IVT) Prevention" },
    ],
  },
  {
    slug: "email-lifecycle-mastery",
    title: "Email & Lifecycle Mastery Track",
    emoji: "📧",
    description:
      "The full lifecycle stack: list building, automation flows, segmentation, deliverability, and the compliance rules that keep you out of spam folders and legal trouble.",
    audience: "Lifecycle & CRM Marketers",
    duration: "15-18 hours",
    lessons: [
      { category: "email", slug: "email-marketing-101", title: "Email Marketing 101" },
      { category: "email", slug: "list-building", title: "List Building" },
      { category: "email", slug: "welcome-series", title: "The Welcome Series" },
      { category: "email", slug: "segmentation", title: "Segmentation" },
      { category: "email", slug: "automation-flows", title: "Email Automation Flows" },
      { category: "email", slug: "abandon-cart", title: "Abandoned Cart and Browse Flows" },
      { category: "email", slug: "subject-lines", title: "Email Subject Lines That Get Opened" },
      { category: "email", slug: "email-copywriting", title: "Email Copywriting" },
      { category: "email", slug: "ab-testing-email", title: "A/B Testing for Email Marketing" },
      { category: "email", slug: "deliverability", title: "Deliverability: SPF, DKIM, DMARC" },
      { category: "email", slug: "rfm", title: "RFM Segmentation" },
      { category: "email", slug: "winback", title: "Win-back Campaigns" },
      { category: "email", slug: "sms-marketing", title: "SMS Marketing" },
      { category: "email", slug: "zero-party-data", title: "Zero-Party Data Strategy" },
      { category: "email", slug: "gdpr-can-spam", title: "GDPR and CAN-SPAM for Email Marketers" },
    ],
  },
  {
    slug: "cro-mastery",
    title: "CRO & Conversion Mastery Track",
    emoji: "🎯",
    description:
      "Turn more visitors into customers, with the statistical rigor to trust your results. Landing pages, checkout flows, friction audits, and the math behind valid A/B tests.",
    audience: "CRO Specialists & Growth Marketers",
    duration: "14-17 hours",
    lessons: [
      { category: "cro", slug: "cro-101", title: "CRO 101: Turn More Visitors Into Customers" },
      { category: "cro", slug: "conversion-rate-math", title: "Conversion Rate Math" },
      { category: "cro", slug: "landing-page-anatomy", title: "Landing Page Anatomy" },
      { category: "cro", slug: "hero-formula", title: "The Hero Section Formula" },
      { category: "cro", slug: "form-optimization", title: "Form Optimization" },
      { category: "cro", slug: "checkout-optimization", title: "Checkout Optimization" },
      { category: "cro", slug: "friction-audit", title: "Friction Audit" },
      { category: "cro", slug: "exit-intent", title: "Exit Intent and Recovery" },
      { category: "cro", slug: "trust-signals", title: "Trust Signals: The Conversion Multiplier Most Sites Underuse" },
      { category: "cro", slug: "urgency-design", title: "Urgency and Scarcity Design" },
      { category: "cro", slug: "sample-size-math", title: "Sample Size Math" },
      { category: "cro", slug: "multivariate-vs-ab", title: "Multivariate Testing vs A/B Testing: When to Use Each" },
      { category: "cro", slug: "statistical-pitfalls-in-cro", title: "Statistical Pitfalls in CRO" },
      { category: "cro", slug: "cro-research", title: "Customer Research for CRO" },
      { category: "cro", slug: "personalization-cro", title: "Personalization for CRO" },
    ],
  },
  {
    slug: "analytics-mastery",
    title: "Analytics & Measurement Mastery Track",
    emoji: "📈",
    description:
      "Own the numbers. GA4 setup, attribution modeling, incrementality testing, marketing mix modeling, and reading a dashboard like an analyst even if you're not one.",
    audience: "Analytics-Focused Marketers",
    duration: "16-19 hours",
    lessons: [
      { category: "analytics", slug: "analytics-101", title: "Analytics 101" },
      { category: "analytics", slug: "ga4-setup", title: "GA4 Setup and Events" },
      { category: "analytics", slug: "utm-tagging", title: "UTM Tagging" },
      { category: "analytics", slug: "kpis-for-marketers", title: "KPIs for Marketers" },
      { category: "analytics", slug: "conversion-tracking", title: "Conversion Tracking" },
      { category: "analytics", slug: "funnel-analysis", title: "Funnel Analysis" },
      { category: "analytics", slug: "cohort-analysis", title: "Cohort Analysis" },
      { category: "analytics", slug: "attribution", title: "Marketing Attribution" },
      { category: "analytics", slug: "attribution-models", title: "Attribution Models" },
      { category: "analytics", slug: "incrementality", title: "Incrementality Testing" },
      { category: "analytics", slug: "mmm", title: "Marketing Mix Modeling" },
      { category: "analytics", slug: "dashboards", title: "Dashboards (Looker, etc.)" },
      { category: "analytics", slug: "predictive-analytics", title: "Predictive Analytics for Marketers" },
      { category: "analytics", slug: "server-side-tracking", title: "Server-Side Tracking" },
      { category: "analytics", slug: "privacy-sandbox", title: "Privacy Sandbox and Post-Cookie Web" },
    ],
  },
  {
    slug: "copywriting-mastery",
    title: "Copywriting Mastery Track",
    emoji: "✍️",
    description:
      "From AIDA to Ogilvy. Headlines, CTAs, landing page copy, storytelling frameworks, and how to write copy that gets cited by AI search engines, not just read by humans.",
    audience: "Copywriters & Content Marketers",
    duration: "14-17 hours",
    lessons: [
      { category: "copywriting", slug: "copywriting-101", title: "Copywriting 101" },
      { category: "copywriting", slug: "aida-pas-frameworks", title: "AIDA, PAS, and the Core Frameworks" },
      { category: "copywriting", slug: "headlines", title: "Writing Headlines That Convert" },
      { category: "copywriting", slug: "features-vs-benefits", title: "Features vs. Benefits: Writing Copy That Actually Converts" },
      { category: "copywriting", slug: "power-words", title: "Power Words: The Psychology Behind Copy That Converts" },
      { category: "copywriting", slug: "voice-and-tone", title: "Voice and Tone: Building a Brand Communication Style" },
      { category: "copywriting", slug: "landing-page-copy", title: "Landing Page Copy" },
      { category: "copywriting", slug: "cta-copy", title: "CTA Copy That Converts" },
      { category: "copywriting", slug: "email-copy", title: "Email Copywriting" },
      { category: "copywriting", slug: "storytelling-copy", title: "Storytelling in Copy" },
      { category: "copywriting", slug: "value-prop-copy", title: "Writing Value Proposition Copy That Converts" },
      { category: "copywriting", slug: "storybrand", title: "StoryBrand Framework" },
      { category: "copywriting", slug: "b2b-copy", title: "B2B Copy: Pain, Proof, Process" },
      { category: "copywriting", slug: "copy-for-ai-search", title: "Writing for AI Search: Copy That Gets Cited by ChatGPT and Perplexity" },
      { category: "copywriting", slug: "ogilvy-halbert-sugarman", title: "The Copywriting Canon: Ogilvy, Halbert, and Sugarman" },
    ],
  },
  {
    slug: "brand-strategy-mastery",
    title: "Brand Strategy Mastery Track",
    emoji: "🎨",
    description:
      "Positioning, visual identity, brand voice, and the crisis playbook. How brands actually grow, and how to protect what you've built once it's working.",
    audience: "Brand Strategists & CMOs",
    duration: "14-17 hours",
    lessons: [
      { category: "brand-strategy", slug: "brand-strategy-101", title: "Brand Strategy 101" },
      { category: "brand-strategy", slug: "brand-vs-marketing", title: "Brand vs. Marketing: What Is the Difference and Why It Matters" },
      { category: "brand-strategy", slug: "how-brands-grow", title: "How Brands Grow" },
      { category: "brand-strategy", slug: "brand-pillars", title: "Brand Pillars" },
      { category: "brand-strategy", slug: "brand-archetypes", title: "Brand Archetypes (Jung's 12)" },
      { category: "brand-strategy", slug: "visual-identity", title: "Visual Identity Systems" },
      { category: "brand-strategy", slug: "naming", title: "Brand Naming" },
      { category: "brand-strategy", slug: "brand-voice-system", title: "Build a Brand Voice System" },
      { category: "brand-strategy", slug: "brand-book", title: "Building a Brand Book" },
      { category: "brand-strategy", slug: "distinctive-assets", title: "Distinctive Brand Assets" },
      { category: "brand-strategy", slug: "brand-tracking", title: "Brand Tracking" },
      { category: "brand-strategy", slug: "brand-equity", title: "Brand Equity: Measurement, Valuation, and Protection" },
      { category: "brand-strategy", slug: "brand-crisis", title: "Brand Crisis Management" },
      { category: "brand-strategy", slug: "brand-in-ai-era", title: "Brand Building in the AI Era: Visibility When AI Answers Replace Search" },
    ],
  },
  {
    slug: "psychology-of-marketing",
    title: "Psychology of Marketing Track",
    emoji: "🧭",
    description:
      "The cognitive science behind every marketing decision: biases, influence principles, habit formation, and why System 1 thinking runs most purchase decisions.",
    audience: "Marketers Who Want to Understand Why, Not Just What",
    duration: "13-16 hours",
    lessons: [
      { category: "psychology", slug: "psychology-101", title: "Why Psychology Is the Real Marketing" },
      { category: "psychology", slug: "system-1-system-2", title: "System 1 and System 2 Thinking" },
      { category: "psychology", slug: "maslow-marketing", title: "Maslow Hierarchy for Marketers" },
      { category: "psychology", slug: "emotion-vs-logic", title: "Emotion First, Logic Second" },
      { category: "psychology", slug: "cognitive-biases", title: "Cognitive Biases Every Marketer Uses" },
      { category: "psychology", slug: "cialdini-6-principles", title: "Cialdini 6 Principles of Influence" },
      { category: "psychology", slug: "anchoring-framing", title: "Anchoring and Framing" },
      { category: "psychology", slug: "loss-aversion", title: "Loss Aversion" },
      { category: "psychology", slug: "scarcity-urgency", title: "Scarcity, Urgency, and FOMO" },
      { category: "psychology", slug: "social-proof-psychology", title: "The Psychology of Social Proof" },
      { category: "psychology", slug: "habit-loops", title: "Habit Loops: Cue, Routine, Reward" },
      { category: "psychology", slug: "behavioral-economics", title: "Behavioral Economics for Marketers" },
      { category: "psychology", slug: "choice-architecture", title: "Choice Architecture and Nudges" },
      { category: "psychology", slug: "peak-end-rule", title: "The Peak-End Rule" },
    ],
  },
  {
    slug: "pr-communications-mastery",
    title: "PR & Communications Mastery Track",
    emoji: "📣",
    description:
      "Media relations, press releases, crisis response, and digital PR that earns links instead of buying them. Built for anyone whose job is shaping the narrative.",
    audience: "PR & Communications Professionals",
    duration: "13-16 hours",
    lessons: [
      { category: "pr-communications", slug: "pr-101", title: "PR 101: What Public Relations Actually Is" },
      { category: "pr-communications", slug: "earned-owned-paid-media", title: "Earned, Owned, and Paid Media: The PR Perspective" },
      { category: "pr-communications", slug: "press-release-writing", title: "Press Release Writing: The Structure That Gets Picked Up" },
      { category: "pr-communications", slug: "press-kit-media-kit", title: "Building a Press Kit That Journalists Actually Use" },
      { category: "pr-communications", slug: "pitching-journalists", title: "Pitching Journalists: The Anatomy of a Pitch That Gets Read" },
      { category: "pr-communications", slug: "media-relations", title: "Media Relations: Building Real Journalist Relationships" },
      { category: "pr-communications", slug: "digital-pr-link-building", title: "Digital PR: Earning Links Through Coverage, Not Outreach Spam" },
      { category: "pr-communications", slug: "data-driven-pr", title: "Data-Driven PR: Turning Surveys and Proprietary Data Into Coverage" },
      { category: "pr-communications", slug: "newsjacking", title: "Newsjacking: Riding the News Cycle Without Getting Burned" },
      { category: "pr-communications", slug: "thought-leadership-pr", title: "Executive Visibility and Thought Leadership PR" },
      { category: "pr-communications", slug: "online-reputation-management", title: "Online Reputation Management: Owning Your Search Results" },
      { category: "pr-communications", slug: "analyst-relations", title: "Analyst Relations: Briefing Gartner, Forrester, and IDC" },
      { category: "pr-communications", slug: "crisis-pr-media-response", title: "Crisis PR: The Media-Facing Response Protocol" },
      { category: "pr-communications", slug: "measuring-pr-impact", title: "Measuring PR Impact: Beyond Vanity Metrics" },
    ],
  },
  {
    slug: "growth-marketing-mastery",
    title: "Growth Marketing Mastery Track",
    emoji: "🚀",
    description:
      "AARRR, growth loops, retention cohorts, and the experimentation discipline behind sustainable, compounding growth, not one-off hacks.",
    audience: "Growth Marketers & PLG Teams",
    duration: "14-17 hours",
    lessons: [
      { category: "growth", slug: "what-is-growth", title: "What Growth Marketing Really Is" },
      { category: "growth", slug: "aarrr", title: "AARRR: Pirate Metrics" },
      { category: "growth", slug: "north-star-metric", title: "The North Star Metric" },
      { category: "growth", slug: "activation", title: "Activation and Aha Moments" },
      { category: "growth", slug: "growth-loops", title: "Growth Loops" },
      { category: "growth", slug: "engagement-loops", title: "Engagement Loops" },
      { category: "growth", slug: "retention-cohorts", title: "Retention Cohorts: Measuring and Improving User Retention" },
      { category: "growth", slug: "referral-programs", title: "Referral Programs" },
      { category: "growth", slug: "viral-coefficient", title: "Viral Coefficient (K-Factor): Engineering Word-of-Mouth Growth" },
      { category: "growth", slug: "ab-testing", title: "A/B Testing and Statistical Significance" },
      { category: "growth", slug: "ice-rice-prioritization", title: "ICE and RICE Prioritization" },
      { category: "growth", slug: "plg", title: "Product-Led Growth (PLG)" },
      { category: "growth", slug: "net-revenue-retention", title: "Net Revenue Retention (NRR): The Metric That Decides If Growth Compounds" },
      { category: "growth", slug: "experimentation-program", title: "Building an Experimentation Program" },
    ],
  },
  {
    slug: "product-marketing-mastery",
    title: "Product Marketing Mastery Track",
    emoji: "🧩",
    description:
      "ICP, positioning, launches, competitive intelligence, and sales enablement, the full PMM stack for taking a product to market and keeping it winning.",
    audience: "Product Marketing Managers",
    duration: "13-16 hours",
    lessons: [
      { category: "product-marketing", slug: "pmm-101", title: "PMM 101: What Product Marketing Actually Is" },
      { category: "product-marketing", slug: "pmm-vs-marketing", title: "PMM vs Marketing: What Is Product Marketing?" },
      { category: "product-marketing", slug: "icp", title: "Ideal Customer Profile (ICP)" },
      { category: "product-marketing", slug: "positioning-doc", title: "The Positioning Doc" },
      { category: "product-marketing", slug: "messaging-hierarchy", title: "Messaging Hierarchy" },
      { category: "product-marketing", slug: "launches", title: "Product Launches" },
      { category: "product-marketing", slug: "competitive-intel", title: "Competitive Intelligence" },
      { category: "product-marketing", slug: "battlecard-design-adoption", title: "Battlecard Design & Sales Rep Adoption" },
      { category: "product-marketing", slug: "sales-enablement", title: "Sales Enablement" },
      { category: "product-marketing", slug: "pricing-packaging", title: "Pricing and Packaging Strategy" },
      { category: "product-marketing", slug: "customer-interviews", title: "Customer Interviews for Product Marketing" },
      { category: "product-marketing", slug: "win-loss-analysis", title: "Win-Loss Analysis" },
      { category: "product-marketing", slug: "analyst-relations", title: "Analyst Relations" },
      { category: "product-marketing", slug: "category-creation", title: "Category Creation: How to Own the Market You Invent" },
    ],
  },
  {
    slug: "on-page-seo-mastery",
    title: "On-Page SEO Mastery Track",
    emoji: "📄",
    description:
      "Everything on the page itself: titles, content depth, schema, speed, images, video, and mobile parity, the controllable levers that don't depend on anyone else linking to you.",
    audience: "SEO Specialists & Content Teams",
    duration: "13-16 hours",
    lessons: [
      { category: "seo", slug: "on-page-seo", title: "On-Page SEO" },
      { category: "seo", slug: "keyword-research", title: "Keyword Research" },
      { category: "seo", slug: "search-intent", title: "Search Intent" },
      { category: "copywriting", slug: "headlines", title: "Writing Headlines That Convert" },
      { category: "seo", slug: "internal-linking", title: "Internal Linking & Site Architecture" },
      { category: "seo", slug: "schema-structured-data", title: "Schema & Structured Data" },
      { category: "seo", slug: "core-web-vitals", title: "Core Web Vitals" },
      { category: "seo", slug: "mobile-first-indexing", title: "Mobile-First Indexing" },
      { category: "seo", slug: "image-seo-visual-search", title: "Image SEO & Visual Search Optimization" },
      { category: "seo", slug: "video-seo", title: "Video SEO: Ranking on YouTube and TikTok Search" },
      { category: "content", slug: "blog-seo-content", title: "Blog and SEO Content" },
      { category: "seo", slug: "ecommerce-product-page-seo", title: "SEO for Ecommerce Product Pages" },
      { category: "seo", slug: "duplicate-thin-content", title: "Duplicate & Thin Content Cleanup" },
    ],
  },
  {
    slug: "off-page-seo-mastery",
    title: "Off-Page SEO Mastery Track",
    emoji: "🔗",
    description:
      "Authority you earn, not build. Link earning, digital PR, entity SEO, E-E-A-T, reputation management, and the local/community signals search engines trust more than anything on your own site.",
    audience: "SEO Specialists & Digital PR Teams",
    duration: "13-16 hours",
    lessons: [
      { category: "seo", slug: "link-building", title: "Off-Page SEO & Link Building" },
      { category: "pr-communications", slug: "digital-pr-link-building", title: "Digital PR: Earning Links Through Coverage, Not Outreach Spam" },
      { category: "content", slug: "original-research-content", title: "Original Research as Content: The Link Magnet Strategy" },
      { category: "pr-communications", slug: "data-driven-pr", title: "Data-Driven PR: Turning Surveys and Proprietary Data Into Coverage" },
      { category: "pr-communications", slug: "pitching-journalists", title: "Pitching Journalists: The Anatomy of a Pitch That Gets Read" },
      { category: "pr-communications", slug: "media-relations", title: "Media Relations: Building Real Journalist Relationships" },
      { category: "pr-communications", slug: "newsjacking", title: "Newsjacking: Riding the News Cycle Without Getting Burned" },
      { category: "seo", slug: "entity-seo", title: "Entity SEO & Knowledge Graph" },
      { category: "seo", slug: "eeat", title: "E-E-A-T" },
      { category: "seo", slug: "local-seo", title: "Local SEO" },
      { category: "seo", slug: "reddit-forum-seo", title: "Reddit and Forum SEO: Why Google Loves Communities in 2026" },
      { category: "seo", slug: "brand-serp-control", title: "Brand SERP Optimisation: Control What Google Shows for Your Name" },
      { category: "pr-communications", slug: "online-reputation-management", title: "Online Reputation Management: Owning Your Search Results" },
    ],
  },
];

export function getTrack(slug: string): Track | undefined {
  return TRACKS.find((t) => t.slug === slug);
}
